# frozen_string_literal: true

module ZeoDev
  # Reading and writing the generated tables under `crates/` and
  # `bench/`.
  #
  # Every one of them is compared byte for byte by a test or by `--check`, so
  # writing is deliberate: LF endings, a trailing newline, and no
  # platform-dependent ordering anywhere. `write` refuses a cell containing a
  # tab or a newline rather than writing a file that reads back as different
  # columns.
  module Tsv
    module_function

    def row(*cells)
      cells.each do |c|
        s = c.to_s
        raise Error, "a TSV cell cannot contain a tab or newline: #{s.inspect}" if s.match?(/[\t\n\r]/)
      end
      cells.join("\t")
    end

    # `rows` is an array of arrays. `comments` are written first, each already
    # carrying its own `#`.
    def render(rows, comments: [])
      out = +""
      comments.each { |c| out << c << "\n" }
      rows.each { |r| out << row(*r) << "\n" }
      out
    end

    # Writes only when the bytes differ, so an unchanged ledger keeps its
    # mtime and a build that keys on it does not redo itself.
    def write(path, content)
      return false if File.exist?(path) && File.binread(path) == content

      File.binwrite(path, content)
      true
    end

    # `[comments, rows]`. A `#` line anywhere is a comment; every other line
    # splits on tabs.
    def read(path)
      comments = []
      rows = []
      File.readlines(path, chomp: true).each do |line|
        line.start_with?("#") ? comments << line : rows << line.split("\t", -1)
      end
      [comments, rows]
    end

    # `--check`: the committed copy against freshly generated bytes.
    def check(path, content, label: File.basename(path))
      if !File.exist?(path)
        warn "#{label} does not exist -- run the command without --check"
        return 1
      end
      if File.binread(path) == content
        puts "#{label} is up to date"
        return 0
      end

      warn "#{label} is stale -- re-run the command without --check"
      1
    end
  end
end
