//! Object model & dynamic dispatch. See the plan's "Object model & dynamic
//! dispatch" section for the full design rationale: two dispatch paths
//! (static direct/match-on-class_id calls, generated entirely by `spinelc`;
//! and this module's runtime `ClassRegistry`/`send`, reached only when
//! `spinelc` cannot resolve a call statically). Spinel itself never needs
//! this module at all -- it's the one deliberate architectural addition.

use crate::{RubyValue, Signal, Symbol};
use std::any::Any;
use std::collections::HashMap;
use std::sync::{Arc, OnceLock};

/// Identifies a Ruby class at runtime. Mirrors spinel's struct-embedded
/// `cls_id` field (`emit_class_struct`, codegen.c:2496). Since Phase 15.1
/// this is the SHARED `spinel-abi` type -- the compiler bakes the same
/// numbering into generated code from the same source of truth, so there is
/// nothing left to keep in sync by hand.
pub use spinel_abi::ClassId;

/// Implemented (via `ruby_class!`) by every generated Ruby class, and by the
/// built-in `Object` root below. `Send + Sync` supertrait bounds (Part 9):
/// satisfied automatically for every generated class once its own fields are
/// `parking_lot::Mutex`-wrapped, needing no manual `unsafe impl` anywhere.
pub trait RubyObject: Any + Send + Sync {
    fn class_id(&self) -> ClassId;

    /// Lets `send`'s dispatcher downcast an erased `RObj` back to its
    /// concrete type. No default body: a default `{ self }` here would be
    /// type-checked generically over an unsized `Self` (rustc checks default
    /// bodies once, not per-impl) and fail to coerce to `&dyn Any`. Each
    /// concrete impl provides the one-line body instead (`ruby_class!`
    /// generates it), where `Self` is always a concrete, sized type.
    fn as_any(&self) -> &dyn Any;

    /// The owned-handle counterpart to `as_any` -- needed because every
    /// generated method now takes `self: Arc<Self>` (not `&self`, see
    /// `ruby_class!`'s docs), so Path 2's dynamic trampolines need an
    /// `Arc<Concrete>`, not a `&Concrete`, to actually call one. `Arc<dyn Any
    /// + Send + Sync>` supports a real consuming `downcast::<T>()`; `Arc<dyn
    /// RubyObject>` doesn't (there's no such inherent method on an arbitrary
    /// trait object), so this is the bridge -- same "no default body"
    /// reasoning as `as_any` above.
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync>;

    /// `.frozen?` state (Phase 13.1) -- backed by the `__frozen: AtomicBool`
    /// field `ruby_class!` generates on every class struct (the per-object
    /// counterpart of `collections::Freezable`'s flag). On the trait (not
    /// just inherent) so `freeze_value`/`is_frozen_value` can reach it
    /// through an erased `RObj` without downcasting. The frozen CHECK before
    /// an ivar write is emitted by codegen (`emit_ivar_write_stmt`'s guard),
    /// which alone can construct the `FrozenError` to raise.
    fn is_frozen(&self) -> bool;

    /// Marks this object frozen -- `.freeze`'s storage half; a repeat call
    /// is a harmless no-op, matching CRuby's own already-frozen guard.
    fn set_frozen(&self);

    /// A snapshot of every ivar's current value (Phase 13.8) -- the runtime
    /// ivar ENUMERATION `Ractor`'s recursive shareability check and
    /// `make_shareable`'s deep-freeze traversal need (reading is enough;
    /// by-name ivar SETTING still doesn't exist, which is why an unfrozen
    /// Object can't be deep-copied across a Ractor boundary -- see
    /// `ractor`'s module docs). Generated by `ruby_class!` from its own
    /// ivar list.
    fn ivar_values(&self) -> Vec<RubyValue>;

    /// `Kernel#dup`/`#clone`'s per-class shallow copy (Phase 15.2): a fresh
    /// instance of the same concrete struct with every ivar's CURRENT value
    /// cloned into it (a `RubyValue` clone is a handle clone, so nested
    /// objects are SHARED -- CRuby's own shallow rule). `copy_frozen` is
    /// the one `dup`-vs-`clone` difference: `clone` carries the receiver's
    /// frozen flag over, `dup` starts unfrozen. Generated by `ruby_class!`
    /// from its own ivar list (only the concrete impl knows the fields);
    /// `initialize_copy`/singleton-state carryover are documented
    /// scope-cuts. See `RubyValue::dup_value` for the non-Object kinds.
    fn dup_object(&self, copy_frozen: bool) -> RObj;
}

/// A handle to any live Ruby object, used wherever the concrete class isn't
/// statically known. Mirrors spinel's boxed `sp_RbVal { tag: SP_TAG_OBJ,
/// cls_id, v: { p } }` (`lib/sp_gc.h:42`) for the object case -- except the
/// Rust trait object's vtable *is* the tag. Mutability lives on individual
/// ivar fields (see `ruby_class!`), not on this handle, so no lock layer is
/// needed here. `Arc` (not `Rc`, Part 9): every concrete `RubyObject` impl is
/// `Send + Sync` (via the trait's own supertrait bounds above), so this type
/// itself is genuinely `Send + Sync` -- no `unsafe impl` needed.
pub type RObj = Arc<dyn RubyObject>;

/// The root of every class hierarchy. `ClassId(0)`, no ivars, no
/// superclass -- the base case `ruby_class!`'s `$super` bottoms out at.
pub struct Object;

impl Object {
    pub const CLASS_ID: ClassId = ClassId(0);
}

/// Fixed, well-known `ClassId`s for every built-in Ruby type this spike
/// models as a `RubyValue` variant rather than a generated `ruby_class!`
/// struct -- numerically mirrored by `spinelc::compiler::BUILTIN_CLASSES`
/// (same "two `ClassId` types, on purpose" convention as `Object::CLASS_ID`/
/// `compiler::OBJECT_CLASS`). Registered into the `ClassRegistry` once, from
/// generated `main()` (`codegen::mod`'s `builtin_registrations`), with the
/// SAME linearized `ancestors` every user class gets -- what makes
/// `5.is_a?(Integer)`/`"x".is_a?(Object)`-style checks against a built-in-
/// typed receiver work uniformly through the one general `is_a`/`send`
/// mechanism, and the prerequisite for eventually `include`ing a plain-Ruby
/// `Enumerable`/`Comparable` into these types via ordinary materialization.
pub use spinel_abi::{
    ARRAY_CLASS, CLASS_CLASS, COMPARABLE_CLASS, FALSE_CLASS, FIBER_CLASS, FLOAT_CLASS,
    HASH_CLASS, INTEGER_CLASS, MATCH_DATA_CLASS, MODULE_CLASS, MUTEX_CLASS, NIL_CLASS,
    PROC_CLASS, QUEUE_CLASS, RACTOR_CLASS, RANGE_CLASS, REGEXP_CLASS, STRING_CLASS,
    THREAD_CLASS, TRUE_CLASS, SYMBOL_CLASS,
};
/// The builtin `Enumerable` MODULE (Phase 14.4 rev.2) -- consulted by
/// `send`'s Enumerable fallback (an Object whose registered ancestors
/// contain this id dispatches unresolved Enumerable-method names to
/// `crate::enumerable`). Like every id above, re-exported from the shared
/// `spinel-abi` numbering.
pub use spinel_abi::ENUMERABLE_CLASS;

impl RubyObject for Object {
    fn class_id(&self) -> ClassId {
        Self::CLASS_ID
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync> {
        self
    }
    // The root `Object` is never instantiated as a runtime value (no
    // `Object.new` path exists -- `emit_new` only constructs user classes),
    // so it has no `__frozen` field to consult; a fixed unfrozen answer
    // keeps the trait total without pretending at state that can't exist.
    fn is_frozen(&self) -> bool {
        false
    }
    fn set_frozen(&self) {}
    fn ivar_values(&self) -> Vec<RubyValue> {
        Vec::new()
    }
    // Never reachable for the same no-instantiation reason as `is_frozen`
    // above; a fresh stateless `Object` keeps the trait total.
    fn dup_object(&self, _copy_frozen: bool) -> RObj {
        Arc::new(Object)
    }
}

/// Downcasts an erased `RObj` to an owned `Arc<T>` -- the Path 2 trampoline
/// counterpart to `as_any().downcast_ref()`, needed because every generated
/// method takes `self: Arc<Self>` now (see `ruby_class!`'s docs). Cloning
/// `recv` first is a cheap `Arc` refcount bump, not a deep copy.
pub fn downcast_robj<T: RubyObject>(recv: &RObj) -> Option<Arc<T>> {
    recv.clone().as_any_rc().downcast::<T>().ok()
}

/// Every generated method/trampoline returns `Result<RubyValue, Signal>`, not
/// a bare `RubyValue` -- see `Signal`'s docs for why this is fixed from the
/// start rather than retrofitted once `break`/`raise`/non-local `return`
/// exist. The third parameter is the call's block, if any (`None` when no
/// block was given) -- see `signal.rs`'s `catch_break` and `codegen::params`'s
/// docs for how a block crosses the Path 2 boundary.
pub type MethodFn = fn(&RObj, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

/// A class's dynamic constructor (Phase 16.1): allocates a fresh instance
/// and runs its `initialize` (if any) -- what makes `x = Widget;
/// x.new(...)` work when the class is only known at runtime as a
/// `RubyValue::Class` value. Generated per class by `ruby_class!`
/// (`__construct`); `None` for modules and builtins.
pub type ConstructorFn = fn(&[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

struct ClassEntry {
    /// The Ruby-visible, fully-qualified name (`"Store::Item"`) -- what
    /// `Class#name`/`#to_s`/`puts Widget` print, and what `NoMethodError`
    /// messages cite (Phase 16.1, retiring the class-id-in-the-message
    /// approximation).
    name: String,
    is_module: bool,
    /// The full, already-linearized MRO (this class first, then prepends/
    /// includes/superclass in resolution order) -- computed at COMPILE time
    /// by `spinelc::analyze::mro::compute_ancestors` and baked in as a
    /// literal list by `ruby_class!`'s generated `__register`. Method
    /// dispatch itself never needs to walk this (every reachable method is
    /// already MATERIALIZED directly onto this class -- see the plan's Part
    /// 6), but `is_a`/rescue-by-class matching does.
    ancestors: Vec<ClassId>,
    methods: HashMap<Symbol, MethodFn>,
    constructor: Option<ConstructorFn>,
}

#[derive(Default)]
pub struct ClassRegistry {
    entries: HashMap<u32, ClassEntry>,
}

impl ClassRegistry {
    pub fn new() -> ClassRegistry {
        ClassRegistry::default()
    }

    /// Mirrors declaring a class's place in the hierarchy -- called once per
    /// class from that class's generated `__register` (or directly from
    /// generated `main()` for modules/builtins, which have no struct), with
    /// `ancestors` already fully linearized at spinelc compile time.
    pub fn register(
        &mut self,
        id: ClassId,
        name: &str,
        is_module: bool,
        ancestors: Vec<ClassId>,
        constructor: Option<ConstructorFn>,
    ) {
        self.entries.insert(
            id.0,
            ClassEntry {
                name: name.to_string(),
                is_module,
                ancestors,
                methods: HashMap::new(),
                constructor,
            },
        );
    }

    /// The runtime-mutable path `define_method`/`define_singleton_method`
    /// actually go through: a real `HashMap` insert, no compile-time
    /// literal-name restriction (contrast spinel's `walk_scope`, which can
    /// only register a `define_method` as a scope if the name is a literal).
    pub fn define_method(&mut self, id: ClassId, name: Symbol, f: MethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining methods on it")
            .methods
            .insert(name, f);
    }

    fn lookup(&self, id: ClassId, name: Symbol) -> Option<MethodFn> {
        self.entries.get(&id.0)?.methods.get(&name).copied()
    }

    fn ancestors_of(&self, id: ClassId) -> &[ClassId] {
        self.entries.get(&id.0).map_or(&[], |e| &e.ancestors)
    }
}

/// `recv_class.is_a?(target)` -- a real ancestry check against the SAME
/// linearized `ancestors` list `super`/reflection uses at compile time (see
/// `analyze::mro::compute_ancestors`'s docs), not spinel's own two-tier
/// "transplant for dispatch, shallower list for reflection" split (confirmed
/// to diverge on a module-of-module diamond -- see the plan). The one
/// runtime surface this spike needs for `Signal::Raise`/`rescue` matching:
/// there's no first-class `Class`/`Module` runtime VALUE (can't be stored in
/// a variable or reflected on generally), just this narrow "is this concrete
/// class id ancestor-compatible with that one" check.
pub fn is_a(recv_class: ClassId, target: ClassId) -> bool {
    registry().ancestors_of(recv_class).contains(&target)
}

/// `recv.respond_to?(:name)` -- a flat lookup on the receiver's own
/// already-materialized method table (every reachable method -- own,
/// inherited, or mixed-in -- is already present there, so no ancestor walk
/// is needed, mirroring `send`'s own dispatch below). Matches real Ruby's
/// default behavior (doesn't consult `method_missing`/`respond_to_missing?`,
/// which this spike doesn't model).
pub fn responds_to(recv_class: ClassId, name: Symbol) -> bool {
    registry().lookup(recv_class, name).is_some()
}

/// The registered Ruby-visible (fully-qualified) name of `id` -- `None`
/// when the registry isn't installed yet or has no such entry (this
/// crate's own unit tests; a real generated program registers everything
/// before any statement runs). See `RubyValue::Class`'s display arms for
/// the fallback rendering.
pub fn class_name(id: ClassId) -> Option<String> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.name.clone())
}

/// Whether `id` names a MODULE (drives `Widget.class` -> `Class` vs
/// `Enumerable.class` -> `Module`) -- same graceful `None` as `class_name`.
pub fn class_is_module(id: ClassId) -> Option<bool> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.is_module)
}

/// A registry probe-and-call for the runtime PROTOCOL dispatches (Phase
/// 16.2): user `==`/`<=>`/`to_s`/`inspect`/`hash` reached from deep inside
/// pure helpers (`rb_eq`, `display_with`, `hash_key`) that can't route
/// through `send` (whose `method_missing`/NoMethodError fallbacks must NOT
/// fire for a protocol probe). `None` = no such method (or no registry --
/// this crate's own unit tests), letting each caller apply its own
/// default; the method, when present, is the MATERIALIZED entry, so
/// inherited/mixed-in definitions resolve exactly like a real call.
pub(crate) fn call_user_method(
    recv: &RObj,
    name: &str,
    args: &[RubyValue],
) -> Option<Result<RubyValue, Signal>> {
    let f = REGISTRY.get()?.lookup(recv.class_id(), Symbol::intern(name))?;
    Some(f(recv, args, None))
}

/// A registry-optional ancestry probe (Phase 16.2) -- `false` when no
/// registry is installed (this crate's own unit tests), where `is_a`'s
/// hard `registry()` access would panic. Used by `rb_eq`'s Comparable
/// fallback, which must stay callable from anywhere.
pub(crate) fn ancestors_contain(id: ClassId, target: ClassId) -> bool {
    REGISTRY
        .get()
        .is_some_and(|r| r.ancestors_of(id).contains(&target))
}

/// Runs `initialize` on a freshly-constructed instance IF the class
/// defines one -- the shared tail of every `ConstructorFn` (`ruby_class!`'s
/// `__construct`). Deliberately a direct registry lookup, NOT `send`: a
/// class with no `initialize` must not trip the `method_missing` fallback.
/// With no `initialize`, arguments are rejected (real Ruby's
/// `Object#initialize` takes none) -- a loud panic, spike scope (no
/// `ArgumentError`-raising channel from this crate).
pub fn run_initialize(
    class: ClassId,
    recv: &RObj,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<(), Signal> {
    if let Some(f) = registry().lookup(class, Symbol::intern("initialize")) {
        f(recv, args, block)?;
        return Ok(());
    }
    if !args.is_empty() {
        panic!(
            "wrong number of arguments for initialize (given {}, expected 0)",
            args.len()
        );
    }
    Ok(())
}

/// The class registry is installed exactly once, from generated `main()`,
/// before any `Thread`/`Ractor` spawns anything (Part 9) -- a `OnceLock`
/// (not a `thread_local!`, unlike before the Send+Sync migration) gives
/// lock-free reads forever after that single write, and is itself the
/// correct semantic choice regardless of concurrency: classes/methods are
/// genuinely process-wide-shared in real Ruby, not per-thread state.
static REGISTRY: OnceLock<ClassRegistry> = OnceLock::new();

fn registry() -> &'static ClassRegistry {
    REGISTRY
        .get()
        .expect("class registry not installed -- install_class_registry must run first")
}

/// Called once from generated `main()`, after every class's `__register` has
/// populated the registry passed in.
pub fn install_class_registry(registry: ClassRegistry) {
    REGISTRY
        .set(registry)
        .unwrap_or_else(|_| panic!("class registry installed twice"));
}

/// Builds a `NoMethodError` exception value from a message -- installed once
/// from generated `main()` (alongside the registry), because this crate
/// cannot construct exception OBJECTS itself: the exception classes are
/// ordinary generated `ruby_class!` structs living in the generated
/// program's own crate (the same division of labor as `array_set`'s
/// `IndexError` contract). What lets `send`'s missing-method fallback raise
/// a real, catchable, thread-join-propagating Ruby exception (Phase 13.7)
/// instead of the old `process::exit(1)` -- which killed every OTHER
/// running Thread over one bad dispatch.
static NO_METHOD_ERROR_FACTORY: OnceLock<fn(String) -> RubyValue> = OnceLock::new();

pub fn install_no_method_error_factory(factory: fn(String) -> RubyValue) {
    NO_METHOD_ERROR_FACTORY
        .set(factory)
        .unwrap_or_else(|_| panic!("NoMethodError factory installed twice"));
}

/// The declarative table of dynamically-dispatchable BUILTIN methods
/// (Phase 15.1): one block per receiver kind, one row per
/// `(method name(s), arity) => body`, expanded into `send_value`'s match.
/// Before this macro the same surface was a hand-grown nest of match arms;
/// as a table it is ONE place to add a builtin method (Phase 17.1's breadth
/// lands as rows here), one place the user-override layer (Phase 16.3)
/// hooks in front of, and one place Phase 18's per-box overlay lookup keys.
///
/// Row contract: a row's body must `return` to ANSWER the call. Falling off
/// the end of a body (e.g. an argument-TYPE guard that didn't match, like
/// `Array#[]` with a non-Int index) falls through past the whole table to
/// the numeric-operator/Enumerable/NoMethodError stages after it, exactly
/// like an unlisted name does -- so partial rows degrade to Ruby's own
/// NoMethodError behavior, never to silent wrongness.
macro_rules! builtin_methods {
    (
        ($recv:ident, $name:ident, $args:ident);
        $( $variant:ident ( $($payload:pat),+ ) { $( $row:pat => $body:block )* } )*
    ) => {
        match $recv {
            $(
                RubyValue::$variant($($payload),+) => {
                    match ($name, $args.len()) {
                        $( $row => $body )*
                        _ => {}
                    }
                }
            )*
            _ => {}
        }
    };
}

/// The general dispatcher -- reached only on Path 2 (see module docs).
/// Since every reachable method (own, inherited, or mixed-in) is already
/// MATERIALIZED directly onto its receiver's own class at spinelc compile
/// time (see the plan's Part 6 -- no cloning-with-shadow-names,
/// monomorphization instead), this is now a FLAT lookup on the receiver's
/// own class -- no ancestor walk needed here at all, only for `is_a`
/// (above), which real dispatch doesn't need.
///
/// `block` is threaded through to whichever `MethodFn` is actually found --
/// including the `method_missing` fallback, matching real Ruby's own
/// `method_missing(name, *args, &block)` protocol.
/// Dynamic dispatch against ANY `RubyValue` receiver (Phase 14.4, closing
/// the long-standing "Poly-dispatch gap"): an `Object` goes through `send`'s
/// registry exactly as before; a BUILT-IN receiver (Array/Hash/String/...)
/// dispatches against a curated method table over the existing collection
/// helpers -- what makes `@items << x`, `@hash[k] = v`, `ks.length` work on
/// ivars/params/any dynamically-typed value. Codegen's every Poly-receiver
/// fallback (ordinary calls, `send`/`public_send`, safe-nav, and the
/// runtime OPERATOR fallback's non-numeric case) routes here.
///
/// The table is deliberately curated, not exhaustive: entries exist for the
/// operations the static `try_collection_dispatch` fast path also supports
/// (extended as packages need them); anything else raises the same real,
/// rescuable `NoMethodError` an unknown Object method does -- with the
/// builtin class's REAL name in the message (better than `send`'s
/// documented class-id approximation, since builtin names are known here).
pub fn send_value(
    recv: &RubyValue,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    if let RubyValue::Object(o) = recv {
        return send(o, name, args, block);
    }
    let n = name.name();
    let n = n.as_str();
    // Universal builtin methods first: `==`/`!=` via `rb_eq` (Ruby's own
    // cross-numeric-tower `==`), `dup`/`clone` via `dup_value` (Phase
    // 15.2), and the reflection set (Phase 16.1: `.class` on everything;
    // `is_a?`/`kind_of?`/`instance_of?` against a runtime Class value) --
    // for every non-Object receiver. (Builtins can't be reopened until
    // Phase 16.3, so there's no user override to consult yet.)
    match (n, args.len()) {
        ("==", 1) => return Ok(RubyValue::Bool(recv.rb_eq(&args[0]))),
        ("!=", 1) => return Ok(RubyValue::Bool(!recv.rb_eq(&args[0]))),
        ("dup", 0) => return Ok(recv.dup_value(false)),
        ("clone", 0) => return Ok(recv.dup_value(true)),
        ("class", 0) => return Ok(RubyValue::Class(recv.class_id())),
        // `Object#hash`, universally (Phase 16.2) -- what a user-defined
        // `hash` typically delegates to (`def hash; k.hash; end`).
        ("hash", 0) => return Ok(RubyValue::Int(crate::value_hash_code(recv))),
        ("is_a?" | "kind_of?", 1) => {
            if let RubyValue::Class(target) = &args[0] {
                return Ok(RubyValue::Bool(is_a(recv.class_id(), *target)));
            }
        }
        ("instance_of?", 1) => {
            if let RubyValue::Class(target) = &args[0] {
                return Ok(RubyValue::Bool(recv.class_id() == *target));
            }
        }
        _ => {}
    }
    // A first-class Class/Module receiver (Phase 16.1): the reflection set
    // plus the dynamic constructor -- `x = Widget; x.new(...)`.
    if let RubyValue::Class(cid) = recv {
        let entry_name = class_name(*cid);
        match (n, args.len()) {
            ("new", _) => {
                let ctor = registry().entries.get(&cid.0).and_then(|e| e.constructor);
                match ctor {
                    Some(ctor) => return ctor(args, block),
                    // Modules (and builtins) have no allocator -- real
                    // Ruby's NoMethodError for a module, TypeError for a
                    // builtin without one; both surface through the same
                    // NoMethodError channel here (documented spike-scope
                    // flattening for the builtin case).
                    None => {
                        let msg = format!(
                            "undefined method 'new' for module {}",
                            entry_name.as_deref().unwrap_or("<anonymous>")
                        );
                        match NO_METHOD_ERROR_FACTORY.get() {
                            Some(factory) => return Err(Signal::Raise(factory(msg))),
                            None => panic!("{msg}"),
                        }
                    }
                }
            }
            ("name" | "to_s" | "inspect", 0) => {
                let name = entry_name
                    .unwrap_or_else(|| format!("#<Class:{}>", cid.0));
                return Ok(RubyValue::Str(crate::string_new(name)));
            }
            ("ancestors", 0) => {
                let ancestors = registry()
                    .ancestors_of(*cid)
                    .iter()
                    .map(|&a| RubyValue::Class(a))
                    .collect();
                return Ok(RubyValue::Array(crate::array_new(ancestors)));
            }
            // Explicit `Module#===` (Phase 16.2) -- the same instance-of
            // ancestry check `case`/`when` desugars to via `rb_case_eq`.
            ("===", 1) => {
                return Ok(RubyValue::Bool(is_a(args[0].class_id(), *cid)));
            }
            _ => {}
        }
    }
    builtin_methods! {
        (recv, n, args);
        Array(arr) {
            ("[]", 1) => {
                if let RubyValue::Int(i) = &args[0] {
                    return Ok(crate::array_get(arr, *i));
                }
            }
            ("[]=", 2) => {
                if let RubyValue::Int(i) = &args[0] {
                    // Same silent-out-of-range posture as the static path's
                    // `array_set` call sites: `None` (a raise) is the
                    // codegen-built `IndexError`'s job on the static path;
                    // dynamically we panic loudly instead of building one.
                    return match crate::array_set(arr, *i, args[1].clone()) {
                        Some(v) => Ok(v),
                        None => panic!("index {} too small for array (IndexError; spike scope: raised as a panic on the dynamic path)", match &args[0] { RubyValue::Int(i) => *i, _ => unreachable!() }),
                    };
                }
            }
            ("<<" | "push", 1) => { return Ok(crate::array_push(arr, args[0].clone())); }
            ("length" | "size", 0) => { return Ok(RubyValue::Int(crate::array_len(arr))); }
            ("include?" | "member?", 1) => {
                return Ok(RubyValue::Bool(crate::array_include(arr, &args[0])));
            }
            ("empty?", 0) => { return Ok(RubyValue::Bool(crate::array_len(arr) == 0)); }
            ("first", 0) => { return Ok(crate::array_get(arr, 0)); }
            ("last", 0) => { return Ok(crate::array_get(arr, -1)); }
            ("to_a", 0) => { return Ok(recv.clone()); }
            ("each", 0) => {
                let Some(RubyValue::Proc(p)) = &block else {
                    panic!("Array#each without a block isn't supported (no Enumerator; spike scope)");
                };
                // Snapshot: mutating the array from inside the block
                // iterates the original elements (a deliberate, simpler
                // rule than CRuby's live-view semantics).
                let elems: Vec<RubyValue> = arr.lock().clone();
                for e in elems {
                    p(&[e])?;
                }
                return Ok(recv.clone());
            }
        }
        Hash(h) {
            ("[]", 1) => { return Ok(crate::hash_get(h, &args[0])); }
            ("[]=", 2) => { return Ok(crate::hash_set(h, args[0].clone(), args[1].clone())); }
            ("delete", 1) => { return Ok(crate::hash_delete(h, &args[0])); }
            ("key?" | "has_key?" | "include?" | "member?", 1) => {
                return Ok(RubyValue::Bool(crate::hash_has_key(h, &args[0])));
            }
            ("keys", 0) => { return Ok(crate::hash_keys(h)); }
            ("values", 0) => { return Ok(crate::hash_values(h)); }
            ("length" | "size", 0) => { return Ok(RubyValue::Int(crate::hash_len(h))); }
            ("empty?", 0) => { return Ok(RubyValue::Bool(crate::hash_len(h) == 0)); }
            ("each", 0) => {
                let Some(RubyValue::Proc(p)) = &block else {
                    panic!("Hash#each without a block isn't supported (no Enumerator; spike scope)");
                };
                let pairs: Vec<(RubyValue, RubyValue)> =
                    h.lock().values().cloned().collect();
                for (k, v) in pairs {
                    p(&[k, v])?;
                }
                return Ok(recv.clone());
            }
        }
        Str(s) {
            ("length" | "size", 0) => { return Ok(RubyValue::Int(crate::string_len(s))); }
            ("empty?", 0) => { return Ok(RubyValue::Bool(crate::string_len(s) == 0)); }
            ("include?", 1) => {
                if let RubyValue::Str(needle) = &args[0] {
                    let found = s.lock().contains(&*needle.lock());
                    return Ok(RubyValue::Bool(found));
                }
            }
            ("+", 1) => {
                if let RubyValue::Str(other) = &args[0] {
                    let joined = format!("{}{}", s.lock(), other.lock());
                    return Ok(RubyValue::Str(crate::string_new(joined)));
                }
            }
            ("to_s", 0) => { return Ok(recv.clone()); }
        }
        // The one Range iteration primitive Enumerable needs -- Array/Hash/
        // Range are the builtin `include Enumerable` set (real Ruby's own),
        // and an unresolved name on any of them tries the Rust Enumerable
        // implementation below before NoMethodError.
        Range(start, end, exclusive) {
            ("each", 0) => {
                let Some(RubyValue::Proc(p)) = &block else {
                    panic!("Range#each without a block isn't supported (no Enumerator; spike scope)");
                };
                let (Some(s), Some(e)) = (start.as_deref(), end.as_deref()) else {
                    panic!("can't iterate from a beginless/endless Range (spike scope)");
                };
                let (RubyValue::Int(s), RubyValue::Int(e)) = (s, e) else {
                    panic!("can't iterate a non-Integer Range (spike scope)");
                };
                let last = if *exclusive { *e - 1 } else { *e };
                let mut i = *s;
                while i <= last {
                    p(&[RubyValue::Int(i)])?;
                    i += 1;
                }
                return Ok(recv.clone());
            }
        }
    }
    // Universal `to_s`/`inspect` (Phase 16.2), placed AFTER the curated
    // tables so `String#to_s`'s identity-preserving row still wins:
    // `nil.inspect` -> "nil", `5.to_s` -> "5", `[1, 2].inspect` ->
    // "[1, 2]" -- the same rendering `puts`/`p` already print.
    match (n, args.len()) {
        ("to_s", 0) => {
            return Ok(RubyValue::Str(crate::string_new(recv.to_display_string())))
        }
        ("inspect", 0) => {
            return Ok(RubyValue::Str(crate::string_new(recv.inspect_string())))
        }
        _ => {}
    }
    // Numeric receivers: the binary operators, so `5.send(:+, 2)` and --
    // the motivating case -- `reduce(:+)`'s per-element
    // `send_value(acc, op, [elem])` dispatch work (real Ruby supports
    // both; codegen's static/runtime-checked arithmetic normally handles
    // these without ever reaching dynamic dispatch). Mixed Int/Float
    // promotes to Float, the same numeric-tower rule the static fallback
    // uses.
    {
        let nums = match (recv, args.first()) {
            (RubyValue::Int(a), Some(RubyValue::Int(b))) if args.len() == 1 => {
                Some((None, Some((*a, *b))))
            }
            (RubyValue::Int(a), Some(RubyValue::Float(b))) if args.len() == 1 => {
                Some((Some((*a as f64, *b)), None))
            }
            (RubyValue::Float(a), Some(RubyValue::Int(b))) if args.len() == 1 => {
                Some((Some((*a, *b as f64)), None))
            }
            (RubyValue::Float(a), Some(RubyValue::Float(b))) if args.len() == 1 => {
                Some((Some((*a, *b)), None))
            }
            _ => None,
        };
        if let Some((float_pair, int_pair)) = nums {
            if let Some((a, b)) = int_pair {
                let r = match n {
                    "+" => Some(RubyValue::Int(crate::int_add(a, b))),
                    "-" => Some(RubyValue::Int(crate::int_sub(a, b))),
                    "*" => Some(RubyValue::Int(crate::int_mul(a, b))),
                    "/" => Some(RubyValue::Int(crate::int_div(a, b))),
                    "%" => Some(RubyValue::Int(crate::int_mod(a, b))),
                    "**" => Some(RubyValue::Int(crate::int_pow(a, b))),
                    "<=>" => Some(RubyValue::Int(crate::int_cmp(a, b))),
                    "<" => Some(RubyValue::Bool(crate::int_lt(a, b))),
                    ">" => Some(RubyValue::Bool(crate::int_gt(a, b))),
                    "<=" => Some(RubyValue::Bool(crate::int_le(a, b))),
                    ">=" => Some(RubyValue::Bool(crate::int_ge(a, b))),
                    _ => None,
                };
                if let Some(r) = r {
                    return Ok(r);
                }
            }
            if let Some((a, b)) = float_pair {
                let r = match n {
                    "+" => Some(RubyValue::Float(crate::float_add(a, b))),
                    "-" => Some(RubyValue::Float(crate::float_sub(a, b))),
                    "*" => Some(RubyValue::Float(crate::float_mul(a, b))),
                    "/" => Some(RubyValue::Float(crate::float_div(a, b))),
                    "%" => Some(RubyValue::Float(crate::float_mod(a, b))),
                    "**" => Some(RubyValue::Float(crate::float_pow(a, b))),
                    "<" => Some(RubyValue::Bool(a < b)),
                    ">" => Some(RubyValue::Bool(a > b)),
                    "<=" => Some(RubyValue::Bool(a <= b)),
                    ">=" => Some(RubyValue::Bool(a >= b)),
                    "<=>" => Some(match crate::float_cmp(a, b) {
                        Some(o) => RubyValue::Int(o),
                        None => RubyValue::Nil,
                    }),
                    _ => None,
                };
                if let Some(r) = r {
                    return Ok(r);
                }
            }
        }
    }
    // The builtin `include Enumerable` set (Array/Hash/Range -- real
    // Ruby's own), hardcoded rather than registry-consulted so this works
    // registry-less too (this crate's own unit tests): an unresolved name
    // on one of these tries the Rust Enumerable implementation before the
    // NoMethodError below.
    if matches!(
        recv,
        RubyValue::Array(_) | RubyValue::Hash(_) | RubyValue::Range(..)
    ) {
        if let Some(r) = crate::enumerable::enumerable_send(recv, n, args, block.clone()) {
            return r;
        }
    }
    // A class/module receiver gets real Ruby's own distinct message shape
    // ("for class Widget" / "for module Helper", oracle-verified) rather
    // than the instance form below.
    if let RubyValue::Class(cid) = recv {
        let kind = if class_is_module(*cid).unwrap_or(false) { "module" } else { "class" };
        let msg = format!(
            "undefined method '{name}' for {kind} {}",
            class_name(*cid).unwrap_or_else(|| format!("#<Class:{}>", cid.0))
        );
        match NO_METHOD_ERROR_FACTORY.get() {
            Some(factory) => return Err(Signal::Raise(factory(msg))),
            None => panic!("{msg}"),
        }
    }
    let class_name = match recv {
        RubyValue::Nil => "NilClass",
        RubyValue::Bool(true) => "TrueClass",
        RubyValue::Bool(false) => "FalseClass",
        RubyValue::Int(_) => "Integer",
        RubyValue::Float(_) => "Float",
        RubyValue::Symbol(_) => "Symbol",
        RubyValue::Str(_) => "String",
        RubyValue::Array(_) => "Array",
        RubyValue::Hash(_) => "Hash",
        RubyValue::Range(..) => "Range",
        RubyValue::Proc(_) => "Proc",
        RubyValue::Regexp(_) => "Regexp",
        RubyValue::MatchData(_) => "MatchData",
        RubyValue::Fiber(_) => "Fiber",
        RubyValue::Thread(_) => "Thread",
        RubyValue::Mutex(_) => "Mutex",
        RubyValue::Queue(_) => "Queue",
        RubyValue::Ractor(_) => "Ractor",
        RubyValue::Object(_) | RubyValue::Class(_) => unreachable!("handled above"),
    };
    let msg = format!("undefined method '{name}' for an instance of {class_name}");
    match NO_METHOD_ERROR_FACTORY.get() {
        Some(factory) => Err(Signal::Raise(factory(msg))),
        None => panic!("{msg}"),
    }
}

pub fn send(
    recv: &RObj,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    let id = recv.class_id();
    if let Some(f) = registry().lookup(id, name) {
        return f(recv, args, block);
    }

    // Universal `Kernel#dup`/`#clone` (Phase 15.2) and the reflection set
    // (Phase 16.1). Placement mirrors real Ruby's lookup order exactly: an
    // ordinary ancestor-chain method (the registry lookup above) wins over
    // Kernel's, and Kernel's wins over `method_missing` (a real method is
    // always found before the missing-method fallback fires).
    if args.is_empty() {
        match name.name().as_str() {
            "dup" => return Ok(RubyValue::Object(recv.dup_object(false))),
            "clone" => return Ok(RubyValue::Object(recv.dup_object(true))),
            "class" => return Ok(RubyValue::Class(id)),
            // Identity-based when no user `hash` exists (the registry
            // lookup above already missed); `value_hash_code` re-probes,
            // finds none, and digests by identity.
            "hash" => {
                return Ok(RubyValue::Int(crate::value_hash_code(
                    &RubyValue::Object(recv.clone()),
                )))
            }
            // Default `Object#to_s`/`#inspect` (the user-defined form was
            // the registry lookup above): the `#<FQName>` rendering
            // `display_with`/`inspect_with` produce.
            "to_s" => {
                return Ok(RubyValue::Str(crate::string_new(
                    RubyValue::Object(recv.clone()).to_display_string(),
                )))
            }
            "inspect" => {
                return Ok(RubyValue::Str(crate::string_new(
                    RubyValue::Object(recv.clone()).inspect_string(),
                )))
            }
            _ => {}
        }
    }
    if args.len() == 1 {
        if let RubyValue::Class(target) = &args[0] {
            match name.name().as_str() {
                "is_a?" | "kind_of?" => return Ok(RubyValue::Bool(is_a(id, *target))),
                "instance_of?" => return Ok(RubyValue::Bool(id == *target)),
                _ => {}
            }
        }
        // `Object#==`'s reference-identity default (Phase 16.2) -- reached
        // only when the class defines no `==` of its own (the registry
        // lookup above wins otherwise), before `method_missing` like every
        // real Kernel/Object method.
        match name.name().as_str() {
            "==" => {
                return Ok(RubyValue::Bool(
                    RubyValue::Object(recv.clone()).rb_eq(&args[0]),
                ))
            }
            "!=" => {
                return Ok(RubyValue::Bool(
                    !RubyValue::Object(recv.clone()).rb_eq(&args[0]),
                ))
            }
            _ => {}
        }
    }

    // method_missing fallback, with `name` prepended to args (mirrors
    // CRuby's own protocol).
    let mm = Symbol::intern("method_missing");
    if let Some(f) = registry().lookup(id, mm) {
        let mut full_args = Vec::with_capacity(args.len() + 1);
        full_args.push(RubyValue::Symbol(name));
        full_args.extend_from_slice(args);
        return f(recv, &full_args, block);
    }

    // A real, catchable `NoMethodError` (Phase 13.7, replacing the original
    // eprintln-and-`process::exit(1)` shortcut): propagates like any other
    // raised exception -- rescuable at the call site, re-raised at a
    // Thread's `join`/`value` if uncaught there, and printed by the
    // top-level uncaught handler otherwise. A whole-process kill over one
    // bad dispatch in one Thread was never right once real threads existed.
    // The class-ID-in-the-message (vs. real Ruby's class NAME) is the
    // pre-existing, documented no-runtime-class-name-table approximation.
    // A user class that `include Enumerable` (its registered ancestors
    // carry ENUMERABLE_CLASS): unresolved names try the Rust Enumerable
    // implementation (which drives this object's own `each` back through
    // dynamic dispatch) before raising.
    if is_a(id, ENUMERABLE_CLASS) {
        if let Some(r) = crate::enumerable::enumerable_send(
            &RubyValue::Object(recv.clone()),
            &name.name(),
            args,
            block,
        ) {
            return r;
        }
    }
    // Same architecture for `include Comparable` (Phase 16.2): unresolved
    // names try the Rust Comparable implementation, which drives this
    // object's own `<=>` -- the compar.c pattern.
    if is_a(id, COMPARABLE_CLASS) {
        if let Some(r) = crate::comparable::comparable_send(recv, &name.name(), args) {
            return r;
        }
    }

    // The registered class NAME (Phase 16.1, retiring the documented
    // class-id approximation) -- real Ruby's exact message shape.
    let msg = format!(
        "undefined method '{name}' for an instance of {}",
        class_name(id).unwrap_or_else(|| format!("class {}", id.0))
    );
    match NO_METHOD_ERROR_FACTORY.get() {
        Some(factory) => Err(Signal::Raise(factory(msg))),
        // Only reachable outside a generated program (this crate's own unit
        // tests, which install no factory) -- a loud panic, not silent.
        None => panic!("{msg}"),
    }
}
