//! Object model & dynamic dispatch. See the plan's "Object model & dynamic
//! dispatch" section for the full design rationale: two dispatch paths
//! (static direct/match-on-class_id calls, generated entirely by `spinelc`;
//! and this module's runtime `ClassRegistry`/`send`, reached only when
//! `spinelc` cannot resolve a call statically). Spinel itself never needs
//! this module at all -- it's the one deliberate architectural addition.

use crate::{RubyValue, Signal, Symbol};
use std::any::Any;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, OnceLock};

/// Identifies a Ruby class at runtime. Mirrors spinel's struct-embedded
/// `cls_id` field (`emit_class_struct`, codegen.c:2496). Since Phase 15.1
/// this is the SHARED `spinel-abi` type -- the compiler bakes the same
/// numbering into generated code from the same source of truth, so there is
/// nothing left to keep in sync by hand.
pub use spinel_abi::ClassId;

/// Implemented (via `ruby_class!`) by every generated Ruby class, and by the
/// built-in `Object` root below. `Send + Sync` supertrait bounds (Part 9):
/// satisfied automatically for every generated class once its own fields are
/// `parking_lot::Mutex`-wrapped, needing no manual `unsafe impl` anywhere.
pub trait RubyObject: Any + Send + Sync {
    fn class_id(&self) -> ClassId;

    /// Lets `send`'s dispatcher downcast an erased `RObj` back to its
    /// concrete type. No default body: a default `{ self }` here would be
    /// type-checked generically over an unsized `Self` (rustc checks default
    /// bodies once, not per-impl) and fail to coerce to `&dyn Any`. Each
    /// concrete impl provides the one-line body instead (`ruby_class!`
    /// generates it), where `Self` is always a concrete, sized type.
    fn as_any(&self) -> &dyn Any;

    /// The owned-handle counterpart to `as_any` -- needed because every
    /// generated method now takes `self: Arc<Self>` (not `&self`, see
    /// `ruby_class!`'s docs), so Path 2's dynamic trampolines need an
    /// `Arc<Concrete>`, not a `&Concrete`, to actually call one. `Arc<dyn Any
    /// + Send + Sync>` supports a real consuming `downcast::<T>()`; `Arc<dyn
    /// RubyObject>` doesn't (there's no such inherent method on an arbitrary
    /// trait object), so this is the bridge -- same "no default body"
    /// reasoning as `as_any` above.
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync>;

    /// `.frozen?` state (Phase 13.1) -- backed by the `__frozen: AtomicBool`
    /// field `ruby_class!` generates on every class struct (the per-object
    /// counterpart of `collections::Freezable`'s flag). On the trait (not
    /// just inherent) so `freeze_value`/`is_frozen_value` can reach it
    /// through an erased `RObj` without downcasting. The frozen CHECK before
    /// an ivar write is emitted by codegen (`emit_ivar_write_stmt`'s guard),
    /// which alone can construct the `FrozenError` to raise.
    fn is_frozen(&self) -> bool;

    /// Marks this object frozen -- `.freeze`'s storage half; a repeat call
    /// is a harmless no-op, matching CRuby's own already-frozen guard.
    fn set_frozen(&self);

    /// A snapshot of every ivar's current value (Phase 13.8) -- the runtime
    /// ivar ENUMERATION `Ractor`'s recursive shareability check and
    /// `make_shareable`'s deep-freeze traversal need (reading is enough;
    /// by-name ivar SETTING still doesn't exist, which is why an unfrozen
    /// Object can't be deep-copied across a Ractor boundary -- see
    /// `ractor`'s module docs). Generated by `ruby_class!` from its own
    /// ivar list.
    fn ivar_values(&self) -> Vec<RubyValue>;

    /// `Kernel#dup`/`#clone`'s per-class shallow copy (Phase 15.2): a fresh
    /// instance of the same concrete struct with every ivar's CURRENT value
    /// cloned into it (a `RubyValue` clone is a handle clone, so nested
    /// objects are SHARED -- CRuby's own shallow rule). `copy_frozen` is
    /// the one `dup`-vs-`clone` difference: `clone` carries the receiver's
    /// frozen flag over, `dup` starts unfrozen. Generated by `ruby_class!`
    /// from its own ivar list (only the concrete impl knows the fields);
    /// `initialize_copy`/singleton-state carryover are documented
    /// scope-cuts. See `RubyValue::dup_value` for the non-Object kinds.
    fn dup_object(&self, copy_frozen: bool) -> RObj;
}

/// A handle to any live Ruby object, used wherever the concrete class isn't
/// statically known. Mirrors spinel's boxed `sp_RbVal { tag: SP_TAG_OBJ,
/// cls_id, v: { p } }` (`lib/sp_gc.h:42`) for the object case -- except the
/// Rust trait object's vtable *is* the tag. Mutability lives on individual
/// ivar fields (see `ruby_class!`), not on this handle, so no lock layer is
/// needed here. `Arc` (not `Rc`, Part 9): every concrete `RubyObject` impl is
/// `Send + Sync` (via the trait's own supertrait bounds above), so this type
/// itself is genuinely `Send + Sync` -- no `unsafe impl` needed.
pub type RObj = Arc<dyn RubyObject>;

/// The root of every class hierarchy. `ClassId(0)`, no ivars, no
/// superclass -- the base case `ruby_class!`'s `$super` bottoms out at.
pub struct Object;

impl Object {
    pub const CLASS_ID: ClassId = ClassId(0);
}

/// Fixed, well-known `ClassId`s for every built-in Ruby type this spike
/// models as a `RubyValue` variant rather than a generated `ruby_class!`
/// struct -- numerically mirrored by `spinelc::compiler::BUILTIN_CLASSES`
/// (same "two `ClassId` types, on purpose" convention as `Object::CLASS_ID`/
/// `compiler::OBJECT_CLASS`). Registered into the `ClassRegistry` once, from
/// generated `main()` (`codegen::mod`'s `builtin_registrations`), with the
/// SAME linearized `ancestors` every user class gets -- what makes
/// `5.is_a?(Integer)`/`"x".is_a?(Object)`-style checks against a built-in-
/// typed receiver work uniformly through the one general `is_a`/`send`
/// mechanism, and the prerequisite for eventually `include`ing a plain-Ruby
/// `Enumerable`/`Comparable` into these types via ordinary materialization.
pub use spinel_abi::{
    ARRAY_CLASS, BASIC_OBJECT_CLASS, CLASS_CLASS, COMPARABLE_CLASS, COMPLEX_CLASS,
    ENUMERATOR_CLASS, FALSE_CLASS, FIBER_CLASS, FLOAT_CLASS, HASH_CLASS, INTEGER_CLASS,
    KERNEL_CLASS, MATCH_DATA_CLASS, MATH_CLASS, MODULE_CLASS, MUTEX_CLASS, NIL_CLASS,
    NUMERIC_CLASS, PROC_CLASS, QUEUE_CLASS, RACTOR_CLASS, RANGE_CLASS, RATIONAL_CLASS,
    REGEXP_CLASS, STRING_CLASS, STRUCT_CLASS, SYMBOL_CLASS, THREAD_CLASS, TRUE_CLASS,
    YIELDER_CLASS,
};
/// The builtin `Enumerable` MODULE (Phase 14.4 rev.2) -- consulted by
/// `send`'s Enumerable fallback (an Object whose registered ancestors
/// contain this id dispatches unresolved Enumerable-method names to
/// `crate::enumerable`). Like every id above, re-exported from the shared
/// `spinel-abi` numbering.
pub use spinel_abi::ENUMERABLE_CLASS;

impl RubyObject for Object {
    fn class_id(&self) -> ClassId {
        Self::CLASS_ID
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync> {
        self
    }
    // The root `Object` is never instantiated as a runtime value (no
    // `Object.new` path exists -- `emit_new` only constructs user classes),
    // so it has no `__frozen` field to consult; a fixed unfrozen answer
    // keeps the trait total without pretending at state that can't exist.
    fn is_frozen(&self) -> bool {
        false
    }
    fn set_frozen(&self) {}
    fn ivar_values(&self) -> Vec<RubyValue> {
        Vec::new()
    }
    // Never reachable for the same no-instantiation reason as `is_frozen`
    // above; a fresh stateless `Object` keeps the trait total.
    fn dup_object(&self, _copy_frozen: bool) -> RObj {
        Arc::new(Object)
    }
}

/// Binds a DYNAMIC call's keyword arguments for a keyword-declaring callee
/// (the G2 trailing-kwargs-hash convention): when the last argument is a
/// Hash, it's the keyword set; otherwise there are no keywords. Returns
/// `(positional, required_values, optional_values, rest_pairs)` for the
/// generated trampoline to splice into the direct call -- optional `None`s
/// let the callee's own prologue lazily evaluate defaults, exactly like
/// Path 1.
///
/// Documented approximation (plan G2): no `ruby2_keywords` flagging, so a
/// bare trailing Hash passed positionally through `send` to a
/// keyword-declaring method binds as keywords.
pub fn bind_dynamic_kwargs<'a>(
    method: &str,
    args: &'a [RubyValue],
    required: &[&str],
    optional: &[&str],
    has_kwrest: bool,
) -> Result<
    (
        &'a [RubyValue],
        Vec<RubyValue>,
        Vec<Option<RubyValue>>,
        Vec<(Symbol, RubyValue)>,
    ),
    Signal,
> {
    let (positional, kw_hash) = match args.split_last() {
        Some((RubyValue::Hash(h), rest)) => (rest, Some(h.clone())),
        _ => (args, None),
    };
    let mut req_values = Vec::with_capacity(required.len());
    let mut opt_values = Vec::with_capacity(optional.len());
    let mut rest_pairs = Vec::new();

    let pairs: Vec<(RubyValue, RubyValue)> = match &kw_hash {
        Some(h) => h.lock().values().cloned().collect(),
        None => Vec::new(),
    };
    let mut lookup = |name: &str| -> Option<RubyValue> {
        pairs.iter().find_map(|(k, v)| match k {
            RubyValue::Symbol(s) if s.name() == name => Some(v.clone()),
            _ => None,
        })
    };
    for name in required {
        match lookup(name) {
            Some(v) => req_values.push(v),
            None => {
                return Err(raise_error(
                    "ArgumentError",
                    format!("missing keyword: :{name} (in `{method}')"),
                ))
            }
        }
    }
    for name in optional {
        opt_values.push(lookup(name));
    }
    for (k, v) in &pairs {
        if let RubyValue::Symbol(s) = k {
            let n = s.name();
            if required.contains(&n.as_str()) || optional.contains(&n.as_str()) {
                continue;
            }
            if has_kwrest {
                rest_pairs.push((*s, v.clone()));
                continue;
            }
            return Err(raise_error(
                "ArgumentError",
                format!("unknown keyword: :{n} (in `{method}')"),
            ));
        }
        // A non-Symbol key in the trailing hash: without kwrest it can't
        // bind anywhere -- real Ruby treats the hash as positional then,
        // but this convention already committed it as keywords (the
        // documented no-ruby2_keywords approximation).
        if !has_kwrest {
            return Err(raise_error(
                "ArgumentError",
                format!("wrong number of arguments (in `{method}')"),
            ));
        }
    }
    Ok((positional, req_values, opt_values, rest_pairs))
}

/// The top-level `self` -- CRuby's `main`, a plain `Object` instance.
/// Generated code passes it as the receiver of top-level-defined methods
/// (which live on `Object`, exactly like real Ruby's private-on-Object
/// rule) and as the value of a top-level `self` expression. One shared
/// instance so identity is stable across the program, lazily built since
/// most programs never touch it.
pub fn main_object() -> RubyValue {
    static MAIN: std::sync::OnceLock<RubyValue> = std::sync::OnceLock::new();
    MAIN.get_or_init(|| RubyValue::Object(Arc::new(Object))).clone()
}

/// Downcasts an erased `RObj` to an owned `Arc<T>` -- the Path 2 trampoline
/// counterpart to `as_any().downcast_ref()`, needed because every generated
/// method takes `self: Arc<Self>` now (see `ruby_class!`'s docs). Cloning
/// `recv` first is a cheap `Arc` refcount bump, not a deep copy.
pub fn downcast_robj<T: RubyObject>(recv: &RObj) -> Option<Arc<T>> {
    recv.clone().as_any_rc().downcast::<T>().ok()
}

/// Every generated method/trampoline returns `Result<RubyValue, Signal>`, not
/// a bare `RubyValue` -- see `Signal`'s docs for why this is fixed from the
/// start rather than retrofitted once `break`/`raise`/non-local `return`
/// exist. The third parameter is the call's block, if any (`None` when no
/// block was given) -- see `signal.rs`'s `catch_break` and `codegen::params`'s
/// docs for how a block crosses the Path 2 boundary.
pub type MethodFn = fn(&RObj, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

/// A class's dynamic constructor (Phase 16.1): allocates a fresh instance
/// and runs its `initialize` (if any) -- what makes `x = Widget;
/// x.new(...)` work when the class is only known at runtime as a
/// `RubyValue::Class` value. Generated per class by `ruby_class!`
/// (`__construct`); `None` for modules and builtins.
pub type ConstructorFn = fn(&[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

/// A method defined by REOPENING a builtin class (Phase 16.3, `class String;
/// def blank?; ...`): the receiver is the builtin VALUE itself (`&RubyValue`,
/// not an `RObj` -- builtins have no generated struct to downcast to), which
/// is exactly what the generated free-function bodies take as `__self`.
/// Consulted FIRST by `send_value` (before even the universal `==`/`dup`
/// arms and the curated tables), because a user redefinition must OVERRIDE
/// the builtin behavior -- real Ruby's rule, oracle-verified (`class String;
/// def length; 42; end` wins everywhere). Phase 18 keys per-box overlays off
/// this same table.
pub type ValueMethodFn = fn(&RubyValue, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

struct ClassEntry {
    /// The Ruby-visible, fully-qualified name (`"Store::Item"`) -- what
    /// `Class#name`/`#to_s`/`puts Widget` print, and what `NoMethodError`
    /// messages cite (Phase 16.1, retiring the class-id-in-the-message
    /// approximation).
    name: String,
    is_module: bool,
    /// The full, already-linearized MRO (this class first, then prepends/
    /// includes/superclass in resolution order) -- computed at COMPILE time
    /// by `spinelc::analyze::mro::compute_ancestors` and baked in as a
    /// literal list by `ruby_class!`'s generated `__register`. Method
    /// dispatch itself never needs to walk this (every reachable method is
    /// already MATERIALIZED directly onto this class -- see the plan's Part
    /// 6), but `is_a`/rescue-by-class matching does.
    ancestors: Vec<ClassId>,
    methods: HashMap<Symbol, MethodFn>,
    /// Methods added by reopening a BUILTIN class (Phase 16.3) -- keyed off
    /// the receiver's `class_id()` with no ancestor walk needed (the only
    /// reopenable builtins are leaf value classes; Object/module reopens are
    /// rejected at spinelc compile time). Empty for every user class, whose
    /// methods live in `methods` above. Keyed `(box_id, name)` since Phase
    /// 18: a builtin reopened INSIDE a `Ruby::Box` registers its methods
    /// under that box's id, and dispatch probes `(caller's box, name)` then
    /// `(0, name)` -- the AOT translation of CRuby's `cme->def->box`
    /// stamping, root reopens visible everywhere.
    value_methods: HashMap<(u32, Symbol), ValueMethodFn>,
    /// The names in `methods`/`value_methods` that Ruby considers PRIVATE
    /// (`private def x`, and every top-level `def` -- which is a private
    /// method of Object). Dispatch itself ignores this (an implicit-self
    /// call and `send` both reach privates, and codegen enforces the
    /// explicit-receiver rule statically where it can); it exists so
    /// `respond_to?` can skip them, matching CRuby's "the default ignores
    /// private methods" rule. Kernel's own C-implemented privates
    /// (`puts`/`p`/...) aren't here -- they have no registry entry at all
    /// and are special-cased in `responds_to`.
    private_methods: HashSet<Symbol>,
    constructor: Option<ConstructorFn>,
}

#[derive(Default)]
pub struct ClassRegistry {
    entries: HashMap<u32, ClassEntry>,
}

impl ClassRegistry {
    pub fn new() -> ClassRegistry {
        ClassRegistry::default()
    }

    /// Mirrors declaring a class's place in the hierarchy -- called once per
    /// class from that class's generated `__register` (or directly from
    /// generated `main()` for modules/builtins, which have no struct), with
    /// `ancestors` already fully linearized at spinelc compile time.
    pub fn register(
        &mut self,
        id: ClassId,
        name: &str,
        is_module: bool,
        ancestors: Vec<ClassId>,
        constructor: Option<ConstructorFn>,
    ) {
        self.entries.insert(
            id.0,
            ClassEntry {
                name: name.to_string(),
                is_module,
                ancestors,
                methods: HashMap::new(),
                value_methods: HashMap::new(),
                private_methods: HashSet::new(),
                constructor,
            },
        );
    }

    /// Registers a builtin-reopen method (Phase 16.3) -- called from
    /// generated `main()` right after the builtin's own `register`, one call
    /// per `def` in a `class String ... end` reopen. `box_id` is the box the
    /// reopen was written in (Phase 18: 0 for the root program; a box's
    /// overlay methods register under its id and are visible only from that
    /// box's code). See `ValueMethodFn`'s docs for the precedence contract.
    /// Records `name` as PRIVATE on `id` -- emitted by codegen right after
    /// the method's own registration, for each `def` whose resolved
    /// visibility is private. See `ClassEntry::private_methods`.
    pub fn mark_private(&mut self, id: ClassId, name: Symbol) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before marking its methods private")
            .private_methods
            .insert(name);
    }

    fn is_private(&self, id: ClassId, name: Symbol) -> bool {
        self.entries
            .get(&id.0)
            .is_some_and(|e| e.private_methods.contains(&name))
    }

    pub fn define_value_method(&mut self, id: ClassId, box_id: u32, name: Symbol, f: ValueMethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining value methods on it")
            .value_methods
            .insert((box_id, name), f);
    }

    /// The runtime-mutable path `define_method`/`define_singleton_method`
    /// actually go through: a real `HashMap` insert, no compile-time
    /// literal-name restriction (contrast spinel's `walk_scope`, which can
    /// only register a `define_method` as a scope if the name is a literal).
    pub fn define_method(&mut self, id: ClassId, name: Symbol, f: MethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining methods on it")
            .methods
            .insert(name, f);
    }

    fn lookup(&self, id: ClassId, name: Symbol) -> Option<MethodFn> {
        self.entries.get(&id.0)?.methods.get(&name).copied()
    }

    /// The `(caller's box, name)` probe with the root fallback -- CRuby's
    /// def->box resolution rule: a box's own patch wins inside the box,
    /// root patches are visible everywhere, and nothing else is.
    fn lookup_value_method(&self, id: ClassId, box_id: u32, name: Symbol) -> Option<ValueMethodFn> {
        let entry = self.entries.get(&id.0)?;
        if box_id != 0 {
            if let Some(f) = entry.value_methods.get(&(box_id, name)) {
                return Some(*f);
            }
        }
        entry.value_methods.get(&(0, name)).copied()
    }

    fn ancestors_of(&self, id: ClassId) -> &[ClassId] {
        self.entries.get(&id.0).map_or(&[], |e| &e.ancestors)
    }
}

/// `recv_class.is_a?(target)` -- a real ancestry check against the SAME
/// linearized `ancestors` list `super`/reflection uses at compile time (see
/// `analyze::mro::compute_ancestors`'s docs), not spinel's own two-tier
/// "transplant for dispatch, shallower list for reflection" split (confirmed
/// to diverge on a module-of-module diamond -- see the plan). The one
/// runtime surface this spike needs for `Signal::Raise`/`rescue` matching:
/// there's no first-class `Class`/`Module` runtime VALUE (can't be stored in
/// a variable or reflected on generally), just this narrow "is this concrete
/// class id ancestor-compatible with that one" check.
pub fn is_a(recv_class: ClassId, target: ClassId) -> bool {
    ancestors_of_value(recv_class).contains(&target)
}

/// `recv.respond_to?(:name)` -- MRO-faithful since Phase 17.1: walks the
/// receiver's real ancestor chain probing, per ancestor, the registry
/// (materialized user methods live flat on the OWN class -- the first
/// ancestor -- and builtin reopens hang off whichever ancestor was
/// reopened), the builtin method tables, and the Enumerable/Comparable
/// name sets. Kernel PRIVATE functions (`puts`, ...) are deliberately
/// invisible, real Ruby's rule. Doesn't consult
/// `method_missing`/`respond_to_missing?`, which this spike doesn't model.
/// `respond_to?`'s answer: does `recv_class` (or any ancestor) provide
/// `name`? `include_all` is the method's own second parameter -- false (the
/// default) skips PRIVATE methods, exactly as in CRuby.
pub fn responds_to(recv_class: ClassId, name: Symbol, include_all: bool) -> bool {
    let n = name.name();
    let n = n.as_str();
    for &anc in ancestors_of_value(recv_class) {
        if let Some(r) = REGISTRY.get() {
            if r.lookup(anc, name).is_some() || r.lookup_value_method(anc, 0, name).is_some() {
                if !include_all && r.is_private(anc, name) {
                    // A private method of this ancestor doesn't answer, but
                    // a PUBLIC same-named one further along the chain still
                    // could -- keep walking rather than returning early.
                    continue;
                }
                return true;
            }
        }
        match anc {
            ENUMERABLE_CLASS => {
                if crate::builtins::enumerable::responds(n) {
                    return true;
                }
            }
            COMPARABLE_CLASS => {
                if crate::builtins::comparable::responds(n) {
                    return true;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if table(n).is_some() {
                        // Kernel's print family is PRIVATE in CRuby:
                        // reachable via implicit self and `send` (both go
                        // through the table), but invisible to
                        // `respond_to?` -- its default ignores privates.
                        if !include_all
                            && anc == KERNEL_CLASS
                            && matches!(n, "puts" | "print" | "p" | "pp" | "warn")
                        {
                            continue;
                        }
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// The ancestor chain the MRO walk runs over: the registry's (richer --
/// user classes, and reopens may have `include`d user modules into a
/// builtin) when installed and populated for `id`, else the ABI-derived
/// fallback chain (this crate's own unit tests; identical for builtins by
/// construction -- both derive from `spinel_abi::BUILTINS`).
pub(crate) fn ancestors_of_value(id: ClassId) -> &'static [ClassId] {
    // `REGISTRY` is a `static OnceLock`, so `get()` hands out `&'static`
    // borrows directly -- no lifetime gymnastics needed.
    if let Some(r) = REGISTRY.get() {
        let chain = r.ancestors_of(id);
        if !chain.is_empty() {
            return chain;
        }
    }
    crate::builtins::fallback_ancestors(id)
}

/// The registry's dynamic constructor for `id` (`Class#new`'s row) --
/// `None` for modules, builtins without allocators, or a missing registry.
pub(crate) fn constructor_of(id: ClassId) -> Option<ConstructorFn> {
    REGISTRY.get()?.entries.get(&id.0)?.constructor
}

/// Coerces a dynamic method-name value the way `send`/`__send__` do:
/// Symbol or String (real Ruby accepts both), anything else raising
/// CRuby's exact TypeError shape.
pub fn method_name_symbol(v: &RubyValue) -> Result<Symbol, Signal> {
    match v {
        RubyValue::Symbol(s) => Ok(*s),
        RubyValue::Str(s) => Ok(Symbol::intern(&s.lock())),
        other => Err(raise_error(
            "TypeError",
            format!("{} is not a symbol nor a string", other.inspect_string()),
        )),
    }
}

/// A registry-OPTIONAL probe for a builtin-reopen method (Phase 16.3) --
/// `None` when no registry is installed (this crate's own unit tests) or
/// the class carries no such method. The lookup key is the receiver's own
/// `class_id()`; see `ValueMethodFn`'s docs for why no ancestor walk is
/// needed. Used by `send_value`'s override-first stage and by
/// `display_with`/`inspect_with`'s `to_s`/`inspect` probes in `value.rs`.
pub(crate) fn value_method(id: ClassId, box_id: u32, name: Symbol) -> Option<ValueMethodFn> {
    REGISTRY.get()?.lookup_value_method(id, box_id, name)
}

/// The registered Ruby-visible (fully-qualified) name of `id` -- `None`
/// when the registry isn't installed yet or has no such entry (this
/// crate's own unit tests; a real generated program registers everything
/// before any statement runs). See `RubyValue::Class`'s display arms for
/// the fallback rendering.
pub fn class_name(id: ClassId) -> Option<String> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.name.clone())
}

/// Whether `id` names a MODULE (drives `Widget.class` -> `Class` vs
/// `Enumerable.class` -> `Module`) -- same graceful `None` as `class_name`.
pub fn class_is_module(id: ClassId) -> Option<bool> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.is_module)
}

/// A registry probe-and-call for the runtime PROTOCOL dispatches (Phase
/// 16.2): user `==`/`<=>`/`to_s`/`inspect`/`hash` reached from deep inside
/// pure helpers (`rb_eq`, `display_with`, `hash_key`) that can't route
/// through `send` (whose `method_missing`/NoMethodError fallbacks must NOT
/// fire for a protocol probe). `None` = no such method (or no registry --
/// this crate's own unit tests), letting each caller apply its own
/// default; the method, when present, is the MATERIALIZED entry, so
/// inherited/mixed-in definitions resolve exactly like a real call.
pub(crate) fn call_user_method(
    recv: &RObj,
    name: &str,
    args: &[RubyValue],
) -> Option<Result<RubyValue, Signal>> {
    let f = REGISTRY.get()?.lookup(recv.class_id(), Symbol::intern(name))?;
    Some(f(recv, args, None))
}

/// A registry-optional ancestry probe (Phase 16.2) -- `false` when no
/// registry is installed (this crate's own unit tests), where `is_a`'s
/// hard `registry()` access would panic. Used by `rb_eq`'s Comparable
/// fallback, which must stay callable from anywhere.
pub(crate) fn ancestors_contain(id: ClassId, target: ClassId) -> bool {
    REGISTRY
        .get()
        .is_some_and(|r| r.ancestors_of(id).contains(&target))
}

/// Runs `initialize` on a freshly-constructed instance IF the class
/// defines one -- the shared tail of every `ConstructorFn` (`ruby_class!`'s
/// `__construct`). Deliberately a direct registry lookup, NOT `send`: a
/// class with no `initialize` must not trip the `method_missing` fallback.
/// With no `initialize`, arguments are rejected (real Ruby's
/// `Object#initialize` takes none) -- a loud panic, spike scope (no
/// `ArgumentError`-raising channel from this crate).
pub fn run_initialize(
    class: ClassId,
    recv: &RObj,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<(), Signal> {
    if let Some(f) = registry().lookup(class, Symbol::intern("initialize")) {
        f(recv, args, block)?;
        return Ok(());
    }
    if !args.is_empty() {
        panic!(
            "wrong number of arguments for initialize (given {}, expected 0)",
            args.len()
        );
    }
    Ok(())
}

/// The class registry is installed exactly once, from generated `main()`,
/// before any `Thread`/`Ractor` spawns anything (Part 9) -- a `OnceLock`
/// (not a `thread_local!`, unlike before the Send+Sync migration) gives
/// lock-free reads forever after that single write, and is itself the
/// correct semantic choice regardless of concurrency: classes/methods are
/// genuinely process-wide-shared in real Ruby, not per-thread state.
static REGISTRY: OnceLock<ClassRegistry> = OnceLock::new();

fn registry() -> &'static ClassRegistry {
    REGISTRY
        .get()
        .expect("class registry not installed -- install_class_registry must run first")
}

/// Called once from generated `main()`, after every class's `__register` has
/// populated the registry passed in.
pub fn install_class_registry(registry: ClassRegistry) {
    REGISTRY
        .set(registry)
        .unwrap_or_else(|_| panic!("class registry installed twice"));
}

/// Builds an exception value from a class NAME + message -- installed once
/// from generated `main()` (alongside the registry), because this crate
/// cannot construct exception OBJECTS itself: the exception classes are
/// ordinary generated `ruby_class!` structs living in the generated
/// program's own crate (the same division of labor as `array_set`'s
/// `IndexError` contract). Began life as a `NoMethodError`-only factory
/// (Phase 13.7, replacing a whole-process `exit(1)` over one bad dispatch);
/// generalized in Phase 17.1 so the builtin method tables can raise real,
/// rescuable `ArgumentError`/`TypeError`/`ZeroDivisionError`/... with
/// CRuby's own message shapes instead of panicking.
static EXCEPTION_FACTORY: OnceLock<fn(&str, String) -> RubyValue> = OnceLock::new();

pub fn install_exception_factory(factory: fn(&str, String) -> RubyValue) {
    EXCEPTION_FACTORY
        .set(factory)
        .unwrap_or_else(|_| panic!("exception factory installed twice"));
}

/// THE runtime raise channel: a rescuable `Signal::Raise` carrying a
/// `class_name` exception when the factory is installed (every generated
/// program), a loud panic otherwise (this crate's own unit tests).
pub fn raise_error(class_name: &str, msg: String) -> Signal {
    match EXCEPTION_FACTORY.get() {
        Some(factory) => Signal::Raise(factory(class_name, msg)),
        None => panic!("{class_name}: {msg}"),
    }
}

/// `StopIteration` needs its own factory shape (Phase 17.2): the instance
/// an exhausted `Enumerator#next` raises carries the underlying `each`'s
/// return value as `#result` -- what `Kernel#loop` returns after
/// swallowing it (CRuby kernel.rb:151). The general factory above can't
/// thread that value, so generated `main()` installs this second builder
/// (constructs `StopIteration.new(msg)` then `__set_result`s it).
static STOP_ITERATION_FACTORY: OnceLock<fn(String, RubyValue) -> RubyValue> = OnceLock::new();

pub fn install_stop_iteration_factory(factory: fn(String, RubyValue) -> RubyValue) {
    STOP_ITERATION_FACTORY
        .set(factory)
        .unwrap_or_else(|_| panic!("StopIteration factory installed twice"));
}

/// The exhausted-iteration raise: a rescuable `StopIteration` whose
/// `result` is `result` (a fresh instance per raise -- CRuby rebuilds one
/// from `stop_exc` each time too). Loud panic registry-less (unit tests).
pub fn raise_stop_iteration(result: RubyValue) -> Signal {
    match STOP_ITERATION_FACTORY.get() {
        Some(factory) => {
            Signal::Raise(factory("iteration reached an end".to_string(), result))
        }
        None => panic!("StopIteration: iteration reached an end"),
    }
}


/// The general dispatcher -- reached only on Path 2 (see module docs).
/// Since every reachable method (own, inherited, or mixed-in) is already
/// MATERIALIZED directly onto its receiver's own class at spinelc compile
/// time (see the plan's Part 6 -- no cloning-with-shadow-names,
/// monomorphization instead), this is now a FLAT lookup on the receiver's
/// own class -- no ancestor walk needed here at all, only for `is_a`
/// (above), which real dispatch doesn't need.
///
/// `block` is threaded through to whichever `MethodFn` is actually found --
/// including the `method_missing` fallback, matching real Ruby's own
/// `method_missing(name, *args, &block)` protocol.
/// Dynamic dispatch against ANY `RubyValue` receiver (Phase 14.4, closing
/// the long-standing "Poly-dispatch gap"): an `Object` goes through `send`'s
/// registry exactly as before; a BUILT-IN receiver (Array/Hash/String/...)
/// dispatches against a curated method table over the existing collection
/// helpers -- what makes `@items << x`, `@hash[k] = v`, `ks.length` work on
/// ivars/params/any dynamically-typed value. Codegen's every Poly-receiver
/// fallback (ordinary calls, `send`/`public_send`, safe-nav, and the
/// runtime OPERATOR fallback's non-numeric case) routes here.
///
/// The table is deliberately curated, not exhaustive: entries exist for the
/// operations the static `try_collection_dispatch` fast path also supports
/// (extended as packages need them); anything else raises the same real,
/// rescuable `NoMethodError` an unknown Object method does -- with the
/// builtin class's REAL name in the message (better than `send`'s
/// documented class-id approximation, since builtin names are known here).
pub fn send_value(
    recv: &RubyValue,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    send_value_in(0, recv, name, args, block)
}

/// `send_value` with the CALLER's box (Phase 18) -- the statically-known
/// defining box every codegen dynamic-dispatch site passes, the AOT
/// translation of CRuby's `cme->def->box` (no frame walk). Only the
/// per-ancestor value-method probe consumes it: a box's builtin patches
/// resolve from that box's code, root patches everywhere. This crate's own
/// internal callers (Enumerable driving `each`, Comparable driving `<=>`,
/// ...) go through the box-0 wrapper above -- builtins run in ROOT, which
/// is CRuby's own documented builtins-call-builtins leak, faithfully.
pub fn send_value_in(
    box_id: u32,
    recv: &RubyValue,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    if let RubyValue::Object(o) = recv {
        return send_in(box_id, o, name, args, block);
    }
    let n = name.name();
    let n = n.as_str();
    // `Math.sqrt(...)`-style MODULE FUNCTIONS (Phase 17.1): our model has
    // no singleton-method tables, so the Math module value gets one
    // dedicated probe ahead of the walk (whose chains describe INSTANCE
    // methods -- a Class value's walk runs over Class/Module, not Math).
    if let RubyValue::Class(cid) = recv {
        if *cid == MATH_CLASS {
            if let Some(r) = crate::builtins::math::math_call(n, args) {
                return r;
            }
        }
        // `GC` module functions -- honest no-ops (spinel-rs is
        // Arc-refcounted; no collector exists to drive). `stat` answers an
        // empty-ish Hash so `GC.stat[:count]`-style reads get nil rather
        // than crashing.
        // TODO(plan P-D): replace this probe with the general
        // `class_method_table(ClassId)` mechanism when File/Dir/Time land.
        if *cid == spinel_abi::GC_CLASS {
            match n {
                "start" | "compact" => return Ok(RubyValue::Nil),
                "enable" | "disable" => return Ok(RubyValue::Bool(false)),
                "stress" => return Ok(RubyValue::Bool(false)),
                "count" => return Ok(RubyValue::Int(0)),
                "stat" => {
                    return Ok(RubyValue::Hash(crate::collections::hash_new(Vec::new())))
                }
                _ => {}
            }
        }
    }
    // THE MRO WALK (Phase 17.1) -- the receiver's real ancestor chain, most
    // derived first. Per ancestor: user reopens (Phase 16.3's value
    // methods) beat that ancestor's builtin table -- real Ruby's placement
    // rule (a `class Numeric; def foo` reopen is found on `5`, but a
    // builtin `Integer#foo` row would beat it). `Enumerable`/`Comparable`
    // dispatch through their dedicated drivers (`enumerable_send` drives
    // the receiver's own `each`, `comparable_send` its `<=>`); everything
    // else -- including the Kernel universals and BasicObject's `==` --
    // is an ordinary table hit. The old hand-ordered ladder (reopen probe,
    // universal arms, curated tables, `to_s`-after-tables hack, hardcoded
    // Array|Hash|Range Enumerable set) dissolved into this one loop.
    for &anc in ancestors_of_value(recv.class_id()) {
        if let Some(f) = value_method(anc, box_id, name) {
            return f(recv, args, block);
        }
        match anc {
            ENUMERABLE_CLASS => {
                if let Some(r) =
                    crate::builtins::enumerable::enumerable_send(recv, n, args, block.clone())
                {
                    return r;
                }
            }
            COMPARABLE_CLASS => {
                if let Some(r) = crate::builtins::comparable::comparable_send(recv, n, args) {
                    return r;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if let Some(f) = table(n) {
                        return f(recv, args, block);
                    }
                }
            }
        }
    }
    // A class/module receiver gets real Ruby's own distinct message shape
    // ("for class Widget" / "for module Helper", oracle-verified) rather
    // than the instance form below.
    if let RubyValue::Class(cid) = recv {
        let kind = if class_is_module(*cid).unwrap_or(false) { "module" } else { "class" };
        let msg = format!(
            "undefined method '{name}' for {kind} {}",
            class_name(*cid).unwrap_or_else(|| format!("#<Class:{}>", cid.0))
        );
        return Err(raise_error("NoMethodError", msg));
    }
    // The receiver's Ruby class name comes straight from the ABI table
    // (`class_id()` -> `builtin_name`) -- the hand-maintained variant->name
    // match this replaced was one more list to keep in sync.
    let class_name = spinel_abi::builtin_name(recv.class_id())
        .expect("every non-Object/non-Class RubyValue variant maps to a builtin ClassId");
    Err(raise_error(
        "NoMethodError",
        format!("undefined method '{name}' for an instance of {class_name}"),
    ))
}

pub fn send(
    recv: &RObj,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    send_in(0, recv, name, args, block)
}

/// `send` with the caller's box -- see `send_value_in`'s docs.
pub fn send_in(
    box_id: u32,
    recv: &RObj,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    let id = recv.class_id();
    if let Some(f) = registry().lookup(id, name) {
        return f(recv, args, block);
    }

    // The SAME MRO walk `send_value` runs (Phase 17.1), over a boxed
    // handle: Kernel's universals, BasicObject's `==`, and the
    // Enumerable/Comparable drivers all resolve as real ancestor methods
    // -- which also fixes a fidelity bug: `method_missing` used to fire
    // BEFORE the Enumerable/Comparable fallbacks, but real Ruby finds a
    // real (module) method first, always.
    let boxed = RubyValue::Object(recv.clone());
    let n = name.name();
    let n = n.as_str();
    for &anc in ancestors_of_value(id) {
        if let Some(f) = value_method(anc, box_id, name) {
            return f(&boxed, args, block);
        }
        match anc {
            ENUMERABLE_CLASS => {
                if let Some(r) =
                    crate::builtins::enumerable::enumerable_send(&boxed, n, args, block.clone())
                {
                    return r;
                }
            }
            COMPARABLE_CLASS => {
                if let Some(r) = crate::builtins::comparable::comparable_send(&boxed, n, args) {
                    return r;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if let Some(f) = table(n) {
                        return f(&boxed, args, block);
                    }
                }
            }
        }
    }

    // method_missing fallback, with `name` prepended to args (mirrors
    // CRuby's own protocol) -- AFTER every real method, per real Ruby.
    let mm = Symbol::intern("method_missing");
    if let Some(f) = registry().lookup(id, mm) {
        let mut full_args = Vec::with_capacity(args.len() + 1);
        full_args.push(RubyValue::Symbol(name));
        full_args.extend_from_slice(args);
        return f(recv, &full_args, block);
    }

    // A real, catchable `NoMethodError` (Phase 13.7, replacing the original
    // eprintln-and-`process::exit(1)` shortcut): propagates like any other
    // raised exception -- rescuable at the call site, re-raised at a
    // Thread's `join`/`value` if uncaught there, and printed by the
    // top-level uncaught handler otherwise. Real Ruby's exact message
    // shape, with the registered class NAME (Phase 16.1).
    Err(raise_error(
        "NoMethodError",
        format!(
            "undefined method '{name}' for an instance of {}",
            class_name(id).unwrap_or_else(|| format!("class {}", id.0))
        ),
    ))
}
