//! Object model & dynamic dispatch. See the plan's "Object model & dynamic
//! dispatch" section for the full design rationale: two dispatch paths
//! (static direct/match-on-class_id calls, generated entirely by `spinelc`;
//! and this module's runtime `ClassRegistry`/`send`, reached only when
//! `spinelc` cannot resolve a call statically). Spinel itself never needs
//! this module at all -- it's the one deliberate architectural addition.

use crate::{RubyValue, Signal, Symbol};
use std::any::Any;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, OnceLock};

/// Identifies a Ruby class at runtime. Mirrors spinel's struct-embedded
/// `cls_id` field (`emit_class_struct`, codegen.c:2496). Since Phase 15.1
/// this is the SHARED `spinel-abi` type -- the compiler bakes the same
/// numbering into generated code from the same source of truth, so there is
/// nothing left to keep in sync by hand.
pub use spinel_abi::ClassId;

/// Implemented (via `ruby_class!`) by every generated Ruby class, and by the
/// built-in `Object` root below. `Send + Sync` supertrait bounds (Part 9):
/// satisfied automatically for every generated class once its own fields are
/// `parking_lot::Mutex`-wrapped, needing no manual `unsafe impl` anywhere.
pub trait RubyObject: Any + Send + Sync {
    fn class_id(&self) -> ClassId;

    /// Lets `send`'s dispatcher downcast an erased `RObj` back to its
    /// concrete type. No default body: a default `{ self }` here would be
    /// type-checked generically over an unsized `Self` (rustc checks default
    /// bodies once, not per-impl) and fail to coerce to `&dyn Any`. Each
    /// concrete impl provides the one-line body instead (`ruby_class!`
    /// generates it), where `Self` is always a concrete, sized type.
    fn as_any(&self) -> &dyn Any;

    /// The owned-handle counterpart to `as_any` -- needed because every
    /// generated method now takes `self: Arc<Self>` (not `&self`, see
    /// `ruby_class!`'s docs), so Path 2's dynamic trampolines need an
    /// `Arc<Concrete>`, not a `&Concrete`, to actually call one. `Arc<dyn Any
    /// + Send + Sync>` supports a real consuming `downcast::<T>()`; `Arc<dyn
    /// RubyObject>` doesn't (there's no such inherent method on an arbitrary
    /// trait object), so this is the bridge -- same "no default body"
    /// reasoning as `as_any` above.
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync>;

    /// `.frozen?` state (Phase 13.1) -- backed by the `__frozen: AtomicBool`
    /// field `ruby_class!` generates on every class struct (the per-object
    /// counterpart of `collections::Freezable`'s flag). On the trait (not
    /// just inherent) so `freeze_value`/`is_frozen_value` can reach it
    /// through an erased `RObj` without downcasting. The frozen CHECK before
    /// an ivar write is emitted by codegen (`emit_ivar_write_stmt`'s guard),
    /// which alone can construct the `FrozenError` to raise.
    fn is_frozen(&self) -> bool;

    /// Marks this object frozen -- `.freeze`'s storage half; a repeat call
    /// is a harmless no-op, matching CRuby's own already-frozen guard.
    fn set_frozen(&self);

    /// A snapshot of every ivar's current value (Phase 13.8) -- the runtime
    /// ivar ENUMERATION `Ractor`'s recursive shareability check and
    /// `make_shareable`'s deep-freeze traversal need (reading is enough;
    /// by-name ivar SETTING still doesn't exist, which is why an unfrozen
    /// Object can't be deep-copied across a Ractor boundary -- see
    /// `ractor`'s module docs). Generated by `ruby_class!` from its own
    /// ivar list.
    fn ivar_values(&self) -> Vec<RubyValue>;

    /// Every ivar as an ordered `("@name", value)` pair -- what the default
    /// `Object#inspect` rendering and `instance_variables` reflection need,
    /// with names and values paired in ONE pass (so a name-keyed root
    /// `Object`'s map can't desync the two). Generated by `ruby_class!` in
    /// field-declaration order; the default is empty for the runtime's
    /// hand-written objects, which expose no Ruby-visible ivars.
    fn ivar_pairs(&self) -> Vec<(String, RubyValue)> {
        Vec::new()
    }

    /// Read one ivar BY NAME (without the `@`), for the paths where the
    /// receiver's concrete class isn't statically known and codegen
    /// therefore couldn't emit a direct field access: `instance_exec`'s
    /// rebound self, and the top-level `main` object. `None` means this
    /// class declares no such ivar -- distinct from `Some(Nil)`, which is a
    /// declared-but-unassigned one. Generated by `ruby_class!` from its own
    /// ivar list; the default keeps the trait total for the runtime's
    /// hand-written objects, which have no Ruby-visible ivars.
    ///
    /// TODO(plan P-D): a generated class's ivar set is fixed at compile time
    /// from the `@x` names its own body mentions, so an `instance_exec` block
    /// that INVENTS an ivar the target class never names (`obj.instance_exec
    /// { @brand_new = 1 }`) has no slot to write and is silently dropped by
    /// `ivar_set_named`'s `false`. Needs a per-object overflow map (adds a
    /// field to every generated struct, so it also touches `emit_new`'s
    /// struct literals). Corpus: instance_exec_dynamic_ivar.
    fn ivar_get_named(&self, _name: &str) -> Option<RubyValue> {
        None
    }

    /// Write one ivar BY NAME -- `ivar_get_named`'s counterpart, same
    /// statically-unknown-receiver paths. Answers whether the class actually
    /// has the slot (see that method's TODO for the invented-ivar gap).
    fn ivar_set_named(&self, _name: &str, _v: RubyValue) -> bool {
        false
    }

    /// `Kernel#dup`/`#clone`'s per-class shallow copy (Phase 15.2): a fresh
    /// instance of the same concrete struct with every ivar's CURRENT value
    /// cloned into it (a `RubyValue` clone is a handle clone, so nested
    /// objects are SHARED -- CRuby's own shallow rule). `copy_frozen` is
    /// the one `dup`-vs-`clone` difference: `clone` carries the receiver's
    /// frozen flag over, `dup` starts unfrozen. Generated by `ruby_class!`
    /// from its own ivar list (only the concrete impl knows the fields);
    /// `initialize_copy`/singleton-state carryover are documented
    /// scope-cuts. See `RubyValue::dup_value` for the non-Object kinds.
    fn dup_object(&self, copy_frozen: bool) -> RObj;

    /// The wrapped builtin value of a value-builtin SUBCLASS instance (D3):
    /// `class Stack < Array` stores a `RubyValue::Array` here, so inherited
    /// `Array` methods run against it (the `send_in` payload bridge). `None`
    /// for every ordinary object -- only `ValueSubclass` overrides these three.
    /// Returns a HANDLE clone (cheap `Arc` bump), never holding the internal
    /// lock across the re-entrant dispatch that follows.
    fn builtin_payload(&self) -> Option<RubyValue> {
        None
    }
    /// The root builtin whose methods this subclass inherits (`Array` for
    /// `Stack < Array`) -- the ancestor the payload bridge substitutes at.
    fn builtin_root(&self) -> Option<ClassId> {
        None
    }
    /// Re-seat the whole payload (a `super`/`replace`/`initialize` that rebuilds
    /// the collection). `false` for a non-value-subclass. The single write path.
    fn set_builtin_payload(&self, _v: RubyValue) -> bool {
        false
    }
}

/// A handle to any live Ruby object, used wherever the concrete class isn't
/// statically known. Mirrors spinel's boxed `sp_RbVal { tag: SP_TAG_OBJ,
/// cls_id, v: { p } }` (`lib/sp_gc.h:42`) for the object case -- except the
/// Rust trait object's vtable *is* the tag. Mutability lives on individual
/// ivar fields (see `ruby_class!`), not on this handle, so no lock layer is
/// needed here. `Arc` (not `Rc`, Part 9): every concrete `RubyObject` impl is
/// `Send + Sync` (via the trait's own supertrait bounds above), so this type
/// itself is genuinely `Send + Sync` -- no `unsafe impl` needed.
pub type RObj = Arc<dyn RubyObject>;

/// The root of every class hierarchy. `ClassId(0)`, no superclass -- the
/// base case `ruby_class!`'s `$super` bottoms out at.
///
/// Unlike a generated class, its ivars live in a NAME-KEYED map rather than
/// struct fields: this is the type behind `main_object()`, and the top level's
/// `self` has no compile-time class whose ivar list codegen could have
/// materialized into fields. `@x` at the top level (or inside a block that
/// `instance_exec` later rebinds onto some other receiver) is resolved by
/// name at runtime, so a map is the honest representation.
#[derive(Default)]
pub struct Object {
    ivars: parking_lot::Mutex<std::collections::HashMap<String, RubyValue>>,
}

impl Object {
    pub const CLASS_ID: ClassId = ClassId(0);
}

/// Fixed, well-known `ClassId`s for every built-in Ruby type this spike
/// models as a `RubyValue` variant rather than a generated `ruby_class!`
/// struct -- numerically mirrored by `spinelc::compiler::BUILTIN_CLASSES`
/// (same "two `ClassId` types, on purpose" convention as `Object::CLASS_ID`/
/// `compiler::OBJECT_CLASS`). Registered into the `ClassRegistry` once, from
/// generated `main()` (`codegen::mod`'s `builtin_registrations`), with the
/// SAME linearized `ancestors` every user class gets -- what makes
/// `5.is_a?(Integer)`/`"x".is_a?(Object)`-style checks against a built-in-
/// typed receiver work uniformly through the one general `is_a`/`send`
/// mechanism, and the prerequisite for eventually `include`ing a plain-Ruby
/// `Enumerable`/`Comparable` into these types via ordinary materialization.
pub use spinel_abi::{
    ARRAY_CLASS, BASIC_OBJECT_CLASS, CLASS_CLASS, COMPARABLE_CLASS, COMPLEX_CLASS,
    ENUMERATOR_CLASS, FALSE_CLASS, FIBER_CLASS, FLOAT_CLASS, HASH_CLASS, INTEGER_CLASS,
    KERNEL_CLASS, MATCH_DATA_CLASS, MATH_CLASS, MODULE_CLASS, MUTEX_CLASS, NIL_CLASS,
    NUMERIC_CLASS, PROC_CLASS, QUEUE_CLASS, RACTOR_CLASS, RANGE_CLASS, RATIONAL_CLASS,
    REGEXP_CLASS, STRING_CLASS, STRUCT_CLASS, SYMBOL_CLASS, THREAD_CLASS, TRUE_CLASS,
    YIELDER_CLASS,
};
/// The builtin `Enumerable` MODULE (Phase 14.4 rev.2) -- consulted by
/// `send`'s Enumerable fallback (an Object whose registered ancestors
/// contain this id dispatches unresolved Enumerable-method names to
/// `crate::enumerable`). Like every id above, re-exported from the shared
/// `spinel-abi` numbering.
pub use spinel_abi::ENUMERABLE_CLASS;

impl RubyObject for Object {
    fn class_id(&self) -> ClassId {
        Self::CLASS_ID
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
    fn as_any_rc(self: Arc<Self>) -> Arc<dyn Any + Send + Sync> {
        self
    }
    // `main` is never frozen and there is no `Object.new` path that could
    // freeze one; a fixed unfrozen answer keeps the trait total without
    // pretending at state that can't exist.
    fn is_frozen(&self) -> bool {
        false
    }
    fn set_frozen(&self) {}
    fn ivar_values(&self) -> Vec<RubyValue> {
        self.ivars.lock().values().cloned().collect()
    }
    fn ivar_pairs(&self) -> Vec<(String, RubyValue)> {
        // The root object's keys are stored WITHOUT the `@` (see
        // `ivar_get_named`); paired in a single lock so name/value order can't
        // diverge. Insertion order isn't preserved (a plain `HashMap`) -- a
        // minor divergence limited to the name-keyed main object, which is
        // rarely inspected with ivars.
        self.ivars.lock().iter().map(|(k, v)| (format!("@{k}"), v.clone())).collect()
    }
    fn ivar_get_named(&self, name: &str) -> Option<RubyValue> {
        // A never-assigned ivar reads `nil` rather than raising -- Ruby's
        // rule, and the reason this answers `Some(Nil)` instead of `None`
        // (`None` means "this class has no such slot", which for a
        // name-keyed object is never true).
        Some(self.ivars.lock().get(name).cloned().unwrap_or(RubyValue::Nil))
    }
    fn ivar_set_named(&self, name: &str, v: RubyValue) -> bool {
        self.ivars.lock().insert(name.to_string(), v);
        true
    }
    fn dup_object(&self, _copy_frozen: bool) -> RObj {
        Arc::new(Object {
            ivars: parking_lot::Mutex::new(self.ivars.lock().clone()),
        })
    }
}

/// Binds a DYNAMIC call's keyword arguments for a keyword-declaring callee
/// (the G2 trailing-kwargs-hash convention): when the last argument is a
/// Hash, it's the keyword set; otherwise there are no keywords. Returns
/// `(positional, required_values, optional_values, rest_pairs)` for the
/// generated trampoline to splice into the direct call -- optional `None`s
/// let the callee's own prologue lazily evaluate defaults, exactly like
/// Path 1.
///
/// Documented approximation (plan G2): no `ruby2_keywords` flagging, so a
/// bare trailing Hash passed positionally through `send` to a
/// keyword-declaring method binds as keywords.
pub fn bind_dynamic_kwargs<'a>(
    method: &str,
    args: &'a [RubyValue],
    required: &[&str],
    optional: &[&str],
    has_kwrest: bool,
) -> Result<
    (
        &'a [RubyValue],
        Vec<RubyValue>,
        Vec<Option<RubyValue>>,
        Vec<(Symbol, RubyValue)>,
    ),
    Signal,
> {
    let (positional, kw_hash) = match args.split_last() {
        Some((RubyValue::Hash(h), rest)) => (rest, Some(h.clone())),
        _ => (args, None),
    };
    let mut req_values = Vec::with_capacity(required.len());
    let mut opt_values = Vec::with_capacity(optional.len());
    let mut rest_pairs = Vec::new();

    let pairs: Vec<(RubyValue, RubyValue)> = match &kw_hash {
        Some(h) => h.lock().values().cloned().collect(),
        None => Vec::new(),
    };
    let lookup = |name: &str| -> Option<RubyValue> {
        pairs.iter().find_map(|(k, v)| match k {
            RubyValue::Symbol(s) if s.name() == name => Some(v.clone()),
            _ => None,
        })
    };
    for name in required {
        match lookup(name) {
            Some(v) => req_values.push(v),
            None => {
                return Err(raise_error(
                    "ArgumentError",
                    format!("missing keyword: :{name} (in `{method}')"),
                ))
            }
        }
    }
    for name in optional {
        opt_values.push(lookup(name));
    }
    for (k, v) in &pairs {
        if let RubyValue::Symbol(s) = k {
            let n = s.name();
            if required.contains(&n.as_str()) || optional.contains(&n.as_str()) {
                continue;
            }
            if has_kwrest {
                rest_pairs.push((*s, v.clone()));
                continue;
            }
            return Err(raise_error(
                "ArgumentError",
                format!("unknown keyword: :{n} (in `{method}')"),
            ));
        }
        // A non-Symbol key in the trailing hash: without kwrest it can't
        // bind anywhere -- real Ruby treats the hash as positional then,
        // but this convention already committed it as keywords (the
        // documented no-ruby2_keywords approximation).
        if !has_kwrest {
            return Err(raise_error(
                "ArgumentError",
                format!("wrong number of arguments (in `{method}')"),
            ));
        }
    }
    Ok((positional, req_values, opt_values, rest_pairs))
}

/// The top-level `self` -- CRuby's `main`, a plain `Object` instance.
/// Generated code passes it as the receiver of top-level-defined methods
/// (which live on `Object`, exactly like real Ruby's private-on-Object
/// rule) and as the value of a top-level `self` expression. One shared
/// instance so identity is stable across the program, lazily built since
/// most programs never touch it.
pub fn main_object() -> RubyValue {
    static MAIN: std::sync::OnceLock<RubyValue> = std::sync::OnceLock::new();
    MAIN.get_or_init(|| RubyValue::Object(Arc::new(Object::default())))
        .clone()
}

/// Read `@name` off a receiver whose concrete class isn't statically known
/// -- what codegen emits for an ivar access when `self` is a `RubyValue`
/// rather than an `Arc<Concrete>` (top level, or a block whose self
/// `instance_exec` may rebind). `name` excludes the `@`.
///
/// A non-Object receiver (`5.instance_exec { @x }`) answers nil rather than
/// raising: real Ruby lets you READ an ivar off any object, and immediates
/// simply never have one. An Object whose class declares no such ivar is the
/// same never-assigned case.
pub fn ivar_get_dyn(recv: &RubyValue, name: &str) -> RubyValue {
    match recv {
        RubyValue::Object(o) => o.ivar_get_named(name).unwrap_or(RubyValue::Nil),
        // A CLASS object's own ivars live in their own table (see
        // `civars`' docs for why they can't share `cvars`'). Reached when a
        // class-method body's `self` is dynamic rather than the static class
        // id codegen usually emits -- e.g. `def self.x; [1].each { @n } end`,
        // where the block captures `self` as a plain `RubyValue::Class`.
        RubyValue::Class(cid) => crate::civars::class_ivar_get(cid.0, name),
        _ => RubyValue::Nil,
    }
}

/// Write `@name` on a statically-unknown receiver -- `ivar_get_dyn`'s
/// counterpart, carrying Ruby's frozen check (`rb_check_frozen`) and its
/// can't-modify-frozen raise, which the static field-write path emits
/// inline instead.
pub fn ivar_set_dyn(recv: &RubyValue, name: &str, v: RubyValue) -> Result<RubyValue, Signal> {
    match recv {
        RubyValue::Object(o) => {
            if o.is_frozen() {
                let cls = crate::builtins::class_name_of(recv);
                return Err(raise_error(
                    "FrozenError",
                    format!("can't modify frozen {cls}: {}", recv.inspect_string()),
                ));
            }
            o.ivar_set_named(name, v.clone());
            Ok(v)
        }
        // See `ivar_get_dyn`'s Class arm. No frozen check: a class object is
        // only frozen by an explicit `Foo.freeze`, which this runtime has no
        // storage to record -- the same posture the static class-ivar write
        // path takes.
        RubyValue::Class(cid) => {
            crate::civars::class_ivar_set(cid.0, name, v.clone());
            Ok(v)
        }
        // Real Ruby raises here (immediates are frozen and have no ivar
        // table), and the message names the receiver's class.
        _ => Err(raise_error(
            "FrozenError",
            format!(
                "can't modify frozen {}: {}",
                crate::builtins::class_name_of(recv),
                recv.inspect_string()
            ),
        )),
    }
}

/// Downcasts an erased `RObj` to an owned `Arc<T>` -- the Path 2 trampoline
/// counterpart to `as_any().downcast_ref()`, needed because every generated
/// method takes `self: Arc<Self>` now (see `ruby_class!`'s docs). Cloning
/// `recv` first is a cheap `Arc` refcount bump, not a deep copy.
pub fn downcast_robj<T: RubyObject>(recv: &RObj) -> Option<Arc<T>> {
    recv.clone().as_any_rc().downcast::<T>().ok()
}

/// Every generated method/trampoline returns `Result<RubyValue, Signal>`, not
/// a bare `RubyValue` -- see `Signal`'s docs for why this is fixed from the
/// start rather than retrofitted once `break`/`raise`/non-local `return`
/// exist. The third parameter is the call's block, if any (`None` when no
/// block was given) -- see `signal.rs`'s `catch_break` and `codegen::params`'s
/// docs for how a block crosses the Path 2 boundary.
pub type MethodFn = fn(&RObj, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

/// A registered instance method's implementation. Today every entry is
/// `Static` -- a bare `fn` pointer, exactly as before -- so the hot path is a
/// direct indirect call with one folded discriminant branch, no allocation.
/// The `Dynamic` arm is the seam the eval VM (the dynamic-`eval`/`define_method`
/// phase) fills: an interpreted method body captured as an `Arc<dyn Fn>` that a
/// bare `fn` pointer cannot represent. Nothing constructs `Dynamic` yet; it
/// exists so the registry's method table and every dispatch site already speak
/// the widened shape when that phase lands, with no further dispatch rewrite.
pub enum MethodImpl {
    Static(MethodFn),
    // Nothing constructs this yet -- it's the eval VM's seam (see the type doc).
    // The `#[cfg(test)]` dispatch test does exercise it.
    #[allow(dead_code)]
    Dynamic(Arc<dyn Fn(&RObj, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal> + Send + Sync>),
}

impl MethodImpl {
    #[inline(always)]
    pub fn call(
        &self,
        recv: &RObj,
        args: &[RubyValue],
        block: Option<RubyValue>,
    ) -> Result<RubyValue, Signal> {
        match self {
            MethodImpl::Static(f) => f(recv, args, block),
            MethodImpl::Dynamic(f) => f(recv, args, block),
        }
    }

    #[inline(always)]
    pub fn from_fn(f: MethodFn) -> Self {
        MethodImpl::Static(f)
    }
}

/// A class's dynamic constructor (Phase 16.1): allocates a fresh instance
/// and runs its `initialize` (if any) -- what makes `x = Widget;
/// x.new(...)` work when the class is only known at runtime as a
/// `RubyValue::Class` value. Generated per class by `ruby_class!`
/// (`__construct`, which ignores the id and uses its own `Self::CLASS_ID`);
/// `None` for modules and builtins.
///
/// The leading `ClassId` lets ONE constructor back many classes -- the native
/// exception hierarchy registers every exception class with the same
/// `RubyException`-allocating fn, which reads the id from here instead of a
/// per-class Rust type (see `crate::builtins::exception`).
pub type ConstructorFn = fn(ClassId, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

/// A method defined by REOPENING a builtin class (Phase 16.3, `class String;
/// def blank?; ...`): the receiver is the builtin VALUE itself (`&RubyValue`,
/// not an `RObj` -- builtins have no generated struct to downcast to), which
/// is exactly what the generated free-function bodies take as `__self`.
/// Consulted FIRST by `send_value` (before even the universal `==`/`dup`
/// arms and the curated tables), because a user redefinition must OVERRIDE
/// the builtin behavior -- real Ruby's rule, oracle-verified (`class String;
/// def length; 42; end` wins everywhere). Phase 18 keys per-box overlays off
/// this same table.
pub type ValueMethodFn = fn(&RubyValue, &[RubyValue], Option<RubyValue>) -> Result<RubyValue, Signal>;

struct ClassEntry {
    /// The Ruby-visible, fully-qualified name (`"Store::Item"`) -- what
    /// `Class#name`/`#to_s`/`puts Widget` print, and what `NoMethodError`
    /// messages cite (Phase 16.1, retiring the class-id-in-the-message
    /// approximation).
    name: String,
    is_module: bool,
    /// The full, already-linearized MRO (this class first, then prepends/
    /// includes/superclass in resolution order) -- computed at COMPILE time
    /// by `spinelc::analyze::mro::compute_ancestors` and baked in as a
    /// literal list by `ruby_class!`'s generated `__register`. Method
    /// dispatch itself never needs to walk this (every reachable method is
    /// already MATERIALIZED directly onto this class -- see the plan's Part
    /// 6), but `is_a`/rescue-by-class matching does.
    ancestors: Vec<ClassId>,
    methods: HashMap<Symbol, MethodImpl>,
    /// Methods added by reopening a BUILTIN class (Phase 16.3) -- keyed off
    /// the receiver's `class_id()` with no ancestor walk needed (the only
    /// reopenable builtins are leaf value classes; Object/module reopens are
    /// rejected at spinelc compile time). Empty for every user class, whose
    /// methods live in `methods` above. Keyed `(box_id, name)` since Phase
    /// 18: a builtin reopened INSIDE a `Ruby::Box` registers its methods
    /// under that box's id, and dispatch probes `(caller's box, name)` then
    /// `(0, name)` -- the AOT translation of CRuby's `cme->def->box`
    /// stamping, root reopens visible everywhere.
    value_methods: HashMap<(u32, Symbol), ValueMethodFn>,
    /// The names in `methods`/`value_methods` that Ruby considers PRIVATE
    /// (`private def x`, and every top-level `def` -- which is a private
    /// method of Object). Dispatch itself ignores this (an implicit-self
    /// call and `send` both reach privates, and codegen enforces the
    /// explicit-receiver rule statically where it can); it exists so
    /// `respond_to?` can skip them, matching CRuby's "the default ignores
    /// private methods" rule. Kernel's own C-implemented privates
    /// (`puts`/`p`/...) aren't here -- they have no registry entry at all
    /// and are special-cased in `responds_to`.
    private_methods: HashSet<Symbol>,
    /// Names this class's body `undef`'d. Mirrors CRuby, where `undef`
    /// inserts an "undefined" method entry that TERMINATES the lookup
    /// rather than deleting anything -- so an inherited name stops
    /// resolving here while staying live on the ancestor that defined it.
    ///
    /// Dispatch itself needs no check: `mro::materialize_methods` already
    /// refuses to materialize an undef'd name onto this class, and dispatch
    /// only ever reads this class's own table. `respond_to?` is the one
    /// consumer, because it WALKS the ancestors and would otherwise find
    /// the ancestor's still-live definition.
    undefined_methods: HashSet<Symbol>,
    /// This class's own CLASS methods (`def self.x`, `class << self`,
    /// `extend`) -- reached when a `RubyValue::Class` receiver is sent to
    /// dynamically (`handler.run(...)`, where `handler` holds a class), the
    /// one path where the callee isn't statically known and so can't be a
    /// direct `Foo::__cm_run(...)` call.
    ///
    /// `ValueMethodFn`-shaped like `value_methods`, but with a DROPPED
    /// receiver rather than a passed one (`params::RecvMode`): the emitted
    /// class-method free function takes no receiver parameter.
    ///
    /// No ancestor walk on lookup, for the same reason `methods` needs
    /// none: `analyze::mro::materialize_class_methods` already copies every
    /// inherited class method onto each subclass at compile time, so a hit
    /// here is always this exact class's own entry. That is also what keeps
    /// class-level `@x` storage correct through this path -- each copy
    /// carries its own class id (see `civars`' docs).
    class_methods: HashMap<Symbol, ValueMethodFn>,
    /// The names DEFINED DIRECTLY on this class (not materialized from an
    /// ancestor) -- what `instance_methods(false)` needs, since `methods`
    /// above holds the flattened, fully-materialized set (dispatch's own
    /// requirement -- see `ancestors`' docs). Populated by codegen's
    /// `mark_own` beside `mark_private`. Empty means "unknown/none recorded",
    /// in which case reflection falls back to the materialized set.
    own_methods: HashSet<Symbol>,
    constructor: Option<ConstructorFn>,
}

#[derive(Default)]
pub struct ClassRegistry {
    entries: HashMap<u32, ClassEntry>,
    /// Fully-qualified class NAME -> id, so the runtime can construct an
    /// exception by name (`raise_error("ArgumentError", ...)`) without the
    /// generated program installing a name->constructor factory. Populated by
    /// `register` alongside `entries`. See `construct_exception`.
    by_name: HashMap<String, u32>,
}

impl ClassRegistry {
    pub fn new() -> ClassRegistry {
        ClassRegistry::default()
    }

    /// Mirrors declaring a class's place in the hierarchy -- called once per
    /// class from that class's generated `__register` (or directly from
    /// generated `main()` for modules/builtins, which have no struct), with
    /// `ancestors` already fully linearized at spinelc compile time.
    pub fn register(
        &mut self,
        id: ClassId,
        name: &str,
        is_module: bool,
        ancestors: Vec<ClassId>,
        constructor: Option<ConstructorFn>,
    ) {
        self.by_name.insert(name.to_string(), id.0);
        self.entries.insert(
            id.0,
            ClassEntry {
                name: name.to_string(),
                is_module,
                ancestors,
                methods: HashMap::new(),
                value_methods: HashMap::new(),
                private_methods: HashSet::new(),
                undefined_methods: HashSet::new(),
                class_methods: HashMap::new(),
                own_methods: HashSet::new(),
                constructor,
            },
        );
    }

    /// Build an exception instance from a class NAME + message -- the runtime's
    /// own replacement for the exception factory that generated `main()` used
    /// to install. Every built-in exception class registers its constructor
    /// `ConstructorFn` through `register_exceptions`, so the runtime can
    /// construct the object itself: allocate the struct and run `initialize(msg)`
    /// through the SAME trampoline `SomeError.new(msg)` uses. An unknown name is
    /// a spinel-rt bug (a `raise_error` site naming a class no exception defines),
    /// exactly as the old factory's `panic!` arm caught. `Exception#initialize`
    /// only assigns `@message` and cannot signal, so a `Signal` here is a bug.
    pub fn construct_exception(&self, class_name: &str, msg: String) -> RubyValue {
        let id = self.by_name.get(class_name).copied();
        let ctor = id
            .and_then(|id| self.entries.get(&id))
            .and_then(|entry| entry.constructor);
        match (id, ctor) {
            (Some(id), Some(ctor)) => ctor(
                ClassId(id),
                &[RubyValue::Str(crate::string_new(msg))],
                None,
            )
            .expect("Exception#initialize can't signal"),
            // No such class registered: a `raise_error` site naming a class no
            // exception defines (a spinel-rt bug), or a partial test registry.
            // Panic with the full message -- the same uncatchable fallback the
            // old registry-less `raise_error` used, so the real error still
            // surfaces rather than being masked by an "unknown class" note.
            _ => panic!("{class_name}: {msg}"),
        }
    }

    /// Records `name` as DEFINED DIRECTLY on `id` (not inherited) -- emitted by
    /// codegen for each of the class's own `def`s, beside `mark_private`. See
    /// `ClassEntry::own_methods`.
    pub fn mark_own(&mut self, id: ClassId, name: Symbol) {
        if let Some(e) = self.entries.get_mut(&id.0) {
            e.own_methods.insert(name);
        }
    }

    /// Registers a builtin-reopen method (Phase 16.3) -- called from
    /// generated `main()` right after the builtin's own `register`, one call
    /// per `def` in a `class String ... end` reopen. `box_id` is the box the
    /// reopen was written in (Phase 18: 0 for the root program; a box's
    /// overlay methods register under its id and are visible only from that
    /// box's code). See `ValueMethodFn`'s docs for the precedence contract.
    /// Records `name` as PRIVATE on `id` -- emitted by codegen right after
    /// the method's own registration, for each `def` whose resolved
    /// visibility is private. See `ClassEntry::private_methods`.
    pub fn mark_private(&mut self, id: ClassId, name: Symbol) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before marking its methods private")
            .private_methods
            .insert(name);
    }

    fn is_private(&self, id: ClassId, name: Symbol) -> bool {
        self.entries
            .get(&id.0)
            .is_some_and(|e| e.private_methods.contains(&name))
    }

    pub fn define_value_method(&mut self, id: ClassId, box_id: u32, name: Symbol, f: ValueMethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining value methods on it")
            .value_methods
            .insert((box_id, name), f);
    }

    /// Records an `undef name` -- see `ClassEntry::undefined_methods`.
    pub fn mark_undefined(&mut self, id: ClassId, name: Symbol) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before undefining methods on it")
            .undefined_methods
            .insert(name);
    }

    /// Whether `id`'s own body `undef`'d `name` -- the lookup TERMINATOR
    /// `respond_to?`'s ancestor walk consults.
    fn is_undefined(&self, id: ClassId, name: Symbol) -> bool {
        self.entries
            .get(&id.0)
            .is_some_and(|e| e.undefined_methods.contains(&name))
    }

    /// Registers one `def self.x` for dynamic dispatch -- see
    /// `ClassEntry::class_methods`' docs.
    pub fn define_class_method(&mut self, id: ClassId, name: Symbol, f: ValueMethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining class methods on it")
            .class_methods
            .insert(name, f);
    }

    /// The runtime-mutable path `define_method`/`define_singleton_method`
    /// actually go through: a real `HashMap` insert, no compile-time
    /// literal-name restriction (contrast spinel's `walk_scope`, which can
    /// only register a `define_method` as a scope if the name is a literal).
    pub fn define_method(&mut self, id: ClassId, name: Symbol, f: MethodFn) {
        self.entries
            .get_mut(&id.0)
            .expect("class must be registered before defining methods on it")
            .methods
            .insert(name, MethodImpl::from_fn(f));
    }

    fn lookup(&self, id: ClassId, name: Symbol) -> Option<&MethodImpl> {
        self.entries.get(&id.0)?.methods.get(&name)
    }

    /// This class's registered instance-method names, each tagged private/not,
    /// excluding `undef`'d names -- the registry half of `instance_methods`/
    /// `methods` reflection. `own_only` narrows the user-method set to those
    /// DEFINED DIRECTLY on the class (for `instance_methods(false)`); builtin
    /// reopens (`value_methods`) are always own. When `own_only` is set but the
    /// class recorded no own-set (e.g. a builtin with no reopens), nothing is
    /// dropped only because there is nothing to drop.
    fn own_instance_method_names(&self, id: ClassId, own_only: bool) -> Vec<(Symbol, bool)> {
        let Some(e) = self.entries.get(&id.0) else {
            return Vec::new();
        };
        let mut seen = HashSet::new();
        let mut out = Vec::new();
        let consider = |name: Symbol, seen: &mut HashSet<Symbol>, out: &mut Vec<(Symbol, bool)>| {
            if e.undefined_methods.contains(&name) || !seen.insert(name) {
                return;
            }
            out.push((name, e.private_methods.contains(&name)));
        };
        // `own_methods` is the authoritative "defined directly here" set --
        // and the ONLY reliable source for a MODULE, whose instance methods
        // live on its includers rather than its own `methods` map.
        for &name in &e.own_methods {
            consider(name, &mut seen, &mut out);
        }
        // Builtin-reopen methods are always own to the reopened class.
        for (_, name) in e.value_methods.keys() {
            consider(*name, &mut seen, &mut out);
        }
        if !own_only {
            // The materialized set adds the inherited methods flattened onto a
            // concrete class at compile time.
            for name in e.methods.keys().copied() {
                consider(name, &mut seen, &mut out);
            }
        }
        out
    }

    /// This class's OWN `def self.x` names -- the registry half of
    /// `SomeClass.singleton_methods`/`.methods`.
    fn own_class_method_names(&self, id: ClassId) -> Vec<Symbol> {
        self.entries
            .get(&id.0)
            .map(|e| e.class_methods.keys().copied().collect())
            .unwrap_or_default()
    }

    /// The `(caller's box, name)` probe with the root fallback -- CRuby's
    /// def->box resolution rule: a box's own patch wins inside the box,
    /// root patches are visible everywhere, and nothing else is.
    fn lookup_value_method(&self, id: ClassId, box_id: u32, name: Symbol) -> Option<ValueMethodFn> {
        let entry = self.entries.get(&id.0)?;
        if box_id != 0 {
            if let Some(f) = entry.value_methods.get(&(box_id, name)) {
                return Some(*f);
            }
        }
        entry.value_methods.get(&(0, name)).copied()
    }

    fn ancestors_of(&self, id: ClassId) -> &[ClassId] {
        self.entries.get(&id.0).map_or(&[], |e| &e.ancestors)
    }
}

/// `recv_class.is_a?(target)` -- a real ancestry check against the SAME
/// linearized `ancestors` list `super`/reflection uses at compile time (see
/// `analyze::mro::compute_ancestors`'s docs), not spinel's own two-tier
/// "transplant for dispatch, shallower list for reflection" split (confirmed
/// to diverge on a module-of-module diamond -- see the plan). The one
/// runtime surface this spike needs for `Signal::Raise`/`rescue` matching:
/// there's no first-class `Class`/`Module` runtime VALUE (can't be stored in
/// a variable or reflected on generally), just this narrow "is this concrete
/// class id ancestor-compatible with that one" check.
pub fn is_a(recv_class: ClassId, target: ClassId) -> bool {
    ancestors_of_value(recv_class).contains(&target)
}

/// `Module#<=>`-style ordering of two class/module ids by the ancestry
/// relation (CRuby `rb_class_cmp`): `Less` when `a` is a proper descendant of
/// `b`, `Greater` when a proper ancestor, `Equal` when the same class, and
/// `None` when the two are unrelated (neither appears in the other's
/// linearized ancestors). Backs `Module`'s `<`/`<=`/`>`/`>=`/`<=>` rows.
pub fn module_cmp(a: ClassId, b: ClassId) -> Option<std::cmp::Ordering> {
    use std::cmp::Ordering;
    let a_le_b = is_a(a, b); // b in a's ancestors: a is b-or-below
    let b_le_a = is_a(b, a);
    match (a_le_b, b_le_a) {
        (true, true) => Some(Ordering::Equal),
        (true, false) => Some(Ordering::Less),
        (false, true) => Some(Ordering::Greater),
        (false, false) => None,
    }
}

/// The DIRECT subclasses of `cid` (CRuby `Class#subclasses`): every registered
/// non-module class whose immediate superclass -- the first non-module entry
/// after itself in its linearized ancestry -- is `cid`. Order is unspecified
/// in CRuby, so callers that need determinism sort by name.
pub fn direct_subclasses(cid: ClassId) -> Vec<ClassId> {
    let Some(r) = REGISTRY.get() else {
        return Vec::new();
    };
    r.entries
        .iter()
        .filter(|(_, e)| !e.is_module)
        .filter_map(|(&id, e)| {
            let self_id = ClassId(id);
            if self_id == cid {
                return None;
            }
            let sup = e
                .ancestors
                .iter()
                .skip_while(|&&a| a != self_id)
                .skip(1)
                .find(|&&a| !class_is_module(a).unwrap_or(false))?;
            (*sup == cid).then_some(self_id)
        })
        .collect()
}

/// The bare ivar name (`x`) from a `:@x`/`"@x"` reflection argument. A
/// non-symbol/string is a `TypeError`; a name without the leading `@` is a
/// `NameError` -- both mirroring CRuby's own messages. Shared by the
/// universal `Object#instance_variable_*` helpers below (the class-object
/// table in `builtins::class_module` keeps its own parallel copy).
pub fn ivar_name_arg(v: &RubyValue) -> Result<String, Signal> {
    let raw = match v {
        RubyValue::Symbol(s) => s.name().to_string(),
        RubyValue::Str(s) => s.lock().to_utf8_lossy().into_owned(),
        _ => {
            return Err(raise_error(
                "TypeError",
                format!("{} is not a symbol nor a string", v.inspect_string()),
            ))
        }
    };
    match raw.strip_prefix('@') {
        Some(name) => Ok(name.to_string()),
        None => Err(raise_error(
            "NameError",
            format!("'{raw}' is not allowed as an instance variable name"),
        )),
    }
}

/// `Object#instance_variable_get(:@x)` over ANY receiver: an `Object`'s named
/// ivar, a class object's own ivar (`civars`), or `nil` for a builtin/
/// immediate (which expose no Ruby-visible ivars in this runtime).
pub fn instance_variable_get(recv: &RubyValue, name_arg: &RubyValue) -> Result<RubyValue, Signal> {
    let name = ivar_name_arg(name_arg)?;
    Ok(match recv {
        RubyValue::Object(o) => o.ivar_get_named(&name).unwrap_or(RubyValue::Nil),
        RubyValue::Class(cid) => crate::civars::class_ivar_get(cid.0, &name),
        _ => RubyValue::Nil,
    })
}

/// `Object#instance_variable_set(:@x, v)` -- writes the named ivar (of an
/// object or a class object), answering the value. A no-op on a receiver
/// with no slot for the name.
pub fn instance_variable_set(
    recv: &RubyValue,
    name_arg: &RubyValue,
    v: RubyValue,
) -> Result<RubyValue, Signal> {
    let name = ivar_name_arg(name_arg)?;
    match recv {
        RubyValue::Object(o) => {
            o.ivar_set_named(&name, v.clone());
        }
        RubyValue::Class(cid) => crate::civars::class_ivar_set(cid.0, &name, v.clone()),
        _ => {}
    }
    Ok(v)
}

/// `Object#instance_variables` -- the receiver's ivar names as `:@name`
/// symbols in declaration order (empty for a builtin/immediate).
pub fn instance_variables(recv: &RubyValue) -> RubyValue {
    let names: Vec<RubyValue> = match recv {
        // `ivar_pairs` already yields `@`-prefixed names (it backs the
        // default `Object#inspect`); `class_ivar_names` yields bare ones.
        RubyValue::Object(o) => o
            .ivar_pairs()
            .into_iter()
            .map(|(n, _)| RubyValue::Symbol(Symbol::intern(&n)))
            .collect(),
        RubyValue::Class(cid) => crate::civars::class_ivar_names(cid.0)
            .into_iter()
            .map(|n| RubyValue::Symbol(Symbol::intern(&format!("@{n}"))))
            .collect(),
        _ => Vec::new(),
    };
    RubyValue::Array(crate::array_new(names))
}

/// `recv.respond_to?(:name)` -- MRO-faithful since Phase 17.1: walks the
/// receiver's real ancestor chain probing, per ancestor, the registry
/// (materialized user methods live flat on the OWN class -- the first
/// ancestor -- and builtin reopens hang off whichever ancestor was
/// reopened), the builtin method tables, and the Enumerable/Comparable
/// name sets. Kernel PRIVATE functions (`puts`, ...) are deliberately
/// invisible, real Ruby's rule. Doesn't consult
/// `method_missing`/`respond_to_missing?`, which this spike doesn't model.
/// `respond_to?`'s answer: does `recv_class` (or any ancestor) provide
/// `name`? `include_all` is the method's own second parameter -- false (the
/// default) skips PRIVATE methods, exactly as in CRuby.
pub fn responds_to(recv_class: ClassId, name: Symbol, include_all: bool) -> bool {
    let n = name.name();
    let n = n.as_str();
    for &anc in ancestors_of_value(recv_class) {
        if let Some(r) = REGISTRY.get() {
            // `undef` TERMINATES the walk at the class that wrote it --
            // an ancestor's still-live definition must not answer for a
            // descendant that undef'd the name.
            if r.is_undefined(anc, name) {
                return false;
            }
            if r.lookup(anc, name).is_some() || r.lookup_value_method(anc, 0, name).is_some() {
                if !include_all && r.is_private(anc, name) {
                    // A private method of this ancestor doesn't answer, but
                    // a PUBLIC same-named one further along the chain still
                    // could -- keep walking rather than returning early.
                    continue;
                }
                return true;
            }
        }
        match anc {
            ENUMERABLE_CLASS => {
                if crate::builtins::enumerable::responds(n) {
                    return true;
                }
            }
            COMPARABLE_CLASS => {
                if crate::builtins::comparable::responds(n) {
                    return true;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if table(n).is_some() {
                        // Kernel's print family is PRIVATE in CRuby:
                        // reachable via implicit self and `send` (both go
                        // through the table), but invisible to
                        // `respond_to?` -- its default ignores privates.
                        if !include_all
                            && anc == KERNEL_CLASS
                            && matches!(n, "puts" | "print" | "p" | "pp" | "warn")
                        {
                            continue;
                        }
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// The ancestor chain the MRO walk runs over: the registry's (richer --
/// user classes, and reopens may have `include`d user modules into a
/// builtin) when installed and populated for `id`, else the ABI-derived
/// fallback chain (this crate's own unit tests; identical for builtins by
/// construction -- both derive from `spinel_abi::BUILTINS`).
pub(crate) fn ancestors_of_value(id: ClassId) -> &'static [ClassId] {
    // `REGISTRY` is a `static OnceLock`, so `get()` hands out `&'static`
    // borrows directly -- no lifetime gymnastics needed.
    if let Some(r) = REGISTRY.get() {
        let chain = r.ancestors_of(id);
        if !chain.is_empty() {
            return chain;
        }
    }
    crate::builtins::fallback_ancestors(id)
}

/// Visibility filter for the method-name reflection below. This runtime
/// tracks only private-vs-not (no separate protected set), so `Public` means
/// "public or protected" -- CRuby folds protected into `instance_methods`'s
/// result anyway, and a dedicated `protected_*` query answers empty here.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum MethodVisibility {
    Public,
    Private,
}

/// Kernel's C-implemented private functions -- present in the runtime's
/// `kernel::lookup` table (reachable via implicit self / `send`) but INVISIBLE
/// to reflection and `respond_to?`, exactly as in CRuby. Mirrors the
/// special-case in `responds_to`.
fn is_hidden_kernel_private(name: &str) -> bool {
    matches!(name, "puts" | "print" | "p" | "pp" | "warn")
}

/// The instance-method names of `class` and -- when `inherit` -- its
/// ancestors, as interned Symbols in MRO order, deduped (a nearer class's
/// definition shadows a farther one). Combines the registry (user methods +
/// builtin reopens) with the builtin method tables and the
/// Enumerable/Comparable/Math name sets. `vis` selects public(+protected) or
/// private-only.
///
/// The builtin tables are a SUBSET of CRuby's (this runtime implements a
/// subset of each class's methods), so a builtin class's list won't equal
/// CRuby's exactly -- reflection callers assert membership, not equality. A
/// user class's own list (`inherit=false`) is exact.
pub fn instance_method_names(class: ClassId, vis: MethodVisibility, inherit: bool) -> Vec<Symbol> {
    let chain: Vec<ClassId> =
        if inherit { ancestors_of_value(class).to_vec() } else { vec![class] };
    let reg = REGISTRY.get();
    let mut seen = HashSet::new();
    let mut out = Vec::new();
    for anc in chain {
        if let Some(r) = reg {
            // `inherit=false` restricts the user-method set to this class's own
            // definitions (materialization otherwise flattens inherited in).
            for (name, is_private) in r.own_instance_method_names(anc, !inherit) {
                let want = if vis == MethodVisibility::Private { is_private } else { !is_private };
                if want && seen.insert(name) {
                    out.push(name);
                }
            }
        }
        // Builtin-table methods are all public; skip them for a private query.
        if vis == MethodVisibility::Public {
            for &n in crate::builtins::class_table_names(anc) {
                if anc == KERNEL_CLASS && is_hidden_kernel_private(n) {
                    continue;
                }
                let sym = Symbol::intern(n);
                if seen.insert(sym) {
                    out.push(sym);
                }
            }
        }
    }
    out
}

/// The CLASS-method (`def self.x` + builtin class-method) names of `class`,
/// deduped -- backs `SomeClass.singleton_methods` and the class-method half
/// of `SomeClass.methods`.
pub fn class_method_names(class: ClassId) -> Vec<Symbol> {
    let mut seen = HashSet::new();
    let mut out = Vec::new();
    if let Some(r) = REGISTRY.get() {
        for name in r.own_class_method_names(class) {
            if seen.insert(name) {
                out.push(name);
            }
        }
    }
    for &n in crate::builtins::class_method_table_names(class) {
        let sym = Symbol::intern(n);
        if seen.insert(sym) {
            out.push(sym);
        }
    }
    out
}

/// The registry's dynamic constructor for `id` (`Class#new`'s row) --
/// `None` for modules, builtins without allocators, or a missing registry.
pub(crate) fn constructor_of(id: ClassId) -> Option<ConstructorFn> {
    REGISTRY.get()?.entries.get(&id.0)?.constructor
}

/// Construct an instance of the class with id `id`, running its `initialize`.
/// Codegen calls this at every raise/construct site for a BOOTSTRAP exception
/// class, since those classes no longer have a generated Rust struct to name --
/// the native exceptions registered their `ConstructorFn` (see
/// `crate::builtins::exception`).
/// A missing constructor is a spinelc bug (a bootstrap id with no registrar).
pub fn construct_by_class_id(
    id: ClassId,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    match constructor_of(id) {
        Some(ctor) => ctor(id, args, block),
        None => panic!("no constructor registered for class id {}", id.0),
    }
}

/// The `super` dispatch for an exception-backed receiver (D3): resume the MRO
/// walk in the RECEIVER's own ancestors at the entry AFTER `defining_class`
/// (the class whose body this `super` is lexically written in) and invoke the
/// first `name` registered there -- a native default or a user delta,
/// uniformly. This is the runtime counterpart of codegen's `emit_super_inline`
/// HIR splice, which CANNOT serve a `super` into a native exception method: an
/// exception's message lives in a hidden slot, independent of any `@message`
/// ivar, so the retained `Exception#initialize` HIR (a fictional `@message =
/// msg`) would set a visible ivar and leave the real message untouched. Walking
/// the registry -- where every exception id carries the native `exc_*` fns --
/// runs the true behavior instead. Also the exact shape #97's eval VM needs for
/// `super`, so it lands here rather than as a codegen special case.
pub fn send_super_from(
    recv: &RubyValue,
    defining_class: ClassId,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    let obj = recv.as_object_unchecked();
    let ancestors = ancestors_of_value(obj.class_id());
    // Resume AFTER the class this `super` is written in; an unrecognized
    // `defining_class` (never expected) degrades to a full walk from the top.
    let start = ancestors
        .iter()
        .position(|&a| a == defining_class)
        .map_or(0, |p| p + 1);
    for &anc in &ancestors[start..] {
        if let Some(f) = registry().lookup(anc, name) {
            return f.call(&obj, args, block);
        }
    }
    Err(raise_error(
        "NoMethodError",
        format!("super: no superclass method '{name}'"),
    ))
}

/// Coerces a dynamic method-name value the way `send`/`__send__` do:
/// Symbol or String (real Ruby accepts both), anything else raising
/// CRuby's exact TypeError shape.
pub fn method_name_symbol(v: &RubyValue) -> Result<Symbol, Signal> {
    match v {
        RubyValue::Symbol(s) => Ok(*s),
        RubyValue::Str(s) => Ok(Symbol::intern(&s.lock().to_utf8_lossy())),
        other => Err(raise_error(
            "TypeError",
            format!("{} is not a symbol nor a string", other.inspect_string()),
        )),
    }
}

/// A registry-OPTIONAL probe for a builtin-reopen method (Phase 16.3) --
/// `None` when no registry is installed (this crate's own unit tests) or
/// the class carries no such method. The lookup key is the receiver's own
/// `class_id()`; see `ValueMethodFn`'s docs for why no ancestor walk is
/// needed. Used by `send_value`'s override-first stage and by
/// `display_with`/`inspect_with`'s `to_s`/`inspect` probes in `value.rs`.
pub(crate) fn value_method(id: ClassId, box_id: u32, name: Symbol) -> Option<ValueMethodFn> {
    REGISTRY.get()?.lookup_value_method(id, box_id, name)
}

/// The registered Ruby-visible (fully-qualified) name of `id` -- `None`
/// when the registry isn't installed yet or has no such entry (this
/// crate's own unit tests; a real generated program registers everything
/// before any statement runs). See `RubyValue::Class`'s display arms for
/// the fallback rendering.
pub fn class_name(id: ClassId) -> Option<String> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.name.clone())
}

/// Whether `id` names a MODULE (drives `Widget.class` -> `Class` vs
/// `Enumerable.class` -> `Module`) -- same graceful `None` as `class_name`.
pub fn class_is_module(id: ClassId) -> Option<bool> {
    Some(REGISTRY.get()?.entries.get(&id.0)?.is_module)
}

/// A registry probe-and-call for the runtime PROTOCOL dispatches (Phase
/// 16.2): user `==`/`<=>`/`to_s`/`inspect`/`hash` reached from deep inside
/// pure helpers (`rb_eq`, `display_with`, `hash_key`) that can't route
/// through `send` (whose `method_missing`/NoMethodError fallbacks must NOT
/// fire for a protocol probe). `None` = no such method (or no registry --
/// this crate's own unit tests), letting each caller apply its own
/// default; the method, when present, is the MATERIALIZED entry, so
/// inherited/mixed-in definitions resolve exactly like a real call.
pub(crate) fn call_user_method(
    recv: &RObj,
    name: &str,
    args: &[RubyValue],
) -> Option<Result<RubyValue, Signal>> {
    let id = recv.class_id();
    if let Some(f) = REGISTRY.get().and_then(|r| r.lookup(id, Symbol::intern(name))) {
        return Some(f.call(recv, args, None));
    }
    // A RUNTIME-RESIDENT class (`Time`, `File`, ... -- plan P-B) is an
    // `Object(RObj)` with no registry entry, but it does have a builtin
    // table. Without this probe its own `to_s`/`inspect`/`hash` would be
    // invisible to every caller here -- stringifying a Time would answer
    // `#<Time>` rather than running `Time#to_s`.
    //
    // The receiver's OWN class only, deliberately NOT its ancestors: this is
    // called from `display_with`/`inspect_with`, and `Kernel`'s own `to_s`
    // row renders via `to_display_string` -- walking up to it would recurse
    // until the stack died (it did). The ancestor walk belongs to `send_in`,
    // which has no such reentrancy; what this needs is only "does THIS class
    // define the method itself".
    if let Some(f) = crate::builtins::class_table(id).and_then(|lookup| lookup(name)) {
        return Some(f(&RubyValue::Object(recv.clone()), args, None));
    }
    None
}

/// A registry-optional ancestry probe (Phase 16.2) -- `false` when no
/// registry is installed (this crate's own unit tests), where `is_a`'s
/// hard `registry()` access would panic. Used by `rb_eq`'s Comparable
/// fallback, which must stay callable from anywhere.
pub(crate) fn ancestors_contain(id: ClassId, target: ClassId) -> bool {
    REGISTRY
        .get()
        .is_some_and(|r| r.ancestors_of(id).contains(&target))
}

/// Runs `initialize` on a freshly-constructed instance IF the class
/// defines one -- the shared tail of every `ConstructorFn` (`ruby_class!`'s
/// `__construct`). Deliberately a direct registry lookup, NOT `send`: a
/// class with no `initialize` must not trip the `method_missing` fallback.
/// With no `initialize`, arguments are rejected (real Ruby's
/// `Object#initialize` takes none) -- a loud panic, spike scope (no
/// `ArgumentError`-raising channel from this crate).
pub fn run_initialize(
    class: ClassId,
    recv: &RObj,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<(), Signal> {
    if let Some(f) = registry().lookup(class, Symbol::intern("initialize")) {
        f.call(recv, args, block)?;
        return Ok(());
    }
    // No user `initialize` at all, so the inherited `Object#initialize`
    // takes no arguments. A RAISE, not a panic (plan G1): real Ruby resolves
    // arity at runtime and the error is rescuable -- `rescue ArgumentError`
    // around a bad `.new` is a corpus idiom, and a panic is uncatchable.
    // Message shape oracle-verified: CRuby says "wrong number of arguments
    // (given 2, expected 0)" with no method name in it.
    if !args.is_empty() {
        return Err(raise_error(
            "ArgumentError",
            format!(
                "wrong number of arguments (given {}, expected 0)",
                args.len()
            ),
        ));
    }
    Ok(())
}

/// The class registry is installed exactly once, from generated `main()`,
/// before any `Thread`/`Ractor` spawns anything (Part 9) -- a `OnceLock`
/// (not a `thread_local!`, unlike before the Send+Sync migration) gives
/// lock-free reads forever after that single write, and is itself the
/// correct semantic choice regardless of concurrency: classes/methods are
/// genuinely process-wide-shared in real Ruby, not per-thread state.
static REGISTRY: OnceLock<ClassRegistry> = OnceLock::new();

fn registry() -> &'static ClassRegistry {
    REGISTRY
        .get()
        .expect("class registry not installed -- install_class_registry must run first")
}

/// Whether an instance method `name` is registered directly on class `id` (its
/// flat, materialized `methods` table) -- the value-subclass constructor uses
/// this to decide whether to run a user `initialize` or seed the payload from
/// the args directly.
pub fn has_instance_method(id: ClassId, name: Symbol) -> bool {
    registry().lookup(id, name).is_some()
}

/// Called once from generated `main()`, after every class's `__register` has
/// populated the registry passed in.
pub fn install_class_registry(registry: ClassRegistry) {
    REGISTRY
        .set(registry)
        .unwrap_or_else(|_| panic!("class registry installed twice"));
}

/// THE runtime raise channel: a rescuable `Signal::Raise` carrying a
/// `class_name` exception once the registry is installed (every generated
/// program), a loud panic otherwise (this crate's own unit tests, which run
/// registry-less). The registry constructs the object itself via the class's
/// registered `ConstructorFn` -- see `ClassRegistry::construct_exception` for
/// why the runtime no longer needs a factory installed from generated `main()`.
pub fn raise_error(class_name: &str, msg: String) -> Signal {
    match REGISTRY.get() {
        Some(reg) => Signal::Raise(reg.construct_exception(class_name, msg)),
        None => panic!("{class_name}: {msg}"),
    }
}

/// Coerce a `raise <value>` operand to the exception value to raise:
/// an Exception object raises itself, a String becomes a `RuntimeError` with
/// that message, and anything else is CRuby's `TypeError: exception
/// class/object expected` -- instead of panicking when the raise machinery
/// later unwraps a non-Object. `Exception`'s id is fixed (`spinel-abi`), so it
/// no longer needs baking in by codegen.
pub fn coerce_raise_arg(value: RubyValue) -> RubyValue {
    let build = |class_name: &str, msg: String| match REGISTRY.get() {
        Some(reg) => reg.construct_exception(class_name, msg),
        None => panic!("{class_name}: {msg}"),
    };
    match &value {
        RubyValue::Object(o) if is_a(o.class_id(), spinel_abi::EXCEPTION_CLASS) => value,
        RubyValue::Str(s) => build("RuntimeError", s.lock().to_utf8_lossy().into_owned()),
        _ => build("TypeError", "exception class/object expected".to_string()),
    }
}

/// The exhausted-iteration raise (Phase 17.2): a rescuable `StopIteration`
/// whose `result` is `result` (a fresh instance per raise -- CRuby rebuilds
/// one from `stop_exc` each time too). Constructs `StopIteration.new(msg)` via
/// the registry, then stamps the result through the exception class's own
/// `__set_result` -- the logic generated `main()` used to install as a second
/// factory, now that the runtime constructs exceptions itself. Loud panic
/// registry-less (unit tests).
pub fn raise_stop_iteration(result: RubyValue) -> Signal {
    match REGISTRY.get() {
        Some(reg) => {
            let exc = reg.construct_exception(
                "StopIteration",
                "iteration reached an end".to_string(),
            );
            send(
                &exc.as_object_unchecked(),
                Symbol::intern("__set_result"),
                std::slice::from_ref(&result),
                None,
            )
            .expect("StopIteration#__set_result can't signal");
            Signal::Raise(exc)
        }
        None => panic!("StopIteration: iteration reached an end"),
    }
}


/// The general dispatcher -- reached only on Path 2 (see module docs).
/// Since every reachable method (own, inherited, or mixed-in) is already
/// MATERIALIZED directly onto its receiver's own class at spinelc compile
/// time (see the plan's Part 6 -- no cloning-with-shadow-names,
/// monomorphization instead), this is now a FLAT lookup on the receiver's
/// own class -- no ancestor walk needed here at all, only for `is_a`
/// (above), which real dispatch doesn't need.
///
/// `block` is threaded through to whichever `MethodFn` is actually found --
/// including the `method_missing` fallback, matching real Ruby's own
/// `method_missing(name, *args, &block)` protocol.
/// Dynamic dispatch against ANY `RubyValue` receiver (Phase 14.4, closing
/// the long-standing "Poly-dispatch gap"): an `Object` goes through `send`'s
/// registry exactly as before; a BUILT-IN receiver (Array/Hash/String/...)
/// dispatches against a curated method table over the existing collection
/// helpers -- what makes `@items << x`, `@hash[k] = v`, `ks.length` work on
/// ivars/params/any dynamically-typed value. Codegen's every Poly-receiver
/// fallback (ordinary calls, `send`/`public_send`, safe-nav, and the
/// runtime OPERATOR fallback's non-numeric case) routes here.
///
/// The table is deliberately curated, not exhaustive: entries exist for the
/// operations the static `try_collection_dispatch` fast path also supports
/// (extended as packages need them); anything else raises the same real,
/// rescuable `NoMethodError` an unknown Object method does -- with the
/// builtin class's REAL name in the message (better than `send`'s
/// documented class-id approximation, since builtin names are known here).
pub fn send_value(
    recv: &RubyValue,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    send_value_in(0, recv, name, args, block)
}

/// `send_value` with the CALLER's box (Phase 18) -- the statically-known
/// defining box every codegen dynamic-dispatch site passes, the AOT
/// translation of CRuby's `cme->def->box` (no frame walk). Only the
/// per-ancestor value-method probe consumes it: a box's builtin patches
/// resolve from that box's code, root patches everywhere. This crate's own
/// internal callers (Enumerable driving `each`, Comparable driving `<=>`,
/// ...) go through the box-0 wrapper above -- builtins run in ROOT, which
/// is CRuby's own documented builtins-call-builtins leak, faithfully.
pub fn send_value_in(
    box_id: u32,
    recv: &RubyValue,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    if let RubyValue::Object(o) = recv {
        return send_in(box_id, o, name, args, block);
    }
    let n = name.name();
    let n = n.as_str();
    // CLASS/MODULE-level methods (`File.read`, `Time.now`, `Math.sqrt`):
    // this runtime has no singleton-method tables, so a class value gets its
    // own table probed ahead of the walk. The walk itself describes INSTANCE
    // methods, and a `RubyValue::Class`'s own chain runs over Class/Module --
    // it would never reach File's or Math's rows.
    if let RubyValue::Class(cid) = recv {
        // A USER `def self.x` first -- ahead of the builtin table below, so
        // a class defining its own `self.name`/`self.new` overrides
        // `Class#name`/`Class#new` rather than being shadowed by them. Real
        // Ruby's placement rule: the singleton method is strictly closer
        // than the one inherited from Class/Module.
        if let Some(f) = REGISTRY
            .get()
            .and_then(|r| r.entries.get(&cid.0))
            .and_then(|e| e.class_methods.get(&name).copied())
        {
            return f(recv, args, block);
        }
        if let Some(lookup) = crate::builtins::class_method_table(*cid) {
            if let Some(f) = lookup(n) {
                return f(recv, args, block);
            }
        }
        // Math predates the table shape (it answers `Option<Result<..>>` from
        // one `math_call` fn rather than per-name rows), so it keeps its own
        // probe rather than being reshaped for no behavior change.
        if *cid == MATH_CLASS {
            if let Some(r) = crate::builtins::math::math_call(n, args) {
                return r;
            }
        }
    }
    // THE MRO WALK (Phase 17.1) -- the receiver's real ancestor chain, most
    // derived first. Per ancestor: user reopens (Phase 16.3's value
    // methods) beat that ancestor's builtin table -- real Ruby's placement
    // rule (a `class Numeric; def foo` reopen is found on `5`, but a
    // builtin `Integer#foo` row would beat it). `Enumerable`/`Comparable`
    // dispatch through their dedicated drivers (`enumerable_send` drives
    // the receiver's own `each`, `comparable_send` its `<=>`); everything
    // else -- including the Kernel universals and BasicObject's `==` --
    // is an ordinary table hit. The old hand-ordered ladder (reopen probe,
    // universal arms, curated tables, `to_s`-after-tables hack, hardcoded
    // Array|Hash|Range Enumerable set) dissolved into this one loop.
    for &anc in ancestors_of_value(recv.class_id()) {
        if let Some(f) = value_method(anc, box_id, name) {
            return f(recv, args, block);
        }
        match anc {
            ENUMERABLE_CLASS => {
                if let Some(r) =
                    crate::builtins::enumerable::enumerable_send(recv, n, args, block.clone())
                {
                    return r;
                }
            }
            COMPARABLE_CLASS => {
                if let Some(r) = crate::builtins::comparable::comparable_send(recv, n, args) {
                    return r;
                }
            }
            // `Math`'s module functions become private instance methods when
            // `Math` is mixed in (`include Math` -> `sqrt(x)`), reached here as
            // an ancestor of the receiver. Same `math_call` probe the class-
            // value dispatch uses, since Math predates the per-name table.
            MATH_CLASS => {
                if let Some(r) = crate::builtins::math::math_call(n, args) {
                    return r;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if let Some(f) = table(n) {
                        return f(recv, args, block);
                    }
                }
            }
        }
    }
    // A class/module receiver gets real Ruby's own distinct message shape
    // ("for class Widget" / "for module Helper", oracle-verified) rather
    // than the instance form below.
    if let RubyValue::Class(cid) = recv {
        let kind = if class_is_module(*cid).unwrap_or(false) { "module" } else { "class" };
        let msg = format!(
            "undefined method '{name}' for {kind} {}",
            class_name(*cid).unwrap_or_else(|| format!("#<Class:{}>", cid.0))
        );
        return Err(raise_error("NoMethodError", msg));
    }
    // The receiver's Ruby class name comes straight from the ABI table
    // (`class_id()` -> `builtin_name`) -- the hand-maintained variant->name
    // match this replaced was one more list to keep in sync.
    let class_name = spinel_abi::builtin_name(recv.class_id())
        .expect("every non-Object/non-Class RubyValue variant maps to a builtin ClassId");
    Err(raise_error(
        "NoMethodError",
        format!("undefined method '{name}' for an instance of {class_name}"),
    ))
}

pub fn send(
    recv: &RObj,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    send_in(0, recv, name, args, block)
}

/// `send` with the caller's box -- see `send_value_in`'s docs.
pub fn send_in(
    box_id: u32,
    recv: &RObj,
    name: Symbol,
    args: &[RubyValue],
    block: Option<RubyValue>,
) -> Result<RubyValue, Signal> {
    let id = recv.class_id();
    if let Some(f) = registry().lookup(id, name) {
        return f.call(recv, args, block);
    }

    let boxed = RubyValue::Object(recv.clone());
    // ENV's methods are probed by IDENTITY, not by class: `ENV.class` is
    // `Object` (real Ruby -- it is a lone singleton with Hash-shaped
    // methods, not a Hash), so a class-keyed table would hand `[]`/`fetch`/
    // `keys` to every plain Object in the program. Ahead of the walk for the
    // same reason `Math` is: these are ENV's own methods, and the walk only
    // describes what `Object`'s ancestors offer.
    if crate::builtins::env::is_env(&boxed) {
        if let Some(f) = crate::builtins::env::lookup(name.name().as_str()) {
            return f(&boxed, args, block);
        }
    }

    // The SAME MRO walk `send_value` runs (Phase 17.1), over a boxed
    // handle: Kernel's universals, BasicObject's `==`, and the
    // Enumerable/Comparable drivers all resolve as real ancestor methods
    // -- which also fixes a fidelity bug: `method_missing` used to fire
    // BEFORE the Enumerable/Comparable fallbacks, but real Ruby finds a
    // real (module) method first, always.
    let n = name.name();
    let n = n.as_str();
    // Value-subclass payload bridge (D3): `class Stack < Array` carries a
    // `RubyValue::Array` payload; at its payload root the inherited builtin
    // method runs against that value, not the boxed object. `None` for every
    // ordinary object, so this costs one field read on the miss path.
    let payload = recv.builtin_payload();
    let payload_root = recv.builtin_root();
    for &anc in ancestors_of_value(id) {
        if let Some(f) = value_method(anc, box_id, name) {
            return f(&boxed, args, block);
        }
        match anc {
            ENUMERABLE_CLASS => {
                if let Some(r) =
                    crate::builtins::enumerable::enumerable_send(&boxed, n, args, block.clone())
                {
                    return r;
                }
            }
            COMPARABLE_CLASS => {
                if let Some(r) = crate::builtins::comparable::comparable_send(&boxed, n, args) {
                    return r;
                }
            }
            // `include Math` -> its module functions as private instance
            // methods (see the same arm in `send_value_in`).
            MATH_CLASS => {
                if let Some(r) = crate::builtins::math::math_call(n, args) {
                    return r;
                }
            }
            _ => {
                if let Some(table) = crate::builtins::class_table(anc) {
                    if let Some(f) = table(n) {
                        // At the payload root, run against the wrapped value and
                        // re-wrap a self-return (`push`/`<<`) back to the subclass.
                        if payload_root == Some(anc) {
                            if let Some(ref p) = payload {
                                let result = f(p, args, block)?;
                                return Ok(
                                    crate::builtins::value_subclass::rewrap_self_return(
                                        result, p, recv,
                                    ),
                                );
                            }
                        }
                        return f(&boxed, args, block);
                    }
                }
            }
        }
    }

    // method_missing fallback, with `name` prepended to args (mirrors
    // CRuby's own protocol) -- AFTER every real method, per real Ruby.
    let mm = Symbol::intern("method_missing");
    if let Some(f) = registry().lookup(id, mm) {
        let mut full_args = Vec::with_capacity(args.len() + 1);
        full_args.push(RubyValue::Symbol(name));
        full_args.extend_from_slice(args);
        return f.call(recv, &full_args, block);
    }

    // A real, catchable `NoMethodError` (Phase 13.7, replacing the original
    // eprintln-and-`process::exit(1)` shortcut): propagates like any other
    // raised exception -- rescuable at the call site, re-raised at a
    // Thread's `join`/`value` if uncaught there, and printed by the
    // top-level uncaught handler otherwise. Real Ruby's exact message
    // shape, with the registered class NAME (Phase 16.1).
    Err(raise_error(
        "NoMethodError",
        format!(
            "undefined method '{name}' for an instance of {}",
            class_name(id).unwrap_or_else(|| format!("class {}", id.0))
        ),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both `MethodImpl` arms invoke through `call` with the same ABI -- the
    /// widening the eval VM depends on, verified without any registry.
    #[test]
    fn method_impl_static_and_dynamic_dispatch_through_call() {
        let recv: RObj = Arc::new(Object::default());

        fn stat(_: &RObj, _: &[RubyValue], _: Option<RubyValue>) -> Result<RubyValue, Signal> {
            Ok(RubyValue::Int(1))
        }
        let s = MethodImpl::from_fn(stat);
        assert!(matches!(s.call(&recv, &[], None), Ok(RubyValue::Int(1))));

        let d = MethodImpl::Dynamic(Arc::new(|_: &RObj, _: &[RubyValue], _: Option<RubyValue>| {
            Ok(RubyValue::Int(2))
        }));
        assert!(matches!(d.call(&recv, &[], None), Ok(RubyValue::Int(2))));
    }
}
