//! The compiler's projection of the builtin METHOD/CONSTANT surface.
//!
//! `zeo_abi::BUILTINS` gives the compiler a builtin class's IDENTITY and SHAPE
//! (name, superclass, includes) but NOT its members -- those live in `zeo-rt`,
//! never linked into the compiler. `CLASS_SURFACE` fills that gap for classes
//! migrated to `ruby_class!`/`ruby_module!`: the method and constant NAMES the
//! compiler folds `respond_to?`/`method_defined?`/const lookups against.
//!
//! The table is generated by this crate's build.rs, which re-parses the
//! runtime's macro headers with the shared `zeo-dsl` grammar -- so this
//! view can't drift from what the runtime actually registers. See build.rs.

use zeo_abi::ClassId;

/// One builtin class's folding surface. Absence of a class here just means it
/// hasn't been migrated to the macro yet -- the compiler falls back to its
/// prior (surface-blind) behavior, and dynamic dispatch is always the runtime
/// backstop, so a missing entry is never a correctness problem, only a missed
/// fold.
pub struct ClassSurface {
    pub id: ClassId,
    pub instance_methods: &'static [&'static str],
    pub class_methods: &'static [&'static str],
    pub constants: &'static [&'static str],
}

// Defines `pub const CLASS_SURFACE: &[ClassSurface]`, written symbolically
// (`id: zeo_abi::COMPARABLE_CLASS`) so the build script never evaluates a const.
include!(concat!(env!("OUT_DIR"), "/class_surface.rs"));

/// The projected surface for `id`, if that class has been migrated to the macro.
pub fn surface_for(id: ClassId) -> Option<&'static ClassSurface> {
    CLASS_SURFACE.iter().find(|s| s.id == id)
}

/// Whether the migrated builtin `id` provides a CLASS method named `name`
/// directly (not via inheritance). The compiler's replacement for the
/// hand-written `target_provides_class_method` allowlist.
pub fn provides_class_method(id: ClassId, name: &str) -> bool {
    surface_for(id).is_some_and(|s| s.class_methods.contains(&name))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// End-to-end proof the build.rs parsed `comparable.rs`'s `ruby_module!`
    /// header and projected its surface -- Comparable is a pure mixin (instance
    /// methods only, no class methods or constants).
    #[test]
    fn comparable_surface_is_projected_from_the_runtime_header() {
        let s = surface_for(zeo_abi::COMPARABLE_CLASS)
            .expect("Comparable is migrated, so it must appear in CLASS_SURFACE");
        assert!(s.instance_methods.contains(&"between?"));
        assert!(s.instance_methods.contains(&"clamp"));
        assert!(s.instance_methods.contains(&"<"));
        assert!(s.class_methods.is_empty());
        assert!(s.constants.is_empty());
    }
}
