[tools]
ruby = "4.0.5"
rust = "1.97.1"

[tasks.build]
description = "Build the CLI"
run = "cargo build"

[tasks.zeo]
description = "Run zeo cli"
run = "cargo run"

[tasks.conformance]
description = "Run conformance checks"
env = { "SPINEL_TEST_DIR" = "/Users/ryanseys/dev/spinel/test" }
run = "cargo run -p xtask conformance run --update-scoreboard"
