//! Derives `RUBY_PLATFORM` from the *build target* and exposes it as the
//! `ZEO_RUBY_PLATFORM` compile-time env, mirroring how CRuby's `configure`
//! bakes `RUBY_PLATFORM` (e.g. `arm64-darwin25`, `x86_64-linux`) from the host
//! at build time rather than probing at runtime. `bootstrap.rs` reads it via
//! `env!` to seed the `RUBY_PLATFORM`/`RUBY_DESCRIPTION` constants.
//!
//! Also declares the extension modules, from the `ext/` tree itself -- see
//! [`declare_exts`].

use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rustc-env=ZEO_RUBY_PLATFORM={}", ruby_platform());
    println!("cargo:rerun-if-changed=build.rs");
    build_cext();
    declare_exts();
}

/// Write `$OUT_DIR/ext_mods.rs`: one `mod` item per extension whose Rust this
/// build compiles, which `src/ext.rs` includes.
///
/// The list comes from the directory tree, so adding an extension is adding
/// its directory -- there is no list here to forget. An entry needs
/// `ext/<name>/src/lib.rs`, which is where a Rust-backed gem puts its Rust;
/// a directory with only a `lib/` (`fiddle`) is pure Ruby and declares no
/// module.
///
/// Cargo hands a build script the resolved feature set, so an extension the
/// build turned off is simply absent rather than emitted behind a `#[cfg]`.
/// Paths are absolute because `#[path]` inside an `include!` resolves against
/// the included file, not the including one.
fn declare_exts() {
    let root = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let ext = Path::new(&root).join("ext");
    println!("cargo:rerun-if-changed=ext");
    let mut names: Vec<String> = std::fs::read_dir(&ext)
        .unwrap_or_else(|e| panic!("reading {}: {e}", ext.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| ext.join(n).join("ext").join(n).join("src/lib.rs").is_file())
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "no extension has a Rust half under {} -- every `require` of one \
         would fail at run time",
        ext.display()
    );

    let mut code = String::from("// @generated by build.rs from the ext/ tree.\n");
    for name in &names {
        let feature = format!("CARGO_FEATURE_EXT_{}", name.to_uppercase());
        if std::env::var_os(&feature).is_none() {
            continue;
        }
        let lib = ext.join(name).join("ext").join(name).join("src/lib.rs");
        println!("cargo:rerun-if-changed=ext/{name}/ext/{name}/src");
        code.push_str(&format!(
            "#[path = {:?}]\npub(crate) mod {name};\n",
            lib.display().to_string()
        ));
    }
    let out = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out).join("ext_mods.rs");
    if std::fs::read_to_string(&dest).is_ok_and(|old| old == code) {
        return;
    }
    std::fs::write(&dest, code).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// The pieces of the C extension surface that have to BE C.
///
/// `cext_jmp.c` holds the only `setjmp`: a `longjmp` past a live Rust frame
/// skips its destructors, which is undefined rather than merely leaky.
/// `cext_va.c`, `cext_fmt.c` and `cext_err.c` hold every variadic entry: Rust
/// cannot read a `va_list`, and guessing is how a pointer gets read out of the
/// wrong register. `cext_err.c` also owns `errno`, which is a macro over a
/// per-thread location Rust cannot name. `cext_native_thread.c` takes pointers
/// to a real `pthread_mutex_t` and `pthread_cond_t`, which is a layout only C
/// knows.
fn build_cext() {
    for f in CEXT_SOURCES {
        println!("cargo:rerun-if-changed=csrc/{f}");
    }
    if std::env::var_os("CARGO_FEATURE_CEXT").is_none() {
        return;
    }
    let mut build = cc::Build::new();
    for f in CEXT_SOURCES {
        build.file(format!("csrc/{f}"));
    }
    // `cext_io.c` reads `struct rb_io` out of the shipped headers, which is
    // the whole point of writing it in C.
    build.include("cext/include").include("cext/config");
    build.warnings(true).compile("zeo_cext");
}

const CEXT_SOURCES: &[&str] = &[
    "cext_jmp.c",
    "cext_va.c",
    "cext_fmt.c",
    "cext_err.c",
    "cext_io.c",
    "cext_native_thread.c",
];

/// `<cpu>-<os>` in Ruby's spelling (its `RUBY_PLATFORM` convention), from the
/// Cargo target the crate is being built for.
fn ruby_platform() -> String {
    format!("{}-{}", ruby_arch(), ruby_os())
}

/// Ruby names a few CPUs differently from Rust's `target_arch` (notably
/// `aarch64` -> `arm64`); everything else passes through unchanged.
fn ruby_arch() -> String {
    match cfg_var("CARGO_CFG_TARGET_ARCH").as_str() {
        "aarch64" => "arm64".to_string(),
        "x86" => "i686".to_string(),
        other => other.to_string(),
    }
}

/// Ruby's OS token: `darwin<major>` (the Darwin kernel major, as `configure`
/// records it) on Apple targets; `linux`/`linux-musl` on Linux; the raw
/// `target_os` elsewhere.
fn ruby_os() -> String {
    match cfg_var("CARGO_CFG_TARGET_OS").as_str() {
        "macos" | "ios" | "tvos" | "watchos" => format!("darwin{}", darwin_major()),
        "linux" => match cfg_var("CARGO_CFG_TARGET_ENV").as_str() {
            "musl" => "linux-musl".to_string(),
            _ => "linux".to_string(),
        },
        other => other.to_string(),
    }
}

/// The Darwin kernel major version (`uname -r` -> `25.5.0` -> `25`), matching
/// what CRuby's `configure` embeds -- taken from the build host only when the
/// host IS a mac (native build). Cross-compiling to an Apple target from
/// elsewhere pins a contemporary default: the host kernel is meaningless for
/// the target, and the value is cosmetic (`RUBY_PLATFORM`'s suffix). Kept in
/// sync with the copy in `crates/zeo/build.rs` (`render_rbconfig`).
fn darwin_major() -> String {
    if std::env::consts::OS == "macos"
        && let Some(major) = Command::new("uname")
            .arg("-r")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .and_then(|r| r.trim().split('.').next().map(str::to_string))
    {
        return major;
    }
    // ruby 4.0.6 era: Darwin 25 (macOS 26).
    "25".to_string()
}

fn cfg_var(key: &str) -> String {
    std::env::var(key).unwrap_or_default()
}
