# The bundled `optparse` package (packages/optparse), exercised against the
# same program real Ruby's own OptionParser runs -- the .expected here is
# generated by CRuby with ITS optparse, so any divergence in the subset shows
# up as a byte diff.
require "optparse"
opts = {}
parser = OptionParser.new do |o|
  o.banner = "Usage: demo [options] FILE"
  o.separator ""
  o.on("-v", "--verbose", "run verbosely") { |x| opts[:verbose] = x }
  o.on("-n", "--name NAME", "the name") { |v| opts[:name] = v }
  o.on("-c", "--count=N", "how many") { |v| opts[:count] = v }
end
argv = ["-v", "--name", "matz", "-c", "3", "file.txt", "--", "-notaflag"]
rest = parser.parse!(argv)
p rest
p argv
p opts[:verbose]
p opts[:name]
p opts[:count]
puts parser.help

o2 = OptionParser.new { |o| o.on("-a", "all") {}; o.on("-b", "bee") {} }
a2 = ["-ab", "x"]
o2.parse!(a2)
p a2

begin
  OptionParser.new { |o| o.on("-x", "ex") {} }.parse!(["--nope"])
rescue OptionParser::InvalidOption => e
  p e.message
  p e.class.ancestors.include?(StandardError)
end
begin
  OptionParser.new { |o| o.on("-n", "--name NAME", "n") {} }.parse!(["--name"])
rescue OptionParser::MissingArgument => e
  p e.message
end
