def fwd_map(&b)   = ({ a: 1, b: 2 }).map(&b)
def fwd_sel(&b)   = ({ a: 1, b: 2 }).select(&b)
def fwd_rej(&b)   = ({ a: 1, b: 2 }).reject(&b)
def fwd_sum(&b)   = ({ a: 1, b: 2 }).sum(&b)
def fwd_cnt(&b)   = ({ a: 1, b: 2 }).count(&b)
def fwd_find(&b)  = ({ a: 1, b: 2 }).find(&b)
def fwd_sort(&b)  = ({ a: 1, b: 2 }).sort_by(&b)
def fwd_min(&b)   = ({ a: 1, b: 2 }).min_by(&b)
def fwd_grp(&b)   = ({ a: 1, b: 2 }).group_by(&b)
def fwd_fmap(&b)  = ({ a: 1, b: 2 }).filter_map(&b)
def fwd_part(&b)  = ({ a: 1, b: 2 }).partition(&b)

p(fwd_map  { |k, v| v })
p(fwd_sel  { |k, v| v > 0 })
p(fwd_rej  { |k, v| v > 0 })
p(fwd_sum  { |k, v| v })
p(fwd_cnt  { |k, v| v > 1 })
p(fwd_find { |k, v| v > 1 })
p(fwd_sort { |k, v| -v })
p(fwd_min  { |k, v| -v })
p(fwd_grp  { |k, v| v.odd? })
p(fwd_fmap { |k, v| v > 1 ? v : nil })
p(fwd_part { |k, v| v > 1 })

