p("aaa".match(/(?>a+)a/))
p("aaa".match?(/(?>a+)a/))
p("aaa".match(/a++a/))
p("aaab".match(/(?>a+)b/)[0])
p("aaab".match(/a++b/)[0])
p("aaab" =~ /a*+b/)
p("abcd".match(/(?>\w+)/)[0])
p("aaa".match(/a?+a/))
p("foo bar".match(/(?>\w+)\s(\w+)/)[1])
p("aaa".scan(/(?>a)/).length)
p("2026-08-10".match(/(?>\d++)-(\d+)/)[1])
