//! `rb_*` entries that ARE a Ruby method call.
//!
//! Generated by `tools/zeo-dev cext forward` from
//! `conformance/cext-forward.tsv`. Do not edit.
//!
//! Most of MRI's object C API is a C name for a method Ruby already
//! has: `rb_str_length` IS `String#length`. zeo answers those by
//! CALLING the method, through the same `dispatch::send_value` a Ruby
//! program uses -- so each one sees the same MRO, the same
//! refinements, the same `method_missing` and the same visibility
//! rules, and cannot drift from the method it stands for.
//!
//! Reimplementing 91 of these in Rust would be 91
//! more places for `String#length` to be subtly wrong.

use super::convert::{to_value, value_of};
use super::value::Value;
use crate::{RubyValue, Signal, Symbol};

fn forward(recv: Value, meth: &str, args: &[Value]) -> Result<Value, Signal> {
    // SAFETY: every argument is an extension's own live `VALUE`.
    let recv = unsafe { value_of(recv) };
    let args: Vec<RubyValue> = args.iter().map(|a| unsafe { value_of(*a) }).collect();
    let out = crate::dispatch::send_value(&recv, Symbol::intern(meth), &args, None)?;
    to_value(&out)
}

crate::cext_fn! {
/// `Array#assoc`
fn rb_ary_assoc(recv: Value, a0: Value) -> Value {
    forward(recv, "assoc", &[a0])
}

/// `Array#<=>`
fn rb_ary_cmp(recv: Value, a0: Value) -> Value {
    forward(recv, "<=>", &[a0])
}

/// `Array#concat`
fn rb_ary_concat(recv: Value, a0: Value) -> Value {
    forward(recv, "concat", &[a0])
}

/// `Array#delete`
fn rb_ary_delete(recv: Value, a0: Value) -> Value {
    forward(recv, "delete", &[a0])
}

/// `Array#dup`
fn rb_ary_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Array#freeze`
fn rb_ary_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `Array#join`
fn rb_ary_join(recv: Value, a0: Value) -> Value {
    forward(recv, "join", &[a0])
}

/// `Array#+`
fn rb_ary_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Array#rassoc`
fn rb_ary_rassoc(recv: Value, a0: Value) -> Value {
    forward(recv, "rassoc", &[a0])
}

/// `Array#replace`
fn rb_ary_replace(recv: Value, a0: Value) -> Value {
    forward(recv, "replace", &[a0])
}

/// `Array#reverse`
fn rb_ary_reverse(recv: Value) -> Value {
    forward(recv, "reverse", &[])
}

/// `Array#sort`
fn rb_ary_sort(recv: Value) -> Value {
    forward(recv, "sort", &[])
}

/// `Array#sort!`
fn rb_ary_sort_bang(recv: Value) -> Value {
    forward(recv, "sort!", &[])
}

/// `Array#to_ary`
fn rb_ary_to_ary(recv: Value) -> Value {
    forward(recv, "to_ary", &[])
}

/// `Array#to_s`
fn rb_ary_to_s(recv: Value) -> Value {
    forward(recv, "to_s", &[])
}

/// `Array#unshift`
fn rb_ary_unshift(recv: Value, a0: Value) -> Value {
    forward(recv, "unshift", &[a0])
}

/// `Integer#clone`
fn rb_big_clone(recv: Value) -> Value {
    forward(recv, "clone", &[])
}

/// `Integer#<=>`
fn rb_big_cmp(recv: Value, a0: Value) -> Value {
    forward(recv, "<=>", &[a0])
}

/// `Integer#/`
fn rb_big_div(recv: Value, a0: Value) -> Value {
    forward(recv, "/", &[a0])
}

/// `Integer#divmod`
fn rb_big_divmod(recv: Value, a0: Value) -> Value {
    forward(recv, "divmod", &[a0])
}

/// `Integer#eql?`
fn rb_big_eql(recv: Value, a0: Value) -> Value {
    forward(recv, "eql?", &[a0])
}

/// `Integer#<<`
fn rb_big_lshift(recv: Value, a0: Value) -> Value {
    forward(recv, "<<", &[a0])
}

/// `Integer#-`
fn rb_big_minus(recv: Value, a0: Value) -> Value {
    forward(recv, "-", &[a0])
}

/// `Integer#%`
fn rb_big_modulo(recv: Value, a0: Value) -> Value {
    forward(recv, "%", &[a0])
}

/// `Integer#+`
fn rb_big_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Integer#**`
fn rb_big_pow(recv: Value, a0: Value) -> Value {
    forward(recv, "**", &[a0])
}

/// `Class#attached_object`
fn rb_class_attached_object(recv: Value) -> Value {
    forward(recv, "attached_object", &[])
}

/// `Class#subclasses`
fn rb_class_subclasses(recv: Value) -> Value {
    forward(recv, "subclasses", &[])
}

/// `Class#superclass`
fn rb_class_superclass(recv: Value) -> Value {
    forward(recv, "superclass", &[])
}

/// `Complex#abs`
fn rb_complex_abs(recv: Value) -> Value {
    forward(recv, "abs", &[])
}

/// `Complex#arg`
fn rb_complex_arg(recv: Value) -> Value {
    forward(recv, "arg", &[])
}

/// `Complex#conjugate`
fn rb_complex_conjugate(recv: Value) -> Value {
    forward(recv, "conjugate", &[])
}

/// `Complex#/`
fn rb_complex_div(recv: Value, a0: Value) -> Value {
    forward(recv, "/", &[a0])
}

/// `Complex#imag`
fn rb_complex_imag(recv: Value) -> Value {
    forward(recv, "imag", &[])
}

/// `Complex#-`
fn rb_complex_minus(recv: Value, a0: Value) -> Value {
    forward(recv, "-", &[a0])
}

/// `Complex#+`
fn rb_complex_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Complex#**`
fn rb_complex_pow(recv: Value, a0: Value) -> Value {
    forward(recv, "**", &[a0])
}

/// `Complex#real`
fn rb_complex_real(recv: Value) -> Value {
    forward(recv, "real", &[])
}

/// `Fiber#alive?`
fn rb_fiber_alive_p(recv: Value) -> Value {
    forward(recv, "alive?", &[])
}

/// `Hash#delete`
fn rb_hash_delete(recv: Value, a0: Value) -> Value {
    forward(recv, "delete", &[a0])
}

/// `Hash#dup`
fn rb_hash_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Hash#fetch`
fn rb_hash_fetch(recv: Value, a0: Value) -> Value {
    forward(recv, "fetch", &[a0])
}

/// `Hash#freeze`
fn rb_hash_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `IO#binmode`
fn rb_io_binmode(recv: Value) -> Value {
    forward(recv, "binmode", &[])
}

/// `IO#close`
fn rb_io_close(recv: Value) -> Value {
    forward(recv, "close", &[])
}

/// `IO#eof`
fn rb_io_eof(recv: Value) -> Value {
    forward(recv, "eof", &[])
}

/// `IO#flush`
fn rb_io_flush(recv: Value) -> Value {
    forward(recv, "flush", &[])
}

/// `IO#getbyte`
fn rb_io_getbyte(recv: Value) -> Value {
    forward(recv, "getbyte", &[])
}

/// `IO#gets`
fn rb_io_gets(recv: Value) -> Value {
    forward(recv, "gets", &[])
}

/// `IO#ungetbyte`
fn rb_io_ungetbyte(recv: Value, a0: Value) -> Value {
    forward(recv, "ungetbyte", &[a0])
}

/// `IO#ungetc`
fn rb_io_ungetc(recv: Value, a0: Value) -> Value {
    forward(recv, "ungetc", &[a0])
}

/// `IO#write`
fn rb_io_write(recv: Value, a0: Value) -> Value {
    forward(recv, "write", &[a0])
}

/// `Module#ancestors`
fn rb_mod_ancestors(recv: Value) -> Value {
    forward(recv, "ancestors", &[])
}

/// `Module#include?`
fn rb_mod_include_p(recv: Value, a0: Value) -> Value {
    forward(recv, "include?", &[a0])
}

/// `Module#included_modules`
fn rb_mod_included_modules(recv: Value) -> Value {
    forward(recv, "included_modules", &[])
}

/// `Module#name`
fn rb_mod_name(recv: Value) -> Value {
    forward(recv, "name", &[])
}

/// `Module#remove_const`
fn rb_mod_remove_const(recv: Value, a0: Value) -> Value {
    forward(recv, "remove_const", &[a0])
}

/// `Thread::Mutex#lock`
fn rb_mutex_lock(recv: Value) -> Value {
    forward(recv, "lock", &[])
}

/// `Thread::Mutex#locked?`
fn rb_mutex_locked_p(recv: Value) -> Value {
    forward(recv, "locked?", &[])
}

/// `Thread::Mutex#sleep`
fn rb_mutex_sleep(recv: Value, a0: Value) -> Value {
    forward(recv, "sleep", &[a0])
}

/// `Thread::Mutex#unlock`
fn rb_mutex_unlock(recv: Value) -> Value {
    forward(recv, "unlock", &[])
}

/// `Object#clone`
fn rb_obj_clone(recv: Value) -> Value {
    forward(recv, "clone", &[])
}

/// `Object#dup`
fn rb_obj_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Object#freeze`
fn rb_obj_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `Object#frozen?`
fn rb_obj_frozen_p(recv: Value) -> Value {
    forward(recv, "frozen?", &[])
}

/// `Object#instance_variables`
fn rb_obj_instance_variables(recv: Value) -> Value {
    forward(recv, "instance_variables", &[])
}

/// `Object#method`
fn rb_obj_method(recv: Value, a0: Value) -> Value {
    forward(recv, "method", &[a0])
}

/// `Object#remove_instance_variable`
fn rb_obj_remove_instance_variable(recv: Value, a0: Value) -> Value {
    forward(recv, "remove_instance_variable", &[a0])
}

/// `Proc#lambda?`
fn rb_proc_lambda_p(recv: Value) -> Value {
    forward(recv, "lambda?", &[])
}

/// `Set#clear`
fn rb_set_clear(recv: Value) -> Value {
    forward(recv, "clear", &[])
}

/// `String#concat`
fn rb_str_concat(recv: Value, a0: Value) -> Value {
    forward(recv, "concat", &[a0])
}

/// `String#dump`
fn rb_str_dump(recv: Value) -> Value {
    forward(recv, "dump", &[])
}

/// `String#==`
fn rb_str_equal(recv: Value, a0: Value) -> Value {
    forward(recv, "==", &[a0])
}

/// `String#inspect`
fn rb_str_inspect(recv: Value) -> Value {
    forward(recv, "inspect", &[])
}

/// `String#intern`
fn rb_str_intern(recv: Value) -> Value {
    forward(recv, "intern", &[])
}

/// `String#length`
fn rb_str_length(recv: Value) -> Value {
    forward(recv, "length", &[])
}

/// `String#+`
fn rb_str_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `String#replace`
fn rb_str_replace(recv: Value, a0: Value) -> Value {
    forward(recv, "replace", &[a0])
}

/// `String#scrub`
fn rb_str_scrub(recv: Value, a0: Value) -> Value {
    forward(recv, "scrub", &[a0])
}

/// `String#succ`
fn rb_str_succ(recv: Value) -> Value {
    forward(recv, "succ", &[])
}

/// `String#*`
fn rb_str_times(recv: Value, a0: Value) -> Value {
    forward(recv, "*", &[a0])
}

/// `String#to_str`
fn rb_str_to_str(recv: Value) -> Value {
    forward(recv, "to_str", &[])
}

/// `Struct#[]`
fn rb_struct_aref(recv: Value, a0: Value) -> Value {
    forward(recv, "[]", &[a0])
}

/// `Struct#[]=`
fn rb_struct_aset(recv: Value, a0: Value, a1: Value) -> Value {
    forward(recv, "[]=", &[a0, a1])
}

/// `Struct#members`
fn rb_struct_members(recv: Value) -> Value {
    forward(recv, "members", &[])
}

/// `Struct#size`
fn rb_struct_size(recv: Value) -> Value {
    forward(recv, "size", &[])
}

/// `Symbol#to_s`
fn rb_sym_to_s(recv: Value) -> Value {
    forward(recv, "to_s", &[])
}

/// `Thread#kill`
fn rb_thread_kill(recv: Value) -> Value {
    forward(recv, "kill", &[])
}

/// `Thread#run`
fn rb_thread_run(recv: Value) -> Value {
    forward(recv, "run", &[])
}

/// `Thread#wakeup`
fn rb_thread_wakeup(recv: Value) -> Value {
    forward(recv, "wakeup", &[])
}

/// `Time#utc_offset`
fn rb_time_utc_offset(recv: Value) -> Value {
    forward(recv, "utc_offset", &[])
}
}
