//! MRI's object layout, read from the vendored headers rather than retyped.
//!
//! Every struct here is generated by `build.rs`'s bindgen pass over
//! `cext/probe/mirror.h`, together with `offset_of` assertions that fail THIS
//! build if a header bump moves a field. That is the whole point: the Rust
//! that fills a view has to agree with the header to the byte, and a
//! hand-written `#[repr(C)]` copy would be a second owner of one fact -- a
//! wrong offset in it reads or writes an unrelated field, silently.
//!
//! Nothing here is public API. [`super::view`] is what fills these, and
//! [`super::handles`] is what writes the flag enums into an object.

// Generated code keeps C's spelling, and the tree carries names zeo's own
// entries never mention -- `struct rb_econv_t` rides in because `struct rb_io`
// points at one.
#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code
)]

include!(concat!(env!("OUT_DIR"), "/cext_layout.rs"));

/// Readable names for the anonymous members bindgen numbers. The generated
/// spellings are stable, but `RString__bindgen_ty_1__bindgen_ty_1` at a fill
/// site says nothing about what is being filled.
pub type RStringPayload = RString__bindgen_ty_1;
pub type RStringHeap = RString__bindgen_ty_1__bindgen_ty_1;
pub type RStringAux = RString__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1;
pub type RArrayPayload = RArray__bindgen_ty_1;
pub type RArrayHeap = RArray__bindgen_ty_1__bindgen_ty_1;
pub type RArrayAux = RArray__bindgen_ty_1__bindgen_ty_1__bindgen_ty_1;
pub type RObjectPayload = RObject__bindgen_ty_1;
pub type RObjectHeap = RObject__bindgen_ty_1__bindgen_ty_1;
pub type RTypedDataFns = rb_data_type_struct__bindgen_ty_1;

/// The three shape flags zeo sets on an object so that upstream's own
/// accessors take the arm a view can answer, plus the two the handle writes.
///
/// Named here rather than at the use sites because each is one member of a
/// generated enum, and `ruby_rstring_flags_RSTRING_NOEMBED` reads as noise.
pub const RSTRING_NOEMBED: usize = ruby_rstring_flags_RSTRING_NOEMBED as usize;
pub const ROBJECT_HEAP: usize = ruby_robject_flags_ROBJECT_HEAP as usize;
pub const RARRAY_EMBED_FLAG: usize = ruby_rarray_flags_RARRAY_EMBED_FLAG as usize;
pub const FL_FREEZE: usize = ruby_fl_type_RUBY_FL_FREEZE as usize;
pub const FL_IS_TYPED_DATA: usize =
    rbimpl_typeddata_flags_RUBY_TYPED_FL_IS_TYPED_DATA as usize;
