//! One loud stub per `rb_*` zeo does not answer yet.
//!
//! Generated by `tools/zeo-dev cext api`. Do not edit.
//!
//! # Why every one of them exists
//!
//! A gem's `ext/**/*.c` is compiled and linked as a whole. One
//! reference to a function zeo has not written yet would fail the
//! LINK, with a message naming a symbol and no gem, no file and no
//! line -- and it would fail even when the call sits on a branch the
//! program never takes. So every declared symbol resolves, and one
//! that is not implemented raises when it is CALLED, naming itself.
//!
//! A stub disappears the moment the real function is written: the
//! generator reads `#[unsafe(no_mangle)]` out of the other files in
//! this module, so implementing one is all it takes.
//!
//! # The signatures
//!
//! A stub takes no arguments and never returns. By the C standard
//! that is a prototype mismatch; on both ABIs zeo targets it is
//! safe. The caller passes arguments in registers and on a stack it
//! cleans up itself, the callee reads none of them, and it never
//! returns -- so there is no return value to disagree about and no
//! frame to unwind. Writing 440 correct signatures would
//! buy nothing: not one of these functions runs.
//!
//! # The globals
//!
//! `rb_cObject`, `rb_eArgError` and 90 others are
//! `VALUE` variables an extension reads directly, so each is a real
//! symbol rather than a stub. Each starts as `Qundef` and the
//! loader fills it before any `Init_` runs; [`GLOBALS`] is what it
//! walks, and `every_global_is_filled` is what proves none was
//! missed. Nothing can read one before the loader runs, because
//! nothing has loaded.

use std::sync::atomic::{AtomicUsize, Ordering};

/// A `VALUE` variable C reads by name. `AtomicUsize` so Rust can
/// write it; C sees a plain `VALUE`, which is the same word.
pub type Global = AtomicUsize;

/// Every global starts here, and the loader is what moves it.
const fn unfilled() -> Global {
    AtomicUsize::new(crate::cext::value::Q_UNDEF)
}

/// Every `VALUE` global, by the name C spells.
pub static GLOBALS: &[(&str, &Global)] = &[
    ("rb_argv0", &rb_argv0),
    ("rb_cArray", &rb_cArray),
    ("rb_cBasicObject", &rb_cBasicObject),
    ("rb_cBinding", &rb_cBinding),
    ("rb_cBox", &rb_cBox),
    ("rb_cClass", &rb_cClass),
    ("rb_cComplex", &rb_cComplex),
    ("rb_cDir", &rb_cDir),
    ("rb_cEncoding", &rb_cEncoding),
    ("rb_cEnumerator", &rb_cEnumerator),
    ("rb_cFalseClass", &rb_cFalseClass),
    ("rb_cFile", &rb_cFile),
    ("rb_cFloat", &rb_cFloat),
    ("rb_cHash", &rb_cHash),
    ("rb_cIO", &rb_cIO),
    ("rb_cInteger", &rb_cInteger),
    ("rb_cMatch", &rb_cMatch),
    ("rb_cMethod", &rb_cMethod),
    ("rb_cModule", &rb_cModule),
    ("rb_cNameErrorMesg", &rb_cNameErrorMesg),
    ("rb_cNilClass", &rb_cNilClass),
    ("rb_cNumeric", &rb_cNumeric),
    ("rb_cObject", &rb_cObject),
    ("rb_cProc", &rb_cProc),
    ("rb_cRandom", &rb_cRandom),
    ("rb_cRange", &rb_cRange),
    ("rb_cRational", &rb_cRational),
    ("rb_cRefinement", &rb_cRefinement),
    ("rb_cRegexp", &rb_cRegexp),
    ("rb_cSet", &rb_cSet),
    ("rb_cStat", &rb_cStat),
    ("rb_cString", &rb_cString),
    ("rb_cStruct", &rb_cStruct),
    ("rb_cSymbol", &rb_cSymbol),
    ("rb_cThread", &rb_cThread),
    ("rb_cTime", &rb_cTime),
    ("rb_cTrueClass", &rb_cTrueClass),
    ("rb_cUnboundMethod", &rb_cUnboundMethod),
    ("rb_default_rs", &rb_default_rs),
    ("rb_eArgError", &rb_eArgError),
    ("rb_eEOFError", &rb_eEOFError),
    ("rb_eEncCompatError", &rb_eEncCompatError),
    ("rb_eEncodingError", &rb_eEncodingError),
    ("rb_eException", &rb_eException),
    ("rb_eFatal", &rb_eFatal),
    ("rb_eFloatDomainError", &rb_eFloatDomainError),
    ("rb_eFrozenError", &rb_eFrozenError),
    ("rb_eIOError", &rb_eIOError),
    ("rb_eIndexError", &rb_eIndexError),
    ("rb_eInterrupt", &rb_eInterrupt),
    ("rb_eKeyError", &rb_eKeyError),
    ("rb_eLoadError", &rb_eLoadError),
    ("rb_eLocalJumpError", &rb_eLocalJumpError),
    ("rb_eMathDomainError", &rb_eMathDomainError),
    ("rb_eNameError", &rb_eNameError),
    ("rb_eNoMatchingPatternError", &rb_eNoMatchingPatternError),
    (
        "rb_eNoMatchingPatternKeyError",
        &rb_eNoMatchingPatternKeyError,
    ),
    ("rb_eNoMemError", &rb_eNoMemError),
    ("rb_eNoMethodError", &rb_eNoMethodError),
    ("rb_eNotImpError", &rb_eNotImpError),
    ("rb_eRangeError", &rb_eRangeError),
    ("rb_eRegexpError", &rb_eRegexpError),
    ("rb_eRuntimeError", &rb_eRuntimeError),
    ("rb_eScriptError", &rb_eScriptError),
    ("rb_eSecurityError", &rb_eSecurityError),
    ("rb_eSignal", &rb_eSignal),
    ("rb_eStandardError", &rb_eStandardError),
    ("rb_eStopIteration", &rb_eStopIteration),
    ("rb_eSyntaxError", &rb_eSyntaxError),
    ("rb_eSysStackError", &rb_eSysStackError),
    ("rb_eSystemCallError", &rb_eSystemCallError),
    ("rb_eSystemExit", &rb_eSystemExit),
    ("rb_eThreadError", &rb_eThreadError),
    ("rb_eTypeError", &rb_eTypeError),
    ("rb_eZeroDivError", &rb_eZeroDivError),
    ("rb_fs", &rb_fs),
    ("rb_mComparable", &rb_mComparable),
    ("rb_mEnumerable", &rb_mEnumerable),
    ("rb_mErrno", &rb_mErrno),
    ("rb_mFileTest", &rb_mFileTest),
    ("rb_mGC", &rb_mGC),
    ("rb_mKernel", &rb_mKernel),
    ("rb_mMath", &rb_mMath),
    ("rb_mProcess", &rb_mProcess),
    ("rb_mWaitReadable", &rb_mWaitReadable),
    ("rb_mWaitWritable", &rb_mWaitWritable),
    ("rb_output_fs", &rb_output_fs),
    ("rb_output_rs", &rb_output_rs),
    ("rb_rs", &rb_rs),
    ("rb_stderr", &rb_stderr),
    ("rb_stdin", &rb_stdin),
    ("rb_stdout", &rb_stdout),
];

/// Read one, for a caller that has the name rather than the symbol.
pub fn global(name: &str) -> Option<usize> {
    GLOBALS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, g)| g.load(Ordering::Relaxed))
}

/// Raise, naming the symbol the extension asked for.
fn unimplemented(what: &'static str) -> ! {
    crate::cext::jmp::raise(crate::dispatch::raise_error(
        "NotImplementedError",
        format!("{what} is not implemented by zeo"),
    ))
}

#[unsafe(no_mangle)]
pub static rb_argv0: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cArray: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBasicObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBinding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBox: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cComplex: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cDir: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEncoding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEnumerator: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFalseClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFile: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFloat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cHash: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cIO: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cInteger: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMatch: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cModule: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNameErrorMesg: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNilClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNumeric: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cProc: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRandom: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRange: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRational: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRefinement: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRegexp: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSet: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cString: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStruct: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSymbol: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cThread: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTime: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTrueClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cUnboundMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_default_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eArgError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEOFError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncCompatError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncodingError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eException: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFatal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFloatDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFrozenError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIOError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIndexError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eInterrupt: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLoadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLocalJumpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eMathDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNameError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMemError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMethodError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNotImpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRangeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRegexpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRuntimeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eScriptError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSecurityError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSignal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStandardError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStopIteration: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSyntaxError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSysStackError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemCallError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemExit: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eThreadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eTypeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eZeroDivError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mComparable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mEnumerable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mErrno: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mFileTest: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mGC: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mKernel: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mMath: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mProcess: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitReadable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitWritable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stderr: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdin: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdout: Global = unfilled();

#[unsafe(no_mangle)]
pub extern "C" fn rb_Hash() -> ! {
    unimplemented("rb_Hash")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_absint_numwords() -> ! {
    unimplemented("rb_absint_numwords")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_absint_singlebit_p() -> ! {
    unimplemented("rb_absint_singlebit_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_add_event_hook() -> ! {
    unimplemented("rb_add_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_alias() -> ! {
    unimplemented("rb_alias")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_alias_variable() -> ! {
    unimplemented("rb_alias_variable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_alloc_tmp_buffer() -> ! {
    unimplemented("rb_alloc_tmp_buffer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_alloc_tmp_buffer_with_count() -> ! {
    unimplemented("rb_alloc_tmp_buffer_with_count")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_apply() -> ! {
    unimplemented("rb_apply")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_arithmetic_sequence_beg_len_step() -> ! {
    unimplemented("rb_arithmetic_sequence_beg_len_step")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_arithmetic_sequence_extract() -> ! {
    unimplemented("rb_arithmetic_sequence_extract")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_aref() -> ! {
    unimplemented("rb_ary_aref")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_cat() -> ! {
    unimplemented("rb_ary_cat")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_delete_at() -> ! {
    unimplemented("rb_ary_delete_at")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_each() -> ! {
    unimplemented("rb_ary_each")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_free() -> ! {
    unimplemented("rb_ary_free")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_hidden_new() -> ! {
    unimplemented("rb_ary_hidden_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_modify() -> ! {
    unimplemented("rb_ary_modify")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_new_from_args() -> ! {
    unimplemented("rb_ary_new_from_args")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_ptr_use_end() -> ! {
    unimplemented("rb_ary_ptr_use_end")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_ptr_use_start() -> ! {
    unimplemented("rb_ary_ptr_use_start")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_resize() -> ! {
    unimplemented("rb_ary_resize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_resurrect() -> ! {
    unimplemented("rb_ary_resurrect")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_rotate() -> ! {
    unimplemented("rb_ary_rotate")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_shared_with_p() -> ! {
    unimplemented("rb_ary_shared_with_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_store() -> ! {
    unimplemented("rb_ary_store")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ary_subseq() -> ! {
    unimplemented("rb_ary_subseq")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_assert_failure() -> ! {
    unimplemented("rb_assert_failure")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_assoc_new() -> ! {
    unimplemented("rb_assoc_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_attr() -> ! {
    unimplemented("rb_attr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_attr_get() -> ! {
    unimplemented("rb_attr_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_autoload_load() -> ! {
    unimplemented("rb_autoload_load")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_autoload_p() -> ! {
    unimplemented("rb_autoload_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_backref_get() -> ! {
    unimplemented("rb_backref_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_backref_set() -> ! {
    unimplemented("rb_backref_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_backtrace() -> ! {
    unimplemented("rb_backtrace")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_2comp() -> ! {
    unimplemented("rb_big_2comp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_new() -> ! {
    unimplemented("rb_big_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_pack() -> ! {
    unimplemented("rb_big_pack")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_resize() -> ! {
    unimplemented("rb_big_resize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_unpack() -> ! {
    unimplemented("rb_big_unpack")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_binding_new() -> ! {
    unimplemented("rb_binding_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_block_call() -> ! {
    unimplemented("rb_block_call")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_block_call_kw() -> ! {
    unimplemented("rb_block_call_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_block_lambda() -> ! {
    unimplemented("rb_block_lambda")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_block_proc() -> ! {
    unimplemented("rb_block_proc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_bug_errno() -> ! {
    unimplemented("rb_bug_errno")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_call_super() -> ! {
    unimplemented("rb_call_super")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_call_super_kw() -> ! {
    unimplemented("rb_call_super_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_catch() -> ! {
    unimplemented("rb_catch")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_catch_obj() -> ! {
    unimplemented("rb_catch_obj")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_check_funcall() -> ! {
    unimplemented("rb_check_funcall")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_check_funcall_kw() -> ! {
    unimplemented("rb_check_funcall_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_class_descendants() -> ! {
    unimplemented("rb_class_descendants")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_clear_constant_cache() -> ! {
    unimplemented("rb_clear_constant_cache")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_clear_constant_cache_for_id() -> ! {
    unimplemented("rb_clear_constant_cache_for_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cloexec_dup() -> ! {
    unimplemented("rb_cloexec_dup")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cloexec_dup2() -> ! {
    unimplemented("rb_cloexec_dup2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cloexec_fcntl_dupfd() -> ! {
    unimplemented("rb_cloexec_fcntl_dupfd")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cloexec_open() -> ! {
    unimplemented("rb_cloexec_open")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cloexec_pipe() -> ! {
    unimplemented("rb_cloexec_pipe")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_close_before_exec() -> ! {
    unimplemented("rb_close_before_exec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cmperr() -> ! {
    unimplemented("rb_cmperr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cmpint() -> ! {
    unimplemented("rb_cmpint")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_const_list() -> ! {
    unimplemented("rb_const_list")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_convert_type() -> ! {
    unimplemented("rb_convert_type")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_copy_generic_ivar() -> ! {
    unimplemented("rb_copy_generic_ivar")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_current_receiver() -> ! {
    unimplemented("rb_current_receiver")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cv_get() -> ! {
    unimplemented("rb_cv_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_cv_set() -> ! {
    unimplemented("rb_cv_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_data_define() -> ! {
    unimplemented("rb_data_define")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_rstring_null_ptr() -> ! {
    unimplemented("rb_debug_rstring_null_ptr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_attr() -> ! {
    unimplemented("rb_define_attr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_class_id() -> ! {
    unimplemented("rb_define_class_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_class_id_under() -> ! {
    unimplemented("rb_define_class_id_under")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_finalizer() -> ! {
    unimplemented("rb_define_finalizer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_global_function() -> ! {
    unimplemented("rb_define_global_function")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_hooked_variable() -> ! {
    unimplemented("rb_define_hooked_variable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_method_id() -> ! {
    unimplemented("rb_define_method_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_module_function() -> ! {
    unimplemented("rb_define_module_function")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_module_id() -> ! {
    unimplemented("rb_define_module_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_module_id_under() -> ! {
    unimplemented("rb_define_module_id_under")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_readonly_variable() -> ! {
    unimplemented("rb_define_readonly_variable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_variable() -> ! {
    unimplemented("rb_define_variable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_define_virtual_variable() -> ! {
    unimplemented("rb_define_virtual_variable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_deprecate_constant() -> ! {
    unimplemented("rb_deprecate_constant")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_detach_process() -> ! {
    unimplemented("rb_detach_process")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_dir_getwd() -> ! {
    unimplemented("rb_dir_getwd")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_during_gc() -> ! {
    unimplemented("rb_during_gc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_each() -> ! {
    unimplemented("rb_each")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_enum_values_pack() -> ! {
    unimplemented("rb_enum_values_pack")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_enumeratorize() -> ! {
    unimplemented("rb_enumeratorize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_enumeratorize_with_size() -> ! {
    unimplemented("rb_enumeratorize_with_size")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_enumeratorize_with_size_kw() -> ! {
    unimplemented("rb_enumeratorize_with_size_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_env_clear() -> ! {
    unimplemented("rb_env_clear")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_eval_cmd_kw() -> ! {
    unimplemented("rb_eval_cmd_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_eval_string() -> ! {
    unimplemented("rb_eval_string")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_eval_string_protect() -> ! {
    unimplemented("rb_eval_string_protect")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_eval_string_wrap() -> ! {
    unimplemented("rb_eval_string_wrap")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_exec_recursive() -> ! {
    unimplemented("rb_exec_recursive")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_exec_recursive_outer() -> ! {
    unimplemented("rb_exec_recursive_outer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_exec_recursive_paired() -> ! {
    unimplemented("rb_exec_recursive_paired")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_exec_recursive_paired_outer() -> ! {
    unimplemented("rb_exec_recursive_paired_outer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_exit() -> ! {
    unimplemented("rb_exit")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ext_ractor_safe() -> ! {
    unimplemented("rb_ext_ractor_safe")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ext_resolve_symbol() -> ! {
    unimplemented("rb_ext_resolve_symbol")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_external_str_new() -> ! {
    unimplemented("rb_external_str_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_external_str_new_cstr() -> ! {
    unimplemented("rb_external_str_new_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_extract_keywords() -> ! {
    unimplemented("rb_extract_keywords")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_abort() -> ! {
    unimplemented("rb_f_abort")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_exec() -> ! {
    unimplemented("rb_f_exec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_exit() -> ! {
    unimplemented("rb_f_exit")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_global_variables() -> ! {
    unimplemented("rb_f_global_variables")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_kill() -> ! {
    unimplemented("rb_f_kill")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_require() -> ! {
    unimplemented("rb_f_require")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_sprintf() -> ! {
    unimplemented("rb_f_sprintf")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_trace_var() -> ! {
    unimplemented("rb_f_trace_var")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_f_untrace_var() -> ! {
    unimplemented("rb_f_untrace_var")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fd_fix_cloexec() -> ! {
    unimplemented("rb_fd_fix_cloexec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_feature_provided() -> ! {
    unimplemented("rb_feature_provided")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_current() -> ! {
    unimplemented("rb_fiber_current")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_new() -> ! {
    unimplemented("rb_fiber_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_new_storage() -> ! {
    unimplemented("rb_fiber_new_storage")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_raise() -> ! {
    unimplemented("rb_fiber_raise")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_resume() -> ! {
    unimplemented("rb_fiber_resume")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_resume_kw() -> ! {
    unimplemented("rb_fiber_resume_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_transfer() -> ! {
    unimplemented("rb_fiber_transfer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_transfer_kw() -> ! {
    unimplemented("rb_fiber_transfer_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_yield() -> ! {
    unimplemented("rb_fiber_yield")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_fiber_yield_kw() -> ! {
    unimplemented("rb_fiber_yield_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_absolute_path() -> ! {
    unimplemented("rb_file_absolute_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_directory_p() -> ! {
    unimplemented("rb_file_directory_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_dirname() -> ! {
    unimplemented("rb_file_dirname")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_expand_path() -> ! {
    unimplemented("rb_file_expand_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_open() -> ! {
    unimplemented("rb_file_open")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_open_str() -> ! {
    unimplemented("rb_file_open_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_s_absolute_path() -> ! {
    unimplemented("rb_file_s_absolute_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_s_expand_path() -> ! {
    unimplemented("rb_file_s_expand_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_file_size() -> ! {
    unimplemented("rb_file_size")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_filesystem_str_new() -> ! {
    unimplemented("rb_filesystem_str_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_filesystem_str_new_cstr() -> ! {
    unimplemented("rb_filesystem_str_new_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_find_file() -> ! {
    unimplemented("rb_find_file")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_find_file_ext() -> ! {
    unimplemented("rb_find_file_ext")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_flt_rationalize() -> ! {
    unimplemented("rb_flt_rationalize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_flt_rationalize_with_prec() -> ! {
    unimplemented("rb_flt_rationalize_with_prec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_frame_callee() -> ! {
    unimplemented("rb_frame_callee")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_frame_method_id_and_class() -> ! {
    unimplemented("rb_frame_method_id_and_class")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_frame_this_func() -> ! {
    unimplemented("rb_frame_this_func")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_free_generic_ivar() -> ! {
    unimplemented("rb_free_generic_ivar")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_free_tmp_buffer() -> ! {
    unimplemented("rb_free_tmp_buffer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_freeze_singleton_class() -> ! {
    unimplemented("rb_freeze_singleton_class")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_funcall_passing_block() -> ! {
    unimplemented("rb_funcall_passing_block")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_funcall_passing_block_kw() -> ! {
    unimplemented("rb_funcall_passing_block_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_funcall_with_block_kw() -> ! {
    unimplemented("rb_funcall_with_block_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_funcallv_kw() -> ! {
    unimplemented("rb_funcallv_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_funcallv_public_kw() -> ! {
    unimplemented("rb_funcallv_public_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc() -> ! {
    unimplemented("rb_gc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_adjust_memory_usage() -> ! {
    unimplemented("rb_gc_adjust_memory_usage")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_copy_finalizer() -> ! {
    unimplemented("rb_gc_copy_finalizer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_count() -> ! {
    unimplemented("rb_gc_count")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_disable() -> ! {
    unimplemented("rb_gc_disable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_enable() -> ! {
    unimplemented("rb_gc_enable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_latest_gc_info() -> ! {
    unimplemented("rb_gc_latest_gc_info")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_mark_maybe() -> ! {
    unimplemented("rb_gc_mark_maybe")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_register_mark_object() -> ! {
    unimplemented("rb_gc_register_mark_object")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_start() -> ! {
    unimplemented("rb_gc_start")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_stat() -> ! {
    unimplemented("rb_gc_stat")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_update_tbl_refs() -> ! {
    unimplemented("rb_gc_update_tbl_refs")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_writebarrier() -> ! {
    unimplemented("rb_gc_writebarrier")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gc_writebarrier_unprotect() -> ! {
    unimplemented("rb_gc_writebarrier_unprotect")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_alloc_func() -> ! {
    unimplemented("rb_get_alloc_func")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_argv() -> ! {
    unimplemented("rb_get_argv")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_kwargs() -> ! {
    unimplemented("rb_get_kwargs")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_path() -> ! {
    unimplemented("rb_get_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_path_no_checksafe() -> ! {
    unimplemented("rb_get_path_no_checksafe")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_get_values_at() -> ! {
    unimplemented("rb_get_values_at")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_gets() -> ! {
    unimplemented("rb_gets")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_glob() -> ! {
    unimplemented("rb_glob")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash() -> ! {
    unimplemented("rb_hash")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_bulk_insert() -> ! {
    unimplemented("rb_hash_bulk_insert")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_bulk_insert_into_st_table() -> ! {
    unimplemented("rb_hash_bulk_insert_into_st_table")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_delete_if() -> ! {
    unimplemented("rb_hash_delete_if")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_set_ifnone() -> ! {
    unimplemented("rb_hash_set_ifnone")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_size_num() -> ! {
    unimplemented("rb_hash_size_num")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_tbl() -> ! {
    unimplemented("rb_hash_tbl")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_update_by() -> ! {
    unimplemented("rb_hash_update_by")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_id2str() -> ! {
    unimplemented("rb_id2str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_id_attrset() -> ! {
    unimplemented("rb_id_attrset")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_interned_str() -> ! {
    unimplemented("rb_interned_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_interned_str_cstr() -> ! {
    unimplemented("rb_interned_str_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_addstr() -> ! {
    unimplemented("rb_io_addstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_ascii8bit_binmode() -> ! {
    unimplemented("rb_io_ascii8bit_binmode")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_fdopen() -> ! {
    unimplemented("rb_io_fdopen")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_print() -> ! {
    unimplemented("rb_io_print")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_printf() -> ! {
    unimplemented("rb_io_printf")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_puts() -> ! {
    unimplemented("rb_io_puts")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_iter_break() -> ! {
    unimplemented("rb_iter_break")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_iter_break_value() -> ! {
    unimplemented("rb_iter_break_value")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_iterate() -> ! {
    unimplemented("rb_iterate")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_keyword_given_p() -> ! {
    unimplemented("rb_keyword_given_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_last_status_get() -> ! {
    unimplemented("rb_last_status_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_last_status_set() -> ! {
    unimplemented("rb_last_status_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_lastline_get() -> ! {
    unimplemented("rb_lastline_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_lastline_set() -> ! {
    unimplemented("rb_lastline_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load() -> ! {
    unimplemented("rb_load")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file() -> ! {
    unimplemented("rb_load_file")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file_str() -> ! {
    unimplemented("rb_load_file_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_protect() -> ! {
    unimplemented("rb_load_protect")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_locale_str_new() -> ! {
    unimplemented("rb_locale_str_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_locale_str_new_cstr() -> ! {
    unimplemented("rb_locale_str_new_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_make_backtrace() -> ! {
    unimplemented("rb_make_backtrace")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_make_exception() -> ! {
    unimplemented("rb_make_exception")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mark_hash() -> ! {
    unimplemented("rb_mark_hash")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mark_set() -> ! {
    unimplemented("rb_mark_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mark_tbl() -> ! {
    unimplemented("rb_mark_tbl")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mark_tbl_no_pin() -> ! {
    unimplemented("rb_mark_tbl_no_pin")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_marshal_define_compat() -> ! {
    unimplemented("rb_marshal_define_compat")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_marshal_dump() -> ! {
    unimplemented("rb_marshal_dump")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_marshal_load() -> ! {
    unimplemented("rb_marshal_load")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_match_busy() -> ! {
    unimplemented("rb_match_busy")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mem_clear() -> ! {
    unimplemented("rb_mem_clear")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memcicmp() -> ! {
    unimplemented("rb_memcicmp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_id() -> ! {
    unimplemented("rb_memory_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_basic_definition_p() -> ! {
    unimplemented("rb_method_basic_definition_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_boundp() -> ! {
    unimplemented("rb_method_boundp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_call() -> ! {
    unimplemented("rb_method_call")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_call_kw() -> ! {
    unimplemented("rb_method_call_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_call_with_block() -> ! {
    unimplemented("rb_method_call_with_block")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_method_call_with_block_kw() -> ! {
    unimplemented("rb_method_call_with_block_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mod_const_at() -> ! {
    unimplemented("rb_mod_const_at")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mod_const_of() -> ! {
    unimplemented("rb_mod_const_of")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_must_asciicompat() -> ! {
    unimplemented("rb_must_asciicompat")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mutex_new() -> ! {
    unimplemented("rb_mutex_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mutex_synchronize() -> ! {
    unimplemented("rb_mutex_synchronize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_mutex_trylock() -> ! {
    unimplemented("rb_mutex_trylock")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_need_block() -> ! {
    unimplemented("rb_need_block")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_notimplement() -> ! {
    unimplemented("rb_notimplement")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_obj_hide() -> ! {
    unimplemented("rb_obj_hide")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_obj_reveal() -> ! {
    unimplemented("rb_obj_reveal")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_obj_setup() -> ! {
    unimplemented("rb_obj_setup")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_out_of_int() -> ! {
    unimplemented("rb_out_of_int")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_p() -> ! {
    unimplemented("rb_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_pipe() -> ! {
    unimplemented("rb_pipe")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_prepend_module() -> ! {
    unimplemented("rb_prepend_module")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_arity() -> ! {
    unimplemented("rb_proc_arity")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_call() -> ! {
    unimplemented("rb_proc_call")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_call_kw() -> ! {
    unimplemented("rb_proc_call_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_call_with_block_kw() -> ! {
    unimplemented("rb_proc_call_with_block_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_exec() -> ! {
    unimplemented("rb_proc_exec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_new() -> ! {
    unimplemented("rb_proc_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_proc_times() -> ! {
    unimplemented("rb_proc_times")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_process_status_wait() -> ! {
    unimplemented("rb_process_status_wait")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_provide() -> ! {
    unimplemented("rb_provide")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_provided() -> ! {
    unimplemented("rb_provided")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_range_beg_len() -> ! {
    unimplemented("rb_range_beg_len")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_range_new() -> ! {
    unimplemented("rb_range_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_range_values() -> ! {
    unimplemented("rb_range_values")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_refinement_new() -> ! {
    unimplemented("rb_refinement_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_alloc() -> ! {
    unimplemented("rb_reg_alloc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_backref_number() -> ! {
    unimplemented("rb_reg_backref_number")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_init_str() -> ! {
    unimplemented("rb_reg_init_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_last_match() -> ! {
    unimplemented("rb_reg_last_match")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_match() -> ! {
    unimplemented("rb_reg_match")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_match2() -> ! {
    unimplemented("rb_reg_match2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_match_last() -> ! {
    unimplemented("rb_reg_match_last")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_match_post() -> ! {
    unimplemented("rb_reg_match_post")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_match_pre() -> ! {
    unimplemented("rb_reg_match_pre")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_new() -> ! {
    unimplemented("rb_reg_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_new_str() -> ! {
    unimplemented("rb_reg_new_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_nth_defined() -> ! {
    unimplemented("rb_reg_nth_defined")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_nth_match() -> ! {
    unimplemented("rb_reg_nth_match")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_options() -> ! {
    unimplemented("rb_reg_options")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_event_hook() -> ! {
    unimplemented("rb_remove_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_method() -> ! {
    unimplemented("rb_remove_method")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_method_id() -> ! {
    unimplemented("rb_remove_method_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_require() -> ! {
    unimplemented("rb_require")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_require_string() -> ! {
    unimplemented("rb_require_string")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reserved_fd_p() -> ! {
    unimplemented("rb_reserved_fd_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reset_random_seed() -> ! {
    unimplemented("rb_reset_random_seed")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ruby_debug_ptr() -> ! {
    unimplemented("rb_ruby_debug_ptr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ruby_verbose_ptr() -> ! {
    unimplemented("rb_ruby_verbose_ptr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_scan_args_bad_format() -> ! {
    unimplemented("rb_scan_args_bad_format")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_scan_args_kw() -> ! {
    unimplemented("rb_scan_args_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_scan_args_length_mismatch() -> ! {
    unimplemented("rb_scan_args_length_mismatch")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_add() -> ! {
    unimplemented("rb_set_add")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_class_path() -> ! {
    unimplemented("rb_set_class_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_class_path_string() -> ! {
    unimplemented("rb_set_class_path_string")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_delete() -> ! {
    unimplemented("rb_set_delete")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_end_proc() -> ! {
    unimplemented("rb_set_end_proc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_foreach() -> ! {
    unimplemented("rb_set_foreach")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_lookup() -> ! {
    unimplemented("rb_set_lookup")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_new() -> ! {
    unimplemented("rb_set_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_new_capa() -> ! {
    unimplemented("rb_set_new_capa")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_set_size() -> ! {
    unimplemented("rb_set_size")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_singleton_class_clone() -> ! {
    unimplemented("rb_singleton_class_clone")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_sourcefile() -> ! {
    unimplemented("rb_sourcefile")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_sourceline() -> ! {
    unimplemented("rb_sourceline")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_spawn() -> ! {
    unimplemented("rb_spawn")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_spawn_err() -> ! {
    unimplemented("rb_spawn_err")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str2inum() -> ! {
    unimplemented("rb_str2inum")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_append() -> ! {
    unimplemented("rb_str_append")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_buf_append() -> ! {
    unimplemented("rb_str_buf_append")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_buf_cat2() -> ! {
    unimplemented("rb_str_buf_cat2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_buf_cat_ascii() -> ! {
    unimplemented("rb_str_buf_cat_ascii")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_buf_new_cstr() -> ! {
    unimplemented("rb_str_buf_new_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_capacity() -> ! {
    unimplemented("rb_str_capacity")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_cat2() -> ! {
    unimplemented("rb_str_cat2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_cmp() -> ! {
    unimplemented("rb_str_cmp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_comparable() -> ! {
    unimplemented("rb_str_comparable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_drop_bytes() -> ! {
    unimplemented("rb_str_drop_bytes")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_dup_frozen() -> ! {
    unimplemented("rb_str_dup_frozen")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_ellipsize() -> ! {
    unimplemented("rb_str_ellipsize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_encode_ospath() -> ! {
    unimplemented("rb_str_encode_ospath")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_export() -> ! {
    unimplemented("rb_str_export")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_export_locale() -> ! {
    unimplemented("rb_str_export_locale")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_format() -> ! {
    unimplemented("rb_str_format")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_free() -> ! {
    unimplemented("rb_str_free")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_hash() -> ! {
    unimplemented("rb_str_hash")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_hash_cmp() -> ! {
    unimplemented("rb_str_hash_cmp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_locktmp() -> ! {
    unimplemented("rb_str_locktmp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_modify() -> ! {
    unimplemented("rb_str_modify")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_modify_expand() -> ! {
    unimplemented("rb_str_modify_expand")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_new_frozen() -> ! {
    unimplemented("rb_str_new_frozen")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_new_shared() -> ! {
    unimplemented("rb_str_new_shared")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_new_with_class() -> ! {
    unimplemented("rb_str_new_with_class")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_offset() -> ! {
    unimplemented("rb_str_offset")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_resurrect() -> ! {
    unimplemented("rb_str_resurrect")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_set_len() -> ! {
    unimplemented("rb_str_set_len")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_shared_replace() -> ! {
    unimplemented("rb_str_shared_replace")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_split() -> ! {
    unimplemented("rb_str_split")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_strlen() -> ! {
    unimplemented("rb_str_strlen")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_sublen() -> ! {
    unimplemented("rb_str_sublen")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_subpos() -> ! {
    unimplemented("rb_str_subpos")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_subseq() -> ! {
    unimplemented("rb_str_subseq")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_tmp_new() -> ! {
    unimplemented("rb_str_tmp_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_to_interned_str() -> ! {
    unimplemented("rb_str_to_interned_str")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_unlocktmp() -> ! {
    unimplemented("rb_str_unlocktmp")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_str_update() -> ! {
    unimplemented("rb_str_update")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_string_value() -> ! {
    unimplemented("rb_string_value")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_string_value_cstr() -> ! {
    unimplemented("rb_string_value_cstr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_string_value_ptr() -> ! {
    unimplemented("rb_string_value_ptr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_alloc() -> ! {
    unimplemented("rb_struct_alloc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_alloc_noinit() -> ! {
    unimplemented("rb_struct_alloc_noinit")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_define_without_accessor() -> ! {
    unimplemented("rb_struct_define_without_accessor")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_define_without_accessor_under() -> ! {
    unimplemented("rb_struct_define_without_accessor_under")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_getmember() -> ! {
    unimplemented("rb_struct_getmember")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_initialize() -> ! {
    unimplemented("rb_struct_initialize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_struct_s_members() -> ! {
    unimplemented("rb_struct_s_members")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_sym_all_symbols() -> ! {
    unimplemented("rb_sym_all_symbols")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_symname_p() -> ! {
    unimplemented("rb_symname_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_syswait() -> ! {
    unimplemented("rb_syswait")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_alone() -> ! {
    unimplemented("rb_thread_alone")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_atfork() -> ! {
    unimplemented("rb_thread_atfork")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_atfork_before_exec() -> ! {
    unimplemented("rb_thread_atfork_before_exec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_check_ints() -> ! {
    unimplemented("rb_thread_check_ints")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_create() -> ! {
    unimplemented("rb_thread_create")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_current() -> ! {
    unimplemented("rb_thread_current")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_fd_close() -> ! {
    unimplemented("rb_thread_fd_close")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_fd_select() -> ! {
    unimplemented("rb_thread_fd_select")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_fd_writable() -> ! {
    unimplemented("rb_thread_fd_writable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_interrupted() -> ! {
    unimplemented("rb_thread_interrupted")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_local_aref() -> ! {
    unimplemented("rb_thread_local_aref")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_local_aset() -> ! {
    unimplemented("rb_thread_local_aset")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_main() -> ! {
    unimplemented("rb_thread_main")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_schedule() -> ! {
    unimplemented("rb_thread_schedule")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_sleep() -> ! {
    unimplemented("rb_thread_sleep")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_sleep_deadly() -> ! {
    unimplemented("rb_thread_sleep_deadly")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_sleep_forever() -> ! {
    unimplemented("rb_thread_sleep_forever")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_stop() -> ! {
    unimplemented("rb_thread_stop")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_wait_fd() -> ! {
    unimplemented("rb_thread_wait_fd")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_wait_for() -> ! {
    unimplemented("rb_thread_wait_for")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_wakeup_alive() -> ! {
    unimplemented("rb_thread_wakeup_alive")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_throw() -> ! {
    unimplemented("rb_throw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_throw_obj() -> ! {
    unimplemented("rb_throw_obj")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_interval() -> ! {
    unimplemented("rb_time_interval")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_nano_new() -> ! {
    unimplemented("rb_time_nano_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_new() -> ! {
    unimplemented("rb_time_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_num_new() -> ! {
    unimplemented("rb_time_num_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_timespec() -> ! {
    unimplemented("rb_time_timespec")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_timespec_interval() -> ! {
    unimplemented("rb_time_timespec_interval")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_timespec_new() -> ! {
    unimplemented("rb_time_timespec_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_time_timeval() -> ! {
    unimplemented("rb_time_timeval")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_timespec_now() -> ! {
    unimplemented("rb_timespec_now")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_typeddata_inherited_p() -> ! {
    unimplemented("rb_typeddata_inherited_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_typeddata_is_kind_of() -> ! {
    unimplemented("rb_typeddata_is_kind_of")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_uint2big() -> ! {
    unimplemented("rb_uint2big")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_uint2inum() -> ! {
    unimplemented("rb_uint2inum")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_undef() -> ! {
    unimplemented("rb_undef")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_undef_method() -> ! {
    unimplemented("rb_undef_method")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_undefine_finalizer() -> ! {
    unimplemented("rb_undefine_finalizer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_unexpected_type() -> ! {
    unimplemented("rb_unexpected_type")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_update_max_fd() -> ! {
    unimplemented("rb_update_max_fd")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_uv_to_utf8() -> ! {
    unimplemented("rb_uv_to_utf8")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_varargs_bad_length() -> ! {
    unimplemented("rb_varargs_bad_length")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_vrescue2() -> ! {
    unimplemented("rb_vrescue2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_waitpid() -> ! {
    unimplemented("rb_waitpid")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_write_error() -> ! {
    unimplemented("rb_write_error")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_write_error2() -> ! {
    unimplemented("rb_write_error2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_yield_block() -> ! {
    unimplemented("rb_yield_block")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_yield_splat() -> ! {
    unimplemented("rb_yield_splat")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_yield_splat_kw() -> ! {
    unimplemented("rb_yield_splat_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_yield_values() -> ! {
    unimplemented("rb_yield_values")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_yield_values_kw() -> ! {
    unimplemented("rb_yield_values_kw")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_brace_glob() -> ! {
    unimplemented("ruby_brace_glob")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_cleanup() -> ! {
    unimplemented("ruby_cleanup")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_default_signal() -> ! {
    unimplemented("ruby_default_signal")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_exec_node() -> ! {
    unimplemented("ruby_exec_node")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_executable_node() -> ! {
    unimplemented("ruby_executable_node")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_finalize() -> ! {
    unimplemented("ruby_finalize")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_glob() -> ! {
    unimplemented("ruby_glob")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_incpush() -> ! {
    unimplemented("ruby_incpush")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init() -> ! {
    unimplemented("ruby_init")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_loadpath() -> ! {
    unimplemented("ruby_init_loadpath")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_stack() -> ! {
    unimplemented("ruby_init_stack")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_malloc_add_size_overflow() -> ! {
    unimplemented("ruby_malloc_add_size_overflow")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_malloc_size_overflow() -> ! {
    unimplemented("ruby_malloc_size_overflow")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_native_thread_p() -> ! {
    unimplemented("ruby_native_thread_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_options() -> ! {
    unimplemented("ruby_options")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_process_options() -> ! {
    unimplemented("ruby_process_options")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_prog_init() -> ! {
    unimplemented("ruby_prog_init")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_run_node() -> ! {
    unimplemented("ruby_run_node")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_script() -> ! {
    unimplemented("ruby_script")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_argv() -> ! {
    unimplemented("ruby_set_argv")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_script_name() -> ! {
    unimplemented("ruby_set_script_name")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_setup() -> ! {
    unimplemented("ruby_setup")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_copyright() -> ! {
    unimplemented("ruby_show_copyright")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_version() -> ! {
    unimplemented("ruby_show_version")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sig_finalize() -> ! {
    unimplemented("ruby_sig_finalize")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_signal_name() -> ! {
    unimplemented("ruby_signal_name")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_stack_check() -> ! {
    unimplemented("ruby_stack_check")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_stack_length() -> ! {
    unimplemented("ruby_stack_length")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_stop() -> ! {
    unimplemented("ruby_stop")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_strtoul() -> ! {
    unimplemented("ruby_strtoul")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sysinit() -> ! {
    unimplemented("ruby_sysinit")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xcalloc() -> ! {
    unimplemented("ruby_xcalloc")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xfree() -> ! {
    unimplemented("ruby_xfree")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xmalloc() -> ! {
    unimplemented("ruby_xmalloc")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xmalloc2() -> ! {
    unimplemented("ruby_xmalloc2")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xrealloc() -> ! {
    unimplemented("ruby_xrealloc")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_xrealloc2() -> ! {
    unimplemented("ruby_xrealloc2")
}
