//! One loud stub per `rb_*` zeo does not answer yet.
//!
//! Generated by `cargo xtask cext api`. Do not edit.
//!
//! # Why every one of them exists
//!
//! Two kinds live here. A STUB is work not done, and the count going down is
//! progress. A REFUSAL is a decision that stays, and it carries its reason
//! into the raise -- so a gem author reading the message learns what to reach
//! for instead.
//!
//! A gem's `ext/**/*.c` is compiled and linked as a whole. One reference to a
//! function zeo has not written yet would fail the LINK, with a message
//! naming a symbol and no gem, no file and no line -- and it would fail even
//! when the call sits on a branch the program never takes. So every declared
//! symbol resolves, and one that is not implemented raises when it is CALLED,
//! naming itself.
//!
//! A stub disappears the moment the real function is written: the generator
//! reads `#[unsafe(no_mangle)]` out of the other files in this module, so
//! implementing one is all it takes.
//!
//! # The signatures
//!
//! A stub takes no arguments and never returns. By the C standard that is a
//! prototype mismatch; on both ABIs zeo targets it is safe. The caller passes
//! arguments in registers and on a stack it cleans up itself, the callee
//! reads none of them, and it never returns -- so there is no return value to
//! disagree about and no frame to unwind. Writing 137 correct
//! signatures would buy nothing: not one of these functions runs. 33
//! of them are refusals rather than gaps.
//!
//! # The globals
//!
//! `rb_cObject`, `rb_eArgError` and 105 others are `VALUE`
//! variables an extension reads directly, so each is a real symbol rather
//! than a stub. Each starts as `Qundef` and the loader fills it before any
//! `Init_` runs; [`GLOBALS`] is what it walks, and `every_global_is_filled`
//! is what proves none was missed. Nothing can read one before the loader
//! runs, because nothing has loaded.

use std::sync::atomic::{AtomicUsize, Ordering};

/// A `VALUE` variable C reads by name. `AtomicUsize` so Rust can write it; C
/// sees a plain `VALUE`, which is the same word.
pub type Global = AtomicUsize;

/// Every global starts here, and the loader is what moves it.
const fn unfilled() -> Global {
    AtomicUsize::new(crate::cext::value::Q_UNDEF)
}

/// Every `VALUE` global, by the name C spells.
pub static GLOBALS: &[(&str, &Global)] = &[
    ("rb_argv0", &rb_argv0),
    ("rb_cArray", &rb_cArray),
    ("rb_cBasicObject", &rb_cBasicObject),
    ("rb_cBinding", &rb_cBinding),
    ("rb_cBox", &rb_cBox),
    ("rb_cClass", &rb_cClass),
    ("rb_cComplex", &rb_cComplex),
    ("rb_cDir", &rb_cDir),
    ("rb_cEncoding", &rb_cEncoding),
    ("rb_cEnumerator", &rb_cEnumerator),
    ("rb_cFalseClass", &rb_cFalseClass),
    ("rb_cFile", &rb_cFile),
    ("rb_cFloat", &rb_cFloat),
    ("rb_cHash", &rb_cHash),
    ("rb_cIO", &rb_cIO),
    ("rb_cInteger", &rb_cInteger),
    ("rb_cMatch", &rb_cMatch),
    ("rb_cMethod", &rb_cMethod),
    ("rb_cModule", &rb_cModule),
    ("rb_cNameErrorMesg", &rb_cNameErrorMesg),
    ("rb_cNilClass", &rb_cNilClass),
    ("rb_cNumeric", &rb_cNumeric),
    ("rb_cObject", &rb_cObject),
    ("rb_cProc", &rb_cProc),
    ("rb_cRactor", &rb_cRactor),
    ("rb_cRandom", &rb_cRandom),
    ("rb_cRange", &rb_cRange),
    ("rb_cRational", &rb_cRational),
    ("rb_cRefinement", &rb_cRefinement),
    ("rb_cRegexp", &rb_cRegexp),
    ("rb_cSet", &rb_cSet),
    ("rb_cStat", &rb_cStat),
    ("rb_cString", &rb_cString),
    ("rb_cStruct", &rb_cStruct),
    ("rb_cSymbol", &rb_cSymbol),
    ("rb_cThread", &rb_cThread),
    ("rb_cTime", &rb_cTime),
    ("rb_cTrueClass", &rb_cTrueClass),
    ("rb_cUnboundMethod", &rb_cUnboundMethod),
    ("rb_default_rs", &rb_default_rs),
    ("rb_eArgError", &rb_eArgError),
    ("rb_eEOFError", &rb_eEOFError),
    ("rb_eEncCompatError", &rb_eEncCompatError),
    ("rb_eEncodingError", &rb_eEncodingError),
    ("rb_eException", &rb_eException),
    ("rb_eFatal", &rb_eFatal),
    ("rb_eFloatDomainError", &rb_eFloatDomainError),
    ("rb_eFrozenError", &rb_eFrozenError),
    ("rb_eIOError", &rb_eIOError),
    ("rb_eIOTimeoutError", &rb_eIOTimeoutError),
    ("rb_eIndexError", &rb_eIndexError),
    ("rb_eInterrupt", &rb_eInterrupt),
    ("rb_eKeyError", &rb_eKeyError),
    ("rb_eLoadError", &rb_eLoadError),
    ("rb_eLocalJumpError", &rb_eLocalJumpError),
    ("rb_eMathDomainError", &rb_eMathDomainError),
    ("rb_eNameError", &rb_eNameError),
    ("rb_eNoMatchingPatternError", &rb_eNoMatchingPatternError),
    (
        "rb_eNoMatchingPatternKeyError",
        &rb_eNoMatchingPatternKeyError,
    ),
    ("rb_eNoMemError", &rb_eNoMemError),
    ("rb_eNoMethodError", &rb_eNoMethodError),
    ("rb_eNotImpError", &rb_eNotImpError),
    ("rb_eRangeError", &rb_eRangeError),
    ("rb_eRegexpError", &rb_eRegexpError),
    ("rb_eRuntimeError", &rb_eRuntimeError),
    ("rb_eScriptError", &rb_eScriptError),
    ("rb_eSecurityError", &rb_eSecurityError),
    ("rb_eSignal", &rb_eSignal),
    ("rb_eStandardError", &rb_eStandardError),
    ("rb_eStopIteration", &rb_eStopIteration),
    ("rb_eSyntaxError", &rb_eSyntaxError),
    ("rb_eSysStackError", &rb_eSysStackError),
    ("rb_eSystemCallError", &rb_eSystemCallError),
    ("rb_eSystemExit", &rb_eSystemExit),
    ("rb_eThreadError", &rb_eThreadError),
    ("rb_eTypeError", &rb_eTypeError),
    ("rb_eZeroDivError", &rb_eZeroDivError),
    ("rb_fs", &rb_fs),
    ("rb_mComparable", &rb_mComparable),
    ("rb_mEnumerable", &rb_mEnumerable),
    ("rb_mErrno", &rb_mErrno),
    ("rb_mFileTest", &rb_mFileTest),
    ("rb_mGC", &rb_mGC),
    ("rb_mKernel", &rb_mKernel),
    ("rb_mMath", &rb_mMath),
    ("rb_mProcess", &rb_mProcess),
    ("rb_mWaitReadable", &rb_mWaitReadable),
    ("rb_mWaitWritable", &rb_mWaitWritable),
    (
        "rb_memory_view_exported_object_registry",
        &rb_memory_view_exported_object_registry,
    ),
    (
        "rb_memory_view_exported_object_registry_data_type",
        &rb_memory_view_exported_object_registry_data_type,
    ),
    ("rb_output_fs", &rb_output_fs),
    ("rb_output_rs", &rb_output_rs),
    (
        "rb_ractor_local_storage_type_free",
        &rb_ractor_local_storage_type_free,
    ),
    ("rb_rs", &rb_rs),
    ("rb_stderr", &rb_stderr),
    ("rb_stdin", &rb_stdin),
    ("rb_stdout", &rb_stdout),
    ("ruby_api_version", &ruby_api_version),
    ("ruby_copyright", &ruby_copyright),
    ("ruby_description", &ruby_description),
    (
        "ruby_digit36_to_number_table",
        &ruby_digit36_to_number_table,
    ),
    ("ruby_engine", &ruby_engine),
    ("ruby_hexdigits", &ruby_hexdigits),
    ("ruby_patchlevel", &ruby_patchlevel),
    ("ruby_platform", &ruby_platform),
    ("ruby_release_date", &ruby_release_date),
    ("ruby_version", &ruby_version),
];

/// Read one, for a caller that has the name rather than the symbol.
pub fn global(name: &str) -> Option<usize> {
    GLOBALS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, g)| g.load(Ordering::Relaxed))
}

/// Raise, naming the symbol the extension asked for.
fn unimplemented(what: &'static str) -> ! {
    crate::cext::jmp::raise(crate::builtins::not_impl_error!(
        "{what} is not implemented by zeo"
    ))
}

/// The same, for an entry zeo has DECIDED not to implement. The reason
/// travels with the raise, so a gem author reading the message learns what to
/// reach for instead.
fn refused(what: &'static str, why: &'static str) -> ! {
    crate::cext::jmp::raise(crate::builtins::not_impl_error!(
        "{what} is not supported by zeo: {why}"
    ))
}

#[unsafe(no_mangle)]
pub static rb_argv0: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cArray: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBasicObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBinding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBox: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cComplex: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cDir: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEncoding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEnumerator: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFalseClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFile: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFloat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cHash: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cIO: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cInteger: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMatch: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cModule: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNameErrorMesg: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNilClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNumeric: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cProc: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRactor: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRandom: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRange: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRational: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRefinement: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRegexp: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSet: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cString: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStruct: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSymbol: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cThread: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTime: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTrueClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cUnboundMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_default_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eArgError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEOFError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncCompatError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncodingError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eException: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFatal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFloatDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFrozenError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIOError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIOTimeoutError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIndexError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eInterrupt: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLoadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLocalJumpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eMathDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNameError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMemError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMethodError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNotImpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRangeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRegexpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRuntimeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eScriptError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSecurityError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSignal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStandardError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStopIteration: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSyntaxError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSysStackError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemCallError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemExit: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eThreadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eTypeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eZeroDivError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mComparable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mEnumerable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mErrno: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mFileTest: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mGC: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mKernel: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mMath: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mProcess: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitReadable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitWritable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_memory_view_exported_object_registry: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_memory_view_exported_object_registry_data_type: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_ractor_local_storage_type_free: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stderr: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdin: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdout: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_api_version: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_copyright: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_description: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_digit36_to_number_table: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_engine: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_hexdigits: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_patchlevel: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_platform: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_release_date: Global = unfilled();
#[unsafe(no_mangle)]
pub static ruby_version: Global = unfilled();

#[unsafe(no_mangle)]
pub extern "C" fn rb_add_event_hook2() -> ! {
    unimplemented("rb_add_event_hook2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_backtrace_locations() -> ! {
    unimplemented("rb_debug_inspector_backtrace_locations")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_current_depth() -> ! {
    unimplemented("rb_debug_inspector_current_depth")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_frame_binding_get() -> ! {
    unimplemented("rb_debug_inspector_frame_binding_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_frame_class_get() -> ! {
    unimplemented("rb_debug_inspector_frame_class_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_frame_depth() -> ! {
    unimplemented("rb_debug_inspector_frame_depth")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_frame_iseq_get() -> ! {
    unimplemented("rb_debug_inspector_frame_iseq_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_frame_self_get() -> ! {
    unimplemented("rb_debug_inspector_frame_self_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_debug_inspector_open() -> ! {
    unimplemented("rb_debug_inspector_open")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_append() -> ! {
    unimplemented("rb_econv_append")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_asciicompat_encoding() -> ! {
    unimplemented("rb_econv_asciicompat_encoding")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_binmode() -> ! {
    unimplemented("rb_econv_binmode")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_check_error() -> ! {
    unimplemented("rb_econv_check_error")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_close() -> ! {
    unimplemented("rb_econv_close")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_convert() -> ! {
    unimplemented("rb_econv_convert")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_decorate_at_first() -> ! {
    unimplemented("rb_econv_decorate_at_first")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_decorate_at_last() -> ! {
    unimplemented("rb_econv_decorate_at_last")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_encoding_to_insert_output() -> ! {
    unimplemented("rb_econv_encoding_to_insert_output")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_has_convpath_p() -> ! {
    unimplemented("rb_econv_has_convpath_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_insert_output() -> ! {
    unimplemented("rb_econv_insert_output")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_make_exception() -> ! {
    unimplemented("rb_econv_make_exception")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_open() -> ! {
    unimplemented("rb_econv_open")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_open_exc() -> ! {
    unimplemented("rb_econv_open_exc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_open_opts() -> ! {
    unimplemented("rb_econv_open_opts")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_prepare_options() -> ! {
    unimplemented("rb_econv_prepare_options")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_prepare_opts() -> ! {
    unimplemented("rb_econv_prepare_opts")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_putback() -> ! {
    unimplemented("rb_econv_putback")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_putbackable() -> ! {
    unimplemented("rb_econv_putbackable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_set_replacement() -> ! {
    unimplemented("rb_econv_set_replacement")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_str_append() -> ! {
    unimplemented("rb_econv_str_append")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_str_convert() -> ! {
    unimplemented("rb_econv_str_convert")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_substr_append() -> ! {
    unimplemented("rb_econv_substr_append")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_econv_substr_convert() -> ! {
    unimplemented("rb_econv_substr_convert")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_int_pair_to_real() -> ! {
    unimplemented("rb_int_pair_to_real")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_internal_thread_add_event_hook() -> ! {
    unimplemented("rb_internal_thread_add_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_internal_thread_remove_event_hook() -> ! {
    unimplemented("rb_internal_thread_remove_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_internal_thread_specific_get() -> ! {
    unimplemented("rb_internal_thread_specific_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_internal_thread_specific_key_create() -> ! {
    unimplemented("rb_internal_thread_specific_key_create")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_internal_thread_specific_set() -> ! {
    unimplemented("rb_internal_thread_specific_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_bufwrite() -> ! {
    unimplemented("rb_io_bufwrite")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_check_byte_readable() -> ! {
    unimplemented("rb_io_check_byte_readable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_check_char_readable() -> ! {
    unimplemented("rb_io_check_char_readable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_check_initialized() -> ! {
    unimplemented("rb_io_check_initialized")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_extract_encoding_option() -> ! {
    unimplemented("rb_io_extract_encoding_option")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_extract_modeenc() -> ! {
    unimplemented("rb_io_extract_modeenc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_fptr_finalize() -> ! {
    unimplemented("rb_io_fptr_finalize")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_make_open_file() -> ! {
    unimplemented("rb_io_make_open_file")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_maybe_wait() -> ! {
    unimplemented("rb_io_maybe_wait")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_maybe_wait_readable() -> ! {
    unimplemented("rb_io_maybe_wait_readable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_maybe_wait_writable() -> ! {
    unimplemented("rb_io_maybe_wait_writable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_modestr_fmode() -> ! {
    unimplemented("rb_io_modestr_fmode")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_modestr_oflags() -> ! {
    unimplemented("rb_io_modestr_oflags")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_oflags_fmode() -> ! {
    unimplemented("rb_io_oflags_fmode")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_open_descriptor() -> ! {
    unimplemented("rb_io_open_descriptor")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_read_check() -> ! {
    unimplemented("rb_io_read_check")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_read_pending() -> ! {
    unimplemented("rb_io_read_pending")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_set_nonblock() -> ! {
    unimplemented("rb_io_set_nonblock")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_stdio_file() -> ! {
    unimplemented("rb_io_stdio_file")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_io_synchronized() -> ! {
    unimplemented("rb_io_synchronized")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_available_p() -> ! {
    unimplemented("rb_memory_view_available_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_extract_item_members() -> ! {
    unimplemented("rb_memory_view_extract_item_members")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_fill_contiguous_strides() -> ! {
    unimplemented("rb_memory_view_fill_contiguous_strides")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_get() -> ! {
    unimplemented("rb_memory_view_get")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_get_item() -> ! {
    unimplemented("rb_memory_view_get_item")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_get_item_pointer() -> ! {
    unimplemented("rb_memory_view_get_item_pointer")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_init_as_byte_array() -> ! {
    unimplemented("rb_memory_view_init_as_byte_array")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_is_column_major_contiguous() -> ! {
    unimplemented("rb_memory_view_is_column_major_contiguous")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_is_row_major_contiguous() -> ! {
    unimplemented("rb_memory_view_is_row_major_contiguous")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_item_size_from_format() -> ! {
    unimplemented("rb_memory_view_item_size_from_format")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_parse_item_format() -> ! {
    unimplemented("rb_memory_view_parse_item_format")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_prepare_item_desc() -> ! {
    unimplemented("rb_memory_view_prepare_item_desc")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_register() -> ! {
    unimplemented("rb_memory_view_register")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_memory_view_release() -> ! {
    unimplemented("rb_memory_view_release")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_nogvl() -> ! {
    unimplemented("rb_nogvl")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_obj_set_shareable() -> ! {
    unimplemented("rb_obj_set_shareable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_postponed_job_preregister() -> ! {
    unimplemented("rb_postponed_job_preregister")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_postponed_job_register() -> ! {
    unimplemented("rb_postponed_job_register")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_postponed_job_register_one() -> ! {
    unimplemented("rb_postponed_job_register_one")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_postponed_job_trigger() -> ! {
    unimplemented("rb_postponed_job_trigger")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_absolute_path() -> ! {
    unimplemented("rb_profile_frame_absolute_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_base_label() -> ! {
    unimplemented("rb_profile_frame_base_label")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_classpath() -> ! {
    unimplemented("rb_profile_frame_classpath")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_first_lineno() -> ! {
    unimplemented("rb_profile_frame_first_lineno")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_full_label() -> ! {
    unimplemented("rb_profile_frame_full_label")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_label() -> ! {
    unimplemented("rb_profile_frame_label")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_method_name() -> ! {
    unimplemented("rb_profile_frame_method_name")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_path() -> ! {
    unimplemented("rb_profile_frame_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_qualified_method_name() -> ! {
    unimplemented("rb_profile_frame_qualified_method_name")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frame_singleton_method_p() -> ! {
    unimplemented("rb_profile_frame_singleton_method_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_frames() -> ! {
    unimplemented("rb_profile_frames")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_profile_thread_frames() -> ! {
    unimplemented("rb_profile_thread_frames")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_make_shareable() -> ! {
    unimplemented("rb_ractor_make_shareable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_make_shareable_copy() -> ! {
    unimplemented("rb_ractor_make_shareable_copy")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stderr() -> ! {
    unimplemented("rb_ractor_stderr")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stderr_set() -> ! {
    unimplemented("rb_ractor_stderr_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stdin() -> ! {
    unimplemented("rb_ractor_stdin")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stdin_set() -> ! {
    unimplemented("rb_ractor_stdin_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stdout() -> ! {
    unimplemented("rb_ractor_stdout")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_ractor_stdout_set() -> ! {
    unimplemented("rb_ractor_stdout_set")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_rand_bytes_int32() -> ! {
    unimplemented("rb_rand_bytes_int32")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_random_base_init() -> ! {
    unimplemented("rb_random_base_init")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_random_mark() -> ! {
    unimplemented("rb_random_mark")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_adjust_startpos() -> ! {
    unimplemented("rb_reg_adjust_startpos")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_onig_match() -> ! {
    unimplemented("rb_reg_onig_match")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_prepare_re() -> ! {
    unimplemented("rb_reg_prepare_re")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_region_copy() -> ! {
    unimplemented("rb_reg_region_copy")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_regsub() -> ! {
    unimplemented("rb_reg_regsub")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_reg_search() -> ! {
    unimplemented("rb_reg_search")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_event_hook_with_data() -> ! {
    unimplemented("rb_remove_event_hook_with_data")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_add_event_hook() -> ! {
    unimplemented("rb_thread_add_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_add_event_hook2() -> ! {
    unimplemented("rb_thread_add_event_hook2")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_remove_event_hook() -> ! {
    unimplemented("rb_thread_remove_event_hook")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_thread_remove_event_hook_with_data() -> ! {
    unimplemented("rb_thread_remove_event_hook_with_data")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_binding() -> ! {
    unimplemented("rb_tracearg_binding")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_callee_id() -> ! {
    unimplemented("rb_tracearg_callee_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_defined_class() -> ! {
    unimplemented("rb_tracearg_defined_class")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_eval_script() -> ! {
    unimplemented("rb_tracearg_eval_script")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_event() -> ! {
    unimplemented("rb_tracearg_event")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_event_flag() -> ! {
    unimplemented("rb_tracearg_event_flag")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_from_tracepoint() -> ! {
    unimplemented("rb_tracearg_from_tracepoint")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_instruction_sequence() -> ! {
    unimplemented("rb_tracearg_instruction_sequence")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_lineno() -> ! {
    unimplemented("rb_tracearg_lineno")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_method_id() -> ! {
    unimplemented("rb_tracearg_method_id")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_object() -> ! {
    unimplemented("rb_tracearg_object")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_parameters() -> ! {
    unimplemented("rb_tracearg_parameters")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_path() -> ! {
    unimplemented("rb_tracearg_path")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_raised_exception() -> ! {
    unimplemented("rb_tracearg_raised_exception")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_return_value() -> ! {
    unimplemented("rb_tracearg_return_value")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracearg_self() -> ! {
    unimplemented("rb_tracearg_self")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracepoint_disable() -> ! {
    unimplemented("rb_tracepoint_disable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracepoint_enable() -> ! {
    unimplemented("rb_tracepoint_enable")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracepoint_enabled_p() -> ! {
    unimplemented("rb_tracepoint_enabled_p")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_tracepoint_new() -> ! {
    unimplemented("rb_tracepoint_new")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_enc_find_basename() -> ! {
    unimplemented("ruby_enc_find_basename")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_enc_find_extname() -> ! {
    unimplemented("ruby_enc_find_extname")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_vm_at_exit() -> ! {
    unimplemented("ruby_vm_at_exit")
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_vm_destruct() -> ! {
    unimplemented("ruby_vm_destruct")
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_add_event_hook() -> ! {
    refused(
        "rb_add_event_hook",
        "the C-level TracePoint; zeo's TracePoint is Ruby-level and its event set does not line up with rb_event_flag_t",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_2comp() -> ! {
    refused(
        "rb_big_2comp",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_new() -> ! {
    refused(
        "rb_big_new",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_pack() -> ! {
    refused(
        "rb_big_pack",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_resize() -> ! {
    refused(
        "rb_big_resize",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_unpack() -> ! {
    refused(
        "rb_big_unpack",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_bulk_insert_into_st_table() -> ! {
    refused(
        "rb_hash_bulk_insert_into_st_table",
        "this hands out a Ruby Hash's internal st_table, which zeo does not store; rb_hash_foreach and rb_hash_aset reach the same data",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_tbl() -> ! {
    refused(
        "rb_hash_tbl",
        "this hands out a Ruby Hash's internal st_table, which zeo does not store; rb_hash_foreach and rb_hash_aset reach the same data",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file() -> ! {
    refused(
        "rb_load_file",
        "this answers a NODE*, MRI's parse tree; zeo compiles through prism and builds no such thing",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file_str() -> ! {
    refused(
        "rb_load_file_str",
        "this answers a NODE*, MRI's parse tree; zeo compiles through prism and builds no such thing",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_marshal_define_compat() -> ! {
    refused(
        "rb_marshal_define_compat",
        "this writes Marshal's internal compatibility table, which zeo's Marshal does not have",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_event_hook() -> ! {
    refused(
        "rb_remove_event_hook",
        "the C-level TracePoint; see rb_add_event_hook",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_cleanup() -> ! {
    refused(
        "ruby_cleanup",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_exec_node() -> ! {
    refused(
        "ruby_exec_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_executable_node() -> ! {
    refused(
        "ruby_executable_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_finalize() -> ! {
    refused(
        "ruby_finalize",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_incpush() -> ! {
    refused(
        "ruby_incpush",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init() -> ! {
    refused(
        "ruby_init",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_loadpath() -> ! {
    refused(
        "ruby_init_loadpath",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_stack() -> ! {
    refused(
        "ruby_init_stack",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_options() -> ! {
    refused(
        "ruby_options",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_process_options() -> ! {
    refused(
        "ruby_process_options",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_prog_init() -> ! {
    refused(
        "ruby_prog_init",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_run_node() -> ! {
    refused(
        "ruby_run_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_script() -> ! {
    refused(
        "ruby_script",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_argv() -> ! {
    refused(
        "ruby_set_argv",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_script_name() -> ! {
    refused(
        "ruby_set_script_name",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_setup() -> ! {
    refused(
        "ruby_setup",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_copyright() -> ! {
    refused(
        "ruby_show_copyright",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_version() -> ! {
    refused(
        "ruby_show_version",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sig_finalize() -> ! {
    refused(
        "ruby_sig_finalize",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_stop() -> ! {
    refused(
        "ruby_stop",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sysinit() -> ! {
    refused(
        "ruby_sysinit",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
