//! One loud stub per `rb_*` zeo does not answer yet.
//!
//! Generated by `tools/zeo-dev cext api`. Do not edit.
//!
//! # Why every one of them exists
//!
//! Two kinds live here. A STUB is work not done, and the count
//! going down is progress. A REFUSAL is a decision that stays, and
//! it carries its reason into the raise -- so a gem author reading
//! the message learns what to reach for instead.
//!
//! A gem's `ext/**/*.c` is compiled and linked as a whole. One
//! reference to a function zeo has not written yet would fail the
//! LINK, with a message naming a symbol and no gem, no file and no
//! line -- and it would fail even when the call sits on a branch the
//! program never takes. So every declared symbol resolves, and one
//! that is not implemented raises when it is CALLED, naming itself.
//!
//! A stub disappears the moment the real function is written: the
//! generator reads `#[unsafe(no_mangle)]` out of the other files in
//! this module, so implementing one is all it takes.
//!
//! # The signatures
//!
//! A stub takes no arguments and never returns. By the C standard
//! that is a prototype mismatch; on both ABIs zeo targets it is
//! safe. The caller passes arguments in registers and on a stack it
//! cleans up itself, the callee reads none of them, and it never
//! returns -- so there is no return value to disagree about and no
//! frame to unwind. Writing 0 correct signatures would
//! buy nothing: not one of these functions runs. 33
//! of them are refusals rather than gaps.
//!
//! # The globals
//!
//! `rb_cObject`, `rb_eArgError` and 90 others are
//! `VALUE` variables an extension reads directly, so each is a real
//! symbol rather than a stub. Each starts as `Qundef` and the
//! loader fills it before any `Init_` runs; [`GLOBALS`] is what it
//! walks, and `every_global_is_filled` is what proves none was
//! missed. Nothing can read one before the loader runs, because
//! nothing has loaded.

use std::sync::atomic::{AtomicUsize, Ordering};

/// A `VALUE` variable C reads by name. `AtomicUsize` so Rust can
/// write it; C sees a plain `VALUE`, which is the same word.
pub type Global = AtomicUsize;

/// Every global starts here, and the loader is what moves it.
const fn unfilled() -> Global {
    AtomicUsize::new(crate::cext::value::Q_UNDEF)
}

/// Every `VALUE` global, by the name C spells.
pub static GLOBALS: &[(&str, &Global)] = &[
    ("rb_argv0", &rb_argv0),
    ("rb_cArray", &rb_cArray),
    ("rb_cBasicObject", &rb_cBasicObject),
    ("rb_cBinding", &rb_cBinding),
    ("rb_cBox", &rb_cBox),
    ("rb_cClass", &rb_cClass),
    ("rb_cComplex", &rb_cComplex),
    ("rb_cDir", &rb_cDir),
    ("rb_cEncoding", &rb_cEncoding),
    ("rb_cEnumerator", &rb_cEnumerator),
    ("rb_cFalseClass", &rb_cFalseClass),
    ("rb_cFile", &rb_cFile),
    ("rb_cFloat", &rb_cFloat),
    ("rb_cHash", &rb_cHash),
    ("rb_cIO", &rb_cIO),
    ("rb_cInteger", &rb_cInteger),
    ("rb_cMatch", &rb_cMatch),
    ("rb_cMethod", &rb_cMethod),
    ("rb_cModule", &rb_cModule),
    ("rb_cNameErrorMesg", &rb_cNameErrorMesg),
    ("rb_cNilClass", &rb_cNilClass),
    ("rb_cNumeric", &rb_cNumeric),
    ("rb_cObject", &rb_cObject),
    ("rb_cProc", &rb_cProc),
    ("rb_cRandom", &rb_cRandom),
    ("rb_cRange", &rb_cRange),
    ("rb_cRational", &rb_cRational),
    ("rb_cRefinement", &rb_cRefinement),
    ("rb_cRegexp", &rb_cRegexp),
    ("rb_cSet", &rb_cSet),
    ("rb_cStat", &rb_cStat),
    ("rb_cString", &rb_cString),
    ("rb_cStruct", &rb_cStruct),
    ("rb_cSymbol", &rb_cSymbol),
    ("rb_cThread", &rb_cThread),
    ("rb_cTime", &rb_cTime),
    ("rb_cTrueClass", &rb_cTrueClass),
    ("rb_cUnboundMethod", &rb_cUnboundMethod),
    ("rb_default_rs", &rb_default_rs),
    ("rb_eArgError", &rb_eArgError),
    ("rb_eEOFError", &rb_eEOFError),
    ("rb_eEncCompatError", &rb_eEncCompatError),
    ("rb_eEncodingError", &rb_eEncodingError),
    ("rb_eException", &rb_eException),
    ("rb_eFatal", &rb_eFatal),
    ("rb_eFloatDomainError", &rb_eFloatDomainError),
    ("rb_eFrozenError", &rb_eFrozenError),
    ("rb_eIOError", &rb_eIOError),
    ("rb_eIndexError", &rb_eIndexError),
    ("rb_eInterrupt", &rb_eInterrupt),
    ("rb_eKeyError", &rb_eKeyError),
    ("rb_eLoadError", &rb_eLoadError),
    ("rb_eLocalJumpError", &rb_eLocalJumpError),
    ("rb_eMathDomainError", &rb_eMathDomainError),
    ("rb_eNameError", &rb_eNameError),
    ("rb_eNoMatchingPatternError", &rb_eNoMatchingPatternError),
    (
        "rb_eNoMatchingPatternKeyError",
        &rb_eNoMatchingPatternKeyError,
    ),
    ("rb_eNoMemError", &rb_eNoMemError),
    ("rb_eNoMethodError", &rb_eNoMethodError),
    ("rb_eNotImpError", &rb_eNotImpError),
    ("rb_eRangeError", &rb_eRangeError),
    ("rb_eRegexpError", &rb_eRegexpError),
    ("rb_eRuntimeError", &rb_eRuntimeError),
    ("rb_eScriptError", &rb_eScriptError),
    ("rb_eSecurityError", &rb_eSecurityError),
    ("rb_eSignal", &rb_eSignal),
    ("rb_eStandardError", &rb_eStandardError),
    ("rb_eStopIteration", &rb_eStopIteration),
    ("rb_eSyntaxError", &rb_eSyntaxError),
    ("rb_eSysStackError", &rb_eSysStackError),
    ("rb_eSystemCallError", &rb_eSystemCallError),
    ("rb_eSystemExit", &rb_eSystemExit),
    ("rb_eThreadError", &rb_eThreadError),
    ("rb_eTypeError", &rb_eTypeError),
    ("rb_eZeroDivError", &rb_eZeroDivError),
    ("rb_fs", &rb_fs),
    ("rb_mComparable", &rb_mComparable),
    ("rb_mEnumerable", &rb_mEnumerable),
    ("rb_mErrno", &rb_mErrno),
    ("rb_mFileTest", &rb_mFileTest),
    ("rb_mGC", &rb_mGC),
    ("rb_mKernel", &rb_mKernel),
    ("rb_mMath", &rb_mMath),
    ("rb_mProcess", &rb_mProcess),
    ("rb_mWaitReadable", &rb_mWaitReadable),
    ("rb_mWaitWritable", &rb_mWaitWritable),
    ("rb_output_fs", &rb_output_fs),
    ("rb_output_rs", &rb_output_rs),
    ("rb_rs", &rb_rs),
    ("rb_stderr", &rb_stderr),
    ("rb_stdin", &rb_stdin),
    ("rb_stdout", &rb_stdout),
];

/// Read one, for a caller that has the name rather than the symbol.
pub fn global(name: &str) -> Option<usize> {
    GLOBALS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, g)| g.load(Ordering::Relaxed))
}

/// The same, for an entry zeo has DECIDED not to implement. The
/// reason travels with the raise, so a gem author reading the
/// message learns what to reach for instead.
fn refused(what: &'static str, why: &'static str) -> ! {
    crate::cext::jmp::raise(crate::dispatch::raise_error(
        "NotImplementedError",
        format!("{what} is not supported by zeo: {why}"),
    ))
}

#[unsafe(no_mangle)]
pub static rb_argv0: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cArray: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBasicObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBinding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cBox: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cComplex: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cDir: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEncoding: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cEnumerator: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFalseClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFile: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cFloat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cHash: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cIO: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cInteger: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMatch: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cModule: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNameErrorMesg: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNilClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cNumeric: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cObject: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cProc: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRandom: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRange: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRational: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRefinement: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cRegexp: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSet: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStat: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cString: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cStruct: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cSymbol: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cThread: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTime: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cTrueClass: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_cUnboundMethod: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_default_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eArgError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEOFError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncCompatError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eEncodingError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eException: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFatal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFloatDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eFrozenError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIOError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eIndexError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eInterrupt: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLoadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eLocalJumpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eMathDomainError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNameError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMatchingPatternKeyError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMemError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNoMethodError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eNotImpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRangeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRegexpError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eRuntimeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eScriptError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSecurityError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSignal: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStandardError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eStopIteration: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSyntaxError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSysStackError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemCallError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eSystemExit: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eThreadError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eTypeError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_eZeroDivError: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mComparable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mEnumerable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mErrno: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mFileTest: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mGC: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mKernel: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mMath: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mProcess: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitReadable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_mWaitWritable: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_fs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_output_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_rs: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stderr: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdin: Global = unfilled();
#[unsafe(no_mangle)]
pub static rb_stdout: Global = unfilled();

#[unsafe(no_mangle)]
pub extern "C" fn rb_add_event_hook() -> ! {
    refused(
        "rb_add_event_hook",
        "the C-level TracePoint; zeo's TracePoint is Ruby-level and its event set does not line up with rb_event_flag_t",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_2comp() -> ! {
    refused(
        "rb_big_2comp",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_new() -> ! {
    refused(
        "rb_big_new",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_pack() -> ! {
    refused(
        "rb_big_pack",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_resize() -> ! {
    refused(
        "rb_big_resize",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_big_unpack() -> ! {
    refused(
        "rb_big_unpack",
        "this exposes MRI's Bignum digit array, which zeo does not have; rb_integer_pack and rb_integer_unpack are the supported way",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_bulk_insert_into_st_table() -> ! {
    refused(
        "rb_hash_bulk_insert_into_st_table",
        "this hands out a Ruby Hash's internal st_table, which zeo does not store; rb_hash_foreach and rb_hash_aset reach the same data",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_hash_tbl() -> ! {
    refused(
        "rb_hash_tbl",
        "this hands out a Ruby Hash's internal st_table, which zeo does not store; rb_hash_foreach and rb_hash_aset reach the same data",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file() -> ! {
    refused(
        "rb_load_file",
        "this answers a NODE*, MRI's parse tree; zeo compiles through prism and builds no such thing",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_load_file_str() -> ! {
    refused(
        "rb_load_file_str",
        "this answers a NODE*, MRI's parse tree; zeo compiles through prism and builds no such thing",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_marshal_define_compat() -> ! {
    refused(
        "rb_marshal_define_compat",
        "this writes Marshal's internal compatibility table, which zeo's Marshal does not have",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn rb_remove_event_hook() -> ! {
    refused(
        "rb_remove_event_hook",
        "the C-level TracePoint; see rb_add_event_hook",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_cleanup() -> ! {
    refused(
        "ruby_cleanup",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_exec_node() -> ! {
    refused(
        "ruby_exec_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_executable_node() -> ! {
    refused(
        "ruby_executable_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_finalize() -> ! {
    refused(
        "ruby_finalize",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_incpush() -> ! {
    refused(
        "ruby_incpush",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init() -> ! {
    refused(
        "ruby_init",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_loadpath() -> ! {
    refused(
        "ruby_init_loadpath",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_init_stack() -> ! {
    refused(
        "ruby_init_stack",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_options() -> ! {
    refused(
        "ruby_options",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_process_options() -> ! {
    refused(
        "ruby_process_options",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_prog_init() -> ! {
    refused(
        "ruby_prog_init",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_run_node() -> ! {
    refused(
        "ruby_run_node",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_script() -> ! {
    refused(
        "ruby_script",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_argv() -> ! {
    refused(
        "ruby_set_argv",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_set_script_name() -> ! {
    refused(
        "ruby_set_script_name",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_setup() -> ! {
    refused(
        "ruby_setup",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_copyright() -> ! {
    refused(
        "ruby_show_copyright",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_show_version() -> ! {
    refused(
        "ruby_show_version",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sig_finalize() -> ! {
    refused(
        "ruby_sig_finalize",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_stop() -> ! {
    refused(
        "ruby_stop",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
#[unsafe(no_mangle)]
pub extern "C" fn ruby_sysinit() -> ! {
    refused(
        "ruby_sysinit",
        "zeo's VM is already running: these boot, configure or shut down an interpreter, and an extension loaded INTO one cannot do that",
    )
}
