//! The RubyGems store zeo materializes for its own bundled libraries.
//!
//! CRuby ships its stdlib as DEFAULT GEMS: a `specifications/default/*.gemspec`
//! per library under `Gem.default_dir`, which is what makes `gem list` list
//! them, `Gem::Specification.find_by_name` find them, and Bundler believe they
//! are installed. zeo ships the same libraries as gem-shaped directories under
//! its payload, and RubyGems could not see any of them:
//! `Gem::Specification.stubs` measured 0 rows.
//!
//! The two shapes do not line up. RubyGems wants
//! `<default_dir>/gems/<name>-<version>` beside
//! `<default_dir>/specifications/default/<name>-<version>.gemspec`
//! (`Specification.default_stubs` builds exactly those two paths); zeo's
//! payload is `lib/ruby/<name>/lib`, version-less and possibly read-only. So the
//! store is BUILT, once, into the writable prefix (`home::ruby_prefix`): a
//! generated gemspec per library, and a symlink per library pointing back at
//! the payload directory. Nothing is copied, so the store costs a few hundred
//! inodes and no bytes.
//!
//! The generated gemspec carries a `# stub:` line. Without one, RubyGems falls
//! back to `Gem::Specification.load`, which `eval`s the file -- and it does
//! that for every default gem at every boot. The stub line is read with two
//! `readline`s instead (`Gem::StubSpecification#data`).

use std::path::{Path, PathBuf};

/// The gem-store directory name -- ruby's API version, NOT its release
/// version. It has to match `ruby_version` in `parse/shims/rbconfig.rb.in`,
/// because `Gem.default_dir` joins `rubylibprefix` with that value and the
/// store has to land where RubyGems will look. `the_store_matches_the_shim`
/// keeps the two honest.
pub const RUBY_API_VERSION: &str = "4.0.0";

/// One library to publish as a default gem.
pub struct DefaultGem<'a> {
    pub name: &'a str,
    pub version: &'a str,
    /// The library's own directory, which the store symlinks to.
    pub dir: &'a Path,
    /// `require_paths`, relative to `dir`.
    pub require_paths: Vec<String>,
}

/// `Gem.default_dir`: where the generated store lives.
pub fn store_dir() -> PathBuf {
    crate::home::ruby_prefix()
        .join("lib")
        .join("ruby")
        .join("gems")
        .join(RUBY_API_VERSION)
}

/// Build (or refresh) the store. Idempotent: a key file holding a hash of
/// every input short-circuits the common case to one read.
///
/// A failure here is reported and swallowed. It costs `gem list` its rows; it
/// must not fail a compile, because every program that reaches this one is a
/// program that was going to run RubyGems for some other reason.
pub fn materialize(gems: &[DefaultGem<'_>]) {
    let store = store_dir();
    if let Err(e) = try_materialize(&store, gems) {
        tracing::warn!("could not build the default-gem store: {e}");
    }
}

fn try_materialize(store: &Path, gems: &[DefaultGem<'_>]) -> std::io::Result<()> {
    let key = content_key(store, gems);
    let key_file = store.join(".zeo-key");
    if std::fs::read_to_string(&key_file).is_ok_and(|k| k == key) {
        return Ok(());
    }

    let specs = store.join("specifications").join("default");
    let gems_dir = store.join("gems");
    // Rebuilt from empty, never patched: a library that left the payload has
    // to lose its gemspec, or `gem list` reports a gem no `require` can find.
    // The key file goes first, so an interrupted rebuild is not mistaken for
    // a complete one.
    let _ = std::fs::remove_file(&key_file);
    let _ = std::fs::remove_dir_all(&specs);
    let _ = std::fs::remove_dir_all(&gems_dir);
    std::fs::create_dir_all(&specs)?;
    std::fs::create_dir_all(&gems_dir)?;

    for gem in gems {
        let full_name = format!("{}-{}", gem.name, gem.version);
        std::fs::write(specs.join(format!("{full_name}.gemspec")), gemspec(gem))?;
        link(gem.dir, &gems_dir.join(&full_name))?;
    }
    std::fs::write(&key_file, key)
}

/// The generated `specifications/default/<full name>.gemspec`.
///
/// Line 1 is discarded by the stub reader, line 2 IS the stub, and line 3 is
/// read as the extensions stub -- so all three are mandatory even though only
/// the second carries anything. The `Gem::Specification` body below them is
/// what `to_spec` evaluates when something wants more than the stub.
fn gemspec(gem: &DefaultGem<'_>) -> String {
    let paths = gem.require_paths.join("\u{0}");
    let literals: Vec<String> = gem.require_paths.iter().map(|p| format!("{p:?}")).collect();
    format!(
        "# -*- encoding: utf-8 -*-\n\
         # stub: {name} {version} ruby {paths}\n\
         # stub: \n\
         # Generated by zeo for a library it bundles. Do not edit: it is\n\
         # rebuilt whenever the bundled set changes.\n\
         Gem::Specification.new do |s|\n\
        \x20 s.name = {name:?}\n\
        \x20 s.version = {version:?}\n\
        \x20 s.require_paths = [{require_paths}]\n\
        \x20 s.summary = \"{name}, bundled with zeo\"\n\
        \x20 s.authors = []\n\
         end\n",
        name = gem.name,
        version = gem.version,
        require_paths = literals.join(", "),
    )
}

/// Point `dest` at `src`. A symlink, so the store never duplicates a payload
/// that can be hundreds of megabytes and never goes stale against it.
#[cfg(unix)]
fn link(src: &Path, dest: &Path) -> std::io::Result<()> {
    std::os::unix::fs::symlink(src, dest)
}

#[cfg(not(unix))]
fn link(src: &Path, dest: &Path) -> std::io::Result<()> {
    // No symlink guarantee off unix; the gemspecs alone still make the
    // libraries visible to `gem list`.
    let _ = (src, dest);
    Ok(())
}

/// Everything the store's contents depend on. The store PATH is in the key
/// too: a dev tree and an installed zeo resolve different prefixes, and a
/// key copied between them would claim a store that was never built there.
fn content_key(store: &Path, gems: &[DefaultGem<'_>]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut eat = |bytes: &[u8]| {
        for byte in bytes {
            hash = (hash ^ u64::from(*byte)).wrapping_mul(0x100_0000_01b3);
        }
    };
    eat(store.as_os_str().as_encoded_bytes());
    for gem in gems {
        eat(gem.name.as_bytes());
        eat(gem.version.as_bytes());
        eat(gem.dir.as_os_str().as_encoded_bytes());
        for path in &gem.require_paths {
            eat(path.as_bytes());
        }
    }
    format!("{hash:016x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gem<'a>(name: &'a str, version: &'a str, dir: &'a Path) -> DefaultGem<'a> {
        DefaultGem {
            name,
            version,
            dir,
            require_paths: vec!["lib".to_string()],
        }
    }

    /// The store directory name and the shim's `ruby_version` are one fact
    /// spelled in two files. `Gem.default_dir` reads the shim's copy, so a
    /// drift would build the store where RubyGems never looks -- and would
    /// look exactly like the empty-`stubs` bug this replaced.
    #[test]
    fn the_store_matches_the_shim() {
        let shim = include_str!(concat!(env!("OUT_DIR"), "/rbconfig.rb"));
        let want = format!("ruby_version = {RUBY_API_VERSION:?}");
        assert!(
            shim.lines().any(|l| l.trim() == want),
            "the rbconfig shim has no `{want}` line"
        );
    }

    /// The exact three-line preamble `Gem::StubSpecification#data` reads:
    /// discard, stub, extensions. Getting line 3 wrong is invisible -- the
    /// reader just falls back to eval'ing the whole file.
    #[test]
    fn the_gemspec_leads_with_a_readable_stub() {
        let spec = gemspec(&gem("uri", "1.1.1", Path::new("/x/uri")));
        let lines: Vec<&str> = spec.lines().collect();
        assert_eq!(lines[1], "# stub: uri 1.1.1 ruby lib");
        assert_eq!(lines[2], "# stub: ");
        assert!(spec.contains("s.name = \"uri\""), "{spec}");
    }

    /// Several require paths ride the stub line separated by NUL, which is
    /// what `StubLine` splits on.
    #[test]
    fn several_require_paths_are_nul_separated() {
        let mut g = gem("ext", "0.1.0", Path::new("/x/ext"));
        g.require_paths = vec!["lib".into(), "ext".into()];
        let spec = gemspec(&g);
        assert_eq!(
            spec.lines().nth(1),
            Some("# stub: ext 0.1.0 ruby lib\u{0}ext")
        );
        assert!(
            spec.contains("s.require_paths = [\"lib\", \"ext\"]"),
            "{spec}"
        );
    }

    #[test]
    fn a_changed_set_changes_the_key() {
        let store = Path::new("/store");
        let dir = Path::new("/x/uri");
        let one = content_key(store, &[gem("uri", "1.1.1", dir)]);
        assert_eq!(one, content_key(store, &[gem("uri", "1.1.1", dir)]));
        assert_ne!(one, content_key(store, &[gem("uri", "1.1.2", dir)]));
        assert_ne!(
            one,
            content_key(store, &[gem("uri", "1.1.1", Path::new("/y/uri"))])
        );
        assert_ne!(
            one,
            content_key(Path::new("/other"), &[gem("uri", "1.1.1", dir)])
        );
        assert_ne!(one, content_key(store, &[]));
    }

    /// A rebuild drops a library that left the set, rather than leaving its
    /// gemspec behind for `gem list` to report.
    #[test]
    fn a_rebuild_forgets_a_dropped_library() {
        let tmp = std::env::temp_dir().join(format!("zeo-default-gems-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let payload = tmp.join("payload");
        std::fs::create_dir_all(payload.join("uri/lib")).unwrap();
        std::fs::create_dir_all(payload.join("csv/lib")).unwrap();
        let store = tmp.join("store");
        let (uri, csv) = (payload.join("uri"), payload.join("csv"));

        try_materialize(
            &store,
            &[gem("uri", "1.1.1", &uri), gem("csv", "3.3.6", &csv)],
        )
        .unwrap();
        let specs = store.join("specifications/default");
        assert!(specs.join("uri-1.1.1.gemspec").is_file());
        assert!(specs.join("csv-3.3.6.gemspec").is_file());
        // `is_dir` follows the link, so this is the whole round trip:
        // `<store>/gems/uri-1.1.1` reaches the payload's `uri` directory.
        assert!(
            store.join("gems/uri-1.1.1/lib").is_dir(),
            "the symlink resolves"
        );

        try_materialize(&store, &[gem("uri", "1.1.1", &uri)]).unwrap();
        assert!(specs.join("uri-1.1.1.gemspec").is_file());
        assert!(
            !specs.join("csv-3.3.6.gemspec").exists(),
            "csv survived a rebuild"
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }

    /// The second call with the same set does no work at all -- the store is
    /// rebuilt on every compile that touches RubyGems otherwise.
    #[test]
    fn an_unchanged_set_is_not_rebuilt() {
        let tmp = std::env::temp_dir().join(format!("zeo-default-gems-key-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let dir = tmp.join("payload/uri");
        std::fs::create_dir_all(dir.join("lib")).unwrap();
        let store = tmp.join("store");

        try_materialize(&store, &[gem("uri", "1.1.1", &dir)]).unwrap();
        let spec = store.join("specifications/default/uri-1.1.1.gemspec");
        std::fs::write(&spec, "TOUCHED").unwrap();
        try_materialize(&store, &[gem("uri", "1.1.1", &dir)]).unwrap();
        assert_eq!(std::fs::read_to_string(&spec).unwrap(), "TOUCHED");
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
