# The cycle this program builds on purpose, and the census the
# `ZEO_RT_GCCHECK=1` leg gates against. A cycle alive at exit is not a
# defect: it is a ring the program never broke. What the leg gates is a
# CHANGE to the line below.
# 
# OptionParser's own graph. A List holds its Switches and every Switch's block closes over the parser.
#@ gccheck: cycle leak: 149 objects (Array x33, Hash x25, Proc x23, cell x17, OptionParser::OptionMap x16, OptionParser::List x8, OptionParser::Switch::NoArgument x8, OptionParser::Switch::OptionalArgument x8, OptionParser::Switch::RequiredArgument x7, OptionParser x4)
# The bundled `optparse` package (packages/optparse), exercised against the
# same program real Ruby's own OptionParser runs -- the .expected here is
# generated by CRuby with ITS optparse, so any divergence in the subset shows
# up as a byte diff.
require "optparse"
opts = {}
parser = OptionParser.new do |o|
  o.banner = "Usage: demo [options] FILE"
  o.separator ""
  o.on("-v", "--verbose", "run verbosely") { |x| opts[:verbose] = x }
  o.on("-n", "--name NAME", "the name") { |v| opts[:name] = v }
  o.on("-c", "--count=N", "how many") { |v| opts[:count] = v }
end
argv = ["-v", "--name", "matz", "-c", "3", "file.txt", "--", "-notaflag"]
rest = parser.parse!(argv)
p rest
p argv
p opts[:verbose]
p opts[:name]
p opts[:count]
puts parser.help

o2 = OptionParser.new { |o| o.on("-a", "all") {}; o.on("-b", "bee") {} }
a2 = ["-ab", "x"]
o2.parse!(a2)
p a2

begin
  OptionParser.new { |o| o.on("-x", "ex") {} }.parse!(["--nope"])
rescue OptionParser::InvalidOption => e
  p e.message
  p e.class.ancestors.include?(StandardError)
end
begin
  OptionParser.new { |o| o.on("-n", "--name NAME", "n") {} }.parse!(["--name"])
rescue OptionParser::MissingArgument => e
  p e.message
end
__END__
["file.txt", "-notaflag"]
["file.txt", "-notaflag"]
true
"matz"
"3"
Usage: demo [options] FILE

    -v, --verbose                    run verbosely
    -n, --name NAME                  the name
    -c, --count=N                    how many
["x"]
"invalid option: --nope"
true
"missing argument: --name"
