//! Emits Rust source text for the analyzed program -- the direct analog of
//! `codegen_program` (`codegen.c:4275`): walks classes/methods/top-level
//! statements, emitting `ruby_class!` macro invocations plus a `fn main()`.
//! No custom Rust AST/pretty-printer is used, matching spinel's own
//! printf-style `Buf`-into-text emission.
//!
//! The heart of this module is `emit_call`'s dispatch decision -- see "Two
//! dispatch paths" in the plan: Path 1 (static direct call, or a call
//! rewritten away entirely, e.g. `super` inlining) whenever
//! `Compiler::method_in_chain` resolves the target from the receiver's
//! statically-known class; Path 2 (`spinel_rt::send`) only when it can't.

use crate::analyze::Analyzed;
use crate::compiler::{ClassId, Compiler, OBJECT_CLASS};
use crate::hir::{HirNode, NodeId};
use crate::types::{infer_type, TyKind};

struct Ctx<'a> {
    compiler: &'a Compiler,
    current_class: Option<ClassId>,
    current_method: Option<String>,
}

pub fn codegen(analyzed: &Analyzed) -> String {
    let compiler = &analyzed.compiler;
    let mut out = String::new();
    out.push_str("// Generated by spinelc. Do not edit by hand.\n\n");

    for (idx, _) in compiler.classes.iter().enumerate() {
        if idx == 0 {
            continue; // Object -- built into spinel-rt, not user-defined
        }
        out.push_str(&emit_class(compiler, ClassId(idx as u32)));
        out.push('\n');
    }

    out.push_str("fn main() {\n");
    out.push_str("    let mut __registry = spinel_rt::ClassRegistry::new();\n");
    out.push_str("    __registry.register(spinel_rt::Object::CLASS_ID, None);\n");
    for (idx, class) in compiler.classes.iter().enumerate() {
        if idx == 0 {
            continue;
        }
        out.push_str(&format!(
            "    {}::__register(&mut __registry);\n",
            class.name
        ));
    }
    out.push_str("    spinel_rt::install_class_registry(__registry);\n\n");

    let cx = Ctx {
        compiler,
        current_class: None,
        current_method: None,
    };
    out.push_str(&emit_statements(&cx, &analyzed.main_statements));
    out.push_str("}\n");
    out
}

fn emit_class(compiler: &Compiler, cid: ClassId) -> String {
    let ci = compiler.class(cid);
    let parent = ci.parent.unwrap_or(OBJECT_CLASS);
    let parent_ty = if parent == OBJECT_CLASS {
        "spinel_rt::Object".to_string()
    } else {
        compiler.class(parent).name.clone()
    };

    let mut out = String::new();
    out.push_str("spinel_rt::ruby_class! {\n");
    out.push_str(&format!("    class {} : {} {{\n", ci.name, parent_ty));
    out.push_str(&format!("        id: {};\n", cid.0));
    out.push_str(&format!("        ivars {{ {} }}\n", ci.ivars.join(", ")));

    for &sid in &ci.methods {
        let scope = compiler.scope(sid);
        let params: String = scope
            .params
            .iter()
            .map(|p| format!(", {p}: spinel_rt::RubyValue"))
            .collect();
        let cx = Ctx {
            compiler,
            current_class: Some(cid),
            current_method: Some(scope.name.clone()),
        };
        let body = emit_body(&cx, &scope.body);
        out.push_str(&format!(
            "        def {}(&self{}) {{\n{}\n        }}\n",
            scope.name, params, body
        ));
    }

    out.push_str("    }\n}\n");
    out
}

/// Emits a method/block body as a sequence of Rust statements followed by a
/// tail expression -- Ruby's own "last expression is the implicit return"
/// semantics translate directly to a Rust block's tail-expression rule.
fn emit_body(cx: &Ctx, body: &[NodeId]) -> String {
    if body.is_empty() {
        return "spinel_rt::RubyValue::Nil".to_string();
    }
    let last = body.len() - 1;
    body.iter()
        .enumerate()
        .map(|(i, &stmt)| emit_statement(cx, stmt, i == last))
        .collect()
}

/// Emits `fn main()`'s body: statements with no implicit tail return (unlike
/// `emit_body`, every statement -- including the last -- is a plain
/// statement).
fn emit_statements(cx: &Ctx, statements: &[NodeId]) -> String {
    statements
        .iter()
        .map(|&stmt| emit_statement(cx, stmt, false))
        .collect()
}

/// One line (or block) of generated Rust for a single HIR statement.
/// `LocalWrite` needs special handling in both callers above: Rust's `let`
/// is a statement, not an expression, so it can't flow through the same
/// "expr, optionally with a trailing `;`" handling everything else uses. In
/// tail position, a bare `let` has no value to return, so a trailing
/// `RubyValue::Nil` follows it (Ruby methods whose last line is a bare
/// assignment are rare in the spike's scope; see `emit_expr`'s `LocalWrite`
/// arm for the sub-expression case, which returns the assigned value).
fn emit_statement(cx: &Ctx, stmt: NodeId, is_tail: bool) -> String {
    if let HirNode::LocalWrite(name, value) = &cx.compiler.hir[stmt] {
        let v = emit_expr(cx, *value);
        let mut out = format!("    let {name} = {v};\n");
        if is_tail {
            out.push_str("    spinel_rt::RubyValue::Nil\n");
        }
        out
    } else {
        let e = emit_expr(cx, stmt);
        if is_tail {
            format!("    {e}\n")
        } else {
            format!("    {e};\n")
        }
    }
}

fn as_int_literal(cx: &Ctx, id: NodeId) -> Option<i64> {
    match &cx.compiler.hir[id] {
        HirNode::IntegerLit(v) => Some(*v),
        _ => None,
    }
}

/// The receiver's statically-known class, if any -- the entire input to the
/// Path 1 / Path 2 decision, read straight off `infer_type` (`types.rs`).
fn infer_class(cx: &Ctx, id: NodeId) -> Option<ClassId> {
    match infer_type(cx.compiler, id) {
        TyKind::Object(cid) => Some(cid),
        _ => None,
    }
}

/// A Rust expression of type `spinel_rt::Symbol` (not `RubyValue`) -- used
/// for `send`'s second argument. A literal `:sym` skips the
/// box-then-immediately-unwrap round trip.
fn emit_symbol_expr(cx: &Ctx, id: NodeId) -> String {
    if let HirNode::SymbolLit(s) = &cx.compiler.hir[id] {
        return format!("spinel_rt::Symbol::intern({s:?})");
    }
    format!("({}).as_symbol_unchecked()", emit_expr(cx, id))
}

/// Emits a Rust expression of type `spinel_rt::RubyValue` for every HIR node
/// except `LocalWrite` (see `emit_body`). This is the direct analog of
/// spinel's `emit_expr`/`emit_call`, except spinel emits into a shared
/// mutable `Buf`; here each call returns its own text and the caller splices
/// it in, which is simpler for a tree this size and avoids a threaded
/// output-buffer parameter everywhere.
fn emit_expr(cx: &Ctx, id: NodeId) -> String {
    match &cx.compiler.hir[id] {
        HirNode::IntegerLit(v) => format!("spinel_rt::RubyValue::Int({v})"),
        HirNode::SymbolLit(s) => {
            format!("spinel_rt::RubyValue::Symbol(spinel_rt::Symbol::intern({s:?}))")
        }
        HirNode::LocalRead(name) => format!("{name}.clone()"),
        HirNode::LocalWrite(name, value) => {
            // Only reachable when a LocalWrite is used as a sub-expression
            // (not a body statement) -- none of the 7 examples do this, but
            // handle it faithfully to Ruby's "assignment evaluates to the
            // assigned value" semantics rather than silently dropping it.
            let v = emit_expr(cx, *value);
            format!("{{ let {name} = {v}; {name}.clone() }}")
        }
        HirNode::IvarRead(name) => format!("self.{name}.borrow().clone()"),
        HirNode::IvarWrite(name, value) => {
            let v = emit_expr(cx, *value);
            format!("{{ let __v = {v}; *self.{name}.borrow_mut() = __v.clone(); __v }}")
        }
        HirNode::New { class_name, args } => emit_new(cx, class_name, args),
        HirNode::SuperCall { .. } => emit_super_inline(cx),
        HirNode::Call {
            receiver,
            name,
            args,
            block,
        } => emit_call(cx, *receiver, name, args, *block),
        HirNode::Block { .. } => {
            panic!("a Block should only be reached via the Call that invokes it")
        }
        HirNode::Program(_) | HirNode::ClassDef { .. } | HirNode::DefMethod { .. } => {
            panic!("unexpected top-level-only node in expression position")
        }
    }
}

fn emit_new(cx: &Ctx, class_name: &str, args: &[NodeId]) -> String {
    let cid = cx
        .compiler
        .class_by_name(class_name)
        .unwrap_or_else(|| panic!("unknown class `{class_name}`"));
    let ci = cx.compiler.class(cid);

    let fields: String = ci
        .ivars
        .iter()
        .map(|iv| format!("{iv}: std::cell::RefCell::new(spinel_rt::RubyValue::Nil), "))
        .collect();
    let ctor = format!("{class_name} {{ {fields} }}");

    match cx.compiler.method_in_chain(cid, "initialize") {
        Some(_) => {
            let arg_exprs: Vec<String> = args.iter().map(|&a| emit_expr(cx, a)).collect();
            format!(
                "{{ let __obj = {ctor}; __obj.initialize({}); __obj }}",
                arg_exprs.join(", ")
            )
        }
        None => ctor,
    }
}

/// `super` always resolves against the *static* superclass -- never through
/// the dynamic dispatch table (mirrors `emit_super`, `codegen.c:3262`). The
/// spike implements it via statement inlining rather than a cross-type
/// function call: subclasses in this object model are distinct Rust structs
/// with no shared layout (unlike spinel's C "common initial sequence"
/// trick), so `Animal::speak(self: &Dog)` wouldn't type-check. Splicing the
/// resolved parent method's body directly into the call site sidesteps that
/// entirely -- and is a real spinel mechanism too, just used there as an
/// optimization (`emit_super_inline`, reached when the parent yields) rather
/// than the default.
fn emit_super_inline(cx: &Ctx) -> String {
    let cid = cx.current_class.expect("`super` outside a method");
    let mname = cx
        .current_method
        .as_deref()
        .expect("`super` outside a method");
    let parent = cx.compiler.class(cid).parent.unwrap_or_else(|| {
        panic!(
            "`super` in {}, which has no superclass",
            cx.compiler.class(cid).name
        )
    });
    let (defining_class, sid) = cx
        .compiler
        .method_in_chain(parent, mname)
        .unwrap_or_else(|| {
            panic!(
                "`super`: no `{mname}` found above {}",
                cx.compiler.class(cid).name
            )
        });

    let body = cx.compiler.scope(sid).body.clone();
    let inline_cx = Ctx {
        compiler: cx.compiler,
        current_class: Some(defining_class),
        current_method: Some(mname.to_string()),
    };
    format!("{{\n{}\n}}", emit_body(&inline_cx, &body))
}

fn emit_call(
    cx: &Ctx,
    receiver: Option<NodeId>,
    name: &str,
    args: &[NodeId],
    block: Option<NodeId>,
) -> String {
    // Implicit self / no receiver: the spike's only builtin is `puts`.
    let Some(recv_id) = receiver else {
        if name == "puts" && args.len() == 1 {
            return format!(
                "{{ spinel_rt::puts({}); spinel_rt::RubyValue::Nil }}",
                emit_expr(cx, args[0])
            );
        }
        panic!("unsupported implicit-self call `{name}` (spike scope)");
    };

    // Literal integer arithmetic: the spike's only unboxed-native path
    // (mirrors spinel's `sp_int_add` fast path). Narrower than spinel's
    // real inference -- only literal-on-literal, not variable-typed-as-Int
    // -- because that needs real type inference, deferred to Phase 1.
    if name == "+" && args.len() == 1 {
        if let (Some(a), Some(b)) = (as_int_literal(cx, recv_id), as_int_literal(cx, args[0])) {
            return format!("spinel_rt::RubyValue::Int(spinel_rt::int_add({a}, {b}))");
        }
    }

    // Known-shape block inlining (mirrors `emit_block_value_into`/`.times`,
    // `codegen_iter.c:1281`): the block body is spliced into a native Rust
    // `for` loop -- no closure or Proc object is allocated.
    if name == "times" {
        if let HirNode::IntegerLit(n) = &cx.compiler.hir[recv_id] {
            let n = *n;
            let block_id = block.unwrap_or_else(|| panic!("`times` requires a block"));
            let HirNode::Block { params, body } = &cx.compiler.hir[block_id] else {
                panic!("`times`'s argument must be a block");
            };
            let mut inner = String::new();
            if let Some(p) = params.first() {
                inner.push_str(&format!("let {p} = spinel_rt::RubyValue::Int(__i);\n"));
            }
            inner.push_str(&emit_body(cx, body));
            return format!("{{ for __i in 0..{n}i64 {{ {inner}; }} spinel_rt::RubyValue::Nil }}");
        }
    }

    let recv_class = infer_class(cx, recv_id);

    // `send`/`public_send`: try literal-name static resolution first
    // (mirrors spinel's `desugar_public_send_recv`) -- rewritten to a direct
    // call (Path 1) when the class is known AND the name resolves. Falls to
    // Path 2 (the genuinely new part -- see the plan's Object Model
    // section) when the receiver's class isn't known, the name isn't a
    // literal, or the literal name doesn't resolve anywhere in the chain
    // (which is exactly the `method_missing` trigger condition).
    if (name == "send" || name == "public_send") && !args.is_empty() {
        if let HirNode::SymbolLit(target) = &cx.compiler.hir[args[0]] {
            let target = target.clone();
            if let Some(cid) = recv_class {
                if cx.compiler.method_in_chain(cid, &target).is_some() {
                    return emit_call(cx, receiver, &target, &args[1..], block);
                }
            }
        }
        let cid = recv_class.unwrap_or_else(|| {
            panic!("dynamic `send` on a receiver of unknown static class (spike scope)")
        });
        let class_name = &cx.compiler.class(cid).name;
        let recv_expr = emit_expr(cx, recv_id);
        let handle = format!("{class_name}::new_handle({recv_expr})");
        let name_expr = emit_symbol_expr(cx, args[0]);
        let rest_args: String = args[1..]
            .iter()
            .map(|&a| format!("{}, ", emit_expr(cx, a)))
            .collect();
        return format!("spinel_rt::send(&{handle}, {name_expr}, &[{rest_args}])");
    }

    // Ordinary call with a statically known receiver class: direct call
    // (Path 1). This is the common case -- `method_in_chain` mirrors
    // `comp_method_in_chain` exactly (compiler.c:404).
    if let Some(cid) = recv_class {
        if cx.compiler.method_in_chain(cid, name).is_some() {
            let recv_expr = emit_expr(cx, recv_id);
            let arg_exprs: Vec<String> = args.iter().map(|&a| emit_expr(cx, a)).collect();
            return format!("({recv_expr}).{name}({})", arg_exprs.join(", "));
        }
    }

    panic!("unsupported call `{name}` (spike scope, or receiver's class isn't statically known)");
}
