//! Projects the compiler's view of the builtin METHOD/CONSTANT surface.
//!
//! The compiler folds `respond_to?`/`method_defined?`/const lookups against a
//! class's known members. For USER classes it reads the compiled program; for
//! BUILTINS that data lives in `zeo-rt` (never linked into the compiler). This
//! build script bridges the gap WITHOUT a cargo dependency edge (which would be
//! a cycle): it reads `zeo-rt/src/builtins/*.rs` as SOURCE, finds every
//! `ruby_class!`/`ruby_module!` invocation, and parses each with the SHARED
//! `zeo-dsl` grammar -- the exact parser the proc-macro uses, so the
//! compiler's folding view can never drift from what the runtime registers.
//!
//! It emits `$OUT_DIR/class_surface.rs`: a `CLASS_SURFACE` table written
//! SYMBOLICALLY (`id: zeo_abi::COMPARABLE_CLASS`), so the build script never
//! evaluates a `ClassId` const -- rustc resolves the symbol when it compiles
//! the include (see `src/builtin_surface.rs`). Only classes already migrated to
//! the macro appear; the rest stay served by `zeo_abi::BUILTINS` shape + the
//! compiler's existing (surface-blind) behavior until they migrate too.

use std::fmt::Write as _;
use std::path::Path;

use syn::parse::Parser;
use zeo_dsl::ClassSpec;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let rt_src = Path::new(&manifest_dir).join("../zeo-rt/src");

    let mut surfaces: Vec<Surface> = Vec::new();
    // The core classes (`builtins/`) and the require-gated extensions (`ext/`,
    // whose gems namespace their classes in subdirectories -- `socket/`, ...).
    // Ext surfaces are projected unconditionally of their cargo feature: the
    // surface is folding-only (a miss falls back to runtime dispatch), and an
    // un-required ext constant is unreachable regardless.
    collect_from_dir(&rt_src.join("builtins"), &mut surfaces);
    collect_from_dir(&rt_src.join("ext"), &mut surfaces);
    // Deterministic output regardless of readdir order.
    surfaces.sort_by(|a, b| a.id_const.cmp(&b.id_const));

    let mut code =
        String::from("// @generated by build.rs from ruby_class!/ruby_module! headers.\n");
    code.push_str("pub const CLASS_SURFACE: &[ClassSurface] = &[\n");
    for s in &surfaces {
        writeln!(
            code,
            "    ClassSurface {{ id: zeo_abi::{}, instance_methods: &[{}], \
             class_methods: &[{}], constants: &[{}] }},",
            s.id_const,
            str_list(&s.instance_methods),
            str_list(&s.class_methods),
            str_list(&s.constants),
        )
        .expect("writing to a String never fails");
    }
    code.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    std::fs::write(Path::new(&out_dir).join("class_surface.rs"), code)
        .expect("writing class_surface.rs");
}

/// One builtin class's projected surface.
struct Surface {
    /// The `ClassId` const's name (e.g. `COMPARABLE_CLASS`), emitted as
    /// `zeo_abi::<name>` for rustc to resolve.
    id_const: String,
    instance_methods: Vec<String>,
    class_methods: Vec<String>,
    constants: Vec<String>,
}

/// Render a name list as Rust `"a", "b"` string-literal elements.
fn str_list(items: &[String]) -> String {
    items
        .iter()
        .map(|s| format!("{s:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn collect_from_dir(dir: &Path, out: &mut Vec<Surface>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // A gem namespaces its classes in a subdirectory (`ext/socket/`).
            collect_from_dir(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            // Re-run when any source changes (a migrated header edited, a class
            // newly migrated).
            println!("cargo:rerun-if-changed={}", path.display());
            collect_from_file(&path, out);
        }
    }
}

fn collect_from_file(path: &Path, out: &mut Vec<Surface>) {
    let Ok(source) = std::fs::read_to_string(path) else {
        return;
    };
    // A file that doesn't parse as Rust can't host a macro invocation we
    // understand; skip rather than fail the whole build.
    let Ok(file) = syn::parse_file(&source) else {
        return;
    };
    collect_from_items(&file.items, out);
}

/// Walk items (recursing into inline `mod` blocks) for `ruby_class!`/
/// `ruby_module!` invocations.
fn collect_from_items(items: &[syn::Item], out: &mut Vec<Surface>) {
    for item in items {
        match item {
            syn::Item::Macro(m) => {
                if let Some(surface) = surface_from_macro(m) {
                    out.push(surface);
                }
            }
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    collect_from_items(inner, out);
                }
            }
            _ => {}
        }
    }
}

fn surface_from_macro(m: &syn::ItemMacro) -> Option<Surface> {
    let macro_name = m.mac.path.segments.last()?.ident.to_string();
    let tokens = m.mac.tokens.clone();
    let spec = match macro_name.as_str() {
        "ruby_class" => ClassSpec::parse_class.parse2(tokens).ok()?,
        "ruby_module" => ClassSpec::parse_module.parse2(tokens).ok()?,
        _ => return None,
    };
    Some(surface_from_spec(&spec))
}

fn surface_from_spec(spec: &ClassSpec) -> Surface {
    let id_const = spec
        .id
        .segments
        .last()
        .expect("a ClassId path has at least one segment")
        .ident
        .to_string();

    let mut instance_methods = Vec::new();
    let mut class_methods = Vec::new();
    for method in &spec.methods {
        let bucket = if method.is_class_method {
            &mut class_methods
        } else {
            &mut instance_methods
        };
        for name in &method.names {
            bucket.push(name.ruby.clone());
        }
    }
    // A late alias joins the bucket of the method it aliases.
    for alias in &spec.aliases {
        if class_methods.iter().any(|n| n == &alias.old_name) {
            class_methods.push(alias.new_name.clone());
        } else {
            instance_methods.push(alias.new_name.clone());
        }
    }

    let constants = spec.consts.iter().map(|c| c.name.to_string()).collect();
    Surface {
        id_const,
        instance_methods,
        class_methods,
        constants,
    }
}
