//! `rb_*` entries that ARE a Ruby method call.
//!
//! Generated by `cargo xtask check-c-headers forward`. Do not edit.
//!
//! Most of MRI's object C API is a C name for a method Ruby already has:
//! `rb_str_length` IS `String#length`. zeo answers those by CALLING the
//! method, through the same `dispatch::send_value` a Ruby program uses -- so
//! each one sees the same MRO, the same refinements, the same
//! `method_missing` and the same visibility rules, and cannot drift from the
//! method it stands for.
//!
//! Reimplementing 103 of these in Rust would be 103 more places for
//! `String#length` to be subtly wrong.

//! # The record
//!
//! Each `FORWARDED` row is a CLAIM: MRI's `rb_x` is exactly `Class#method`,
//! so zeo can answer it by calling that method rather than reimplementing it.
//! Every row was verified against the oracle -- the class HAS that method, and
//! its arity accepts this many arguments -- which rules out a name that merely
//! looks right (`rb_ary_entry` is not `Array#entry`). It does NOT rule out a
//! name that maps onto a real method with different SEMANTICS, so `DENY` in
//! `crates/xtask/src/commands/cext.rs` names the seven that do.
//!
//! The table lives HERE, beside the bodies that stand on it, so the record
//! and the code cannot drift apart. `cext forward` reads it back to
//! regenerate the bodies; `--reverify` re-asks the oracle.

use super::convert::{to_value, value_of};
use super::value::Value;
use zeo_rt::{RubyValue, Signal, Symbol};

/// `(symbol, class, method, arity)`, sorted by symbol.
///
/// `cfg(test)`: the record is read by `cext::tests` and by
/// `cargo xtask check-c-headers forward`, never by the runtime -- the bodies below are
/// what runs.
#[cfg(test)]
pub(crate) const FORWARDED: &[(&str, &str, &str, u8)] = &[
    ("rb_ary_assoc", "Array", "assoc", 1),
    ("rb_ary_cmp", "Array", "<=>", 1),
    ("rb_ary_concat", "Array", "concat", 1),
    ("rb_ary_delete", "Array", "delete", 1),
    ("rb_ary_dup", "Array", "dup", 0),
    ("rb_ary_freeze", "Array", "freeze", 0),
    ("rb_ary_includes", "Array", "include?", 1),
    ("rb_ary_join", "Array", "join", 1),
    ("rb_ary_plus", "Array", "+", 1),
    ("rb_ary_rassoc", "Array", "rassoc", 1),
    ("rb_ary_replace", "Array", "replace", 1),
    ("rb_ary_reverse", "Array", "reverse", 0),
    ("rb_ary_sort", "Array", "sort", 0),
    ("rb_ary_sort_bang", "Array", "sort!", 0),
    ("rb_ary_to_ary", "Array", "to_ary", 0),
    ("rb_ary_to_s", "Array", "to_s", 0),
    ("rb_ary_unshift", "Array", "unshift", 1),
    ("rb_big_and", "Integer", "&", 1),
    ("rb_big_clone", "Integer", "clone", 0),
    ("rb_big_cmp", "Integer", "<=>", 1),
    ("rb_big_div", "Integer", "/", 1),
    ("rb_big_divmod", "Integer", "divmod", 1),
    ("rb_big_eq", "Integer", "==", 1),
    ("rb_big_eql", "Integer", "eql?", 1),
    ("rb_big_idiv", "Integer", "div", 1),
    ("rb_big_lshift", "Integer", "<<", 1),
    ("rb_big_minus", "Integer", "-", 1),
    ("rb_big_modulo", "Integer", "%", 1),
    ("rb_big_mul", "Integer", "*", 1),
    ("rb_big_or", "Integer", "|", 1),
    ("rb_big_plus", "Integer", "+", 1),
    ("rb_big_pow", "Integer", "**", 1),
    ("rb_big_rshift", "Integer", ">>", 1),
    ("rb_big_xor", "Integer", "^", 1),
    ("rb_class_attached_object", "Class", "attached_object", 0),
    ("rb_class_subclasses", "Class", "subclasses", 0),
    ("rb_class_superclass", "Class", "superclass", 0),
    ("rb_complex_abs", "Complex", "abs", 0),
    ("rb_complex_arg", "Complex", "arg", 0),
    ("rb_complex_conjugate", "Complex", "conjugate", 0),
    ("rb_complex_div", "Complex", "/", 1),
    ("rb_complex_imag", "Complex", "imag", 0),
    ("rb_complex_minus", "Complex", "-", 1),
    ("rb_complex_plus", "Complex", "+", 1),
    ("rb_complex_pow", "Complex", "**", 1),
    ("rb_complex_real", "Complex", "real", 0),
    ("rb_fiber_alive_p", "Fiber", "alive?", 0),
    ("rb_hash_delete", "Hash", "delete", 1),
    ("rb_hash_dup", "Hash", "dup", 0),
    ("rb_hash_fetch", "Hash", "fetch", 1),
    ("rb_hash_freeze", "Hash", "freeze", 0),
    ("rb_io_binmode", "IO", "binmode", 0),
    ("rb_io_close", "IO", "close", 0),
    ("rb_io_closed_p", "IO", "closed?", 0),
    ("rb_io_eof", "IO", "eof", 0),
    ("rb_io_flush", "IO", "flush", 0),
    ("rb_io_getbyte", "IO", "getbyte", 0),
    ("rb_io_gets", "IO", "gets", 0),
    ("rb_io_path", "IO", "path", 0),
    ("rb_io_timeout", "IO", "timeout", 0),
    ("rb_io_ungetbyte", "IO", "ungetbyte", 1),
    ("rb_io_ungetc", "IO", "ungetc", 1),
    ("rb_io_wait", "IO", "wait", 2),
    ("rb_io_write", "IO", "write", 1),
    ("rb_mod_ancestors", "Module", "ancestors", 0),
    ("rb_mod_include_p", "Module", "include?", 1),
    ("rb_mod_included_modules", "Module", "included_modules", 0),
    ("rb_mod_name", "Module", "name", 0),
    ("rb_mod_remove_const", "Module", "remove_const", 1),
    ("rb_mutex_lock", "Thread::Mutex", "lock", 0),
    ("rb_mutex_locked_p", "Thread::Mutex", "locked?", 0),
    ("rb_mutex_sleep", "Thread::Mutex", "sleep", 1),
    ("rb_mutex_unlock", "Thread::Mutex", "unlock", 0),
    ("rb_obj_clone", "Object", "clone", 0),
    ("rb_obj_dup", "Object", "dup", 0),
    ("rb_obj_freeze", "Object", "freeze", 0),
    ("rb_obj_frozen_p", "Object", "frozen?", 0),
    (
        "rb_obj_instance_variables",
        "Object",
        "instance_variables",
        0,
    ),
    ("rb_obj_method", "Object", "method", 1),
    (
        "rb_obj_remove_instance_variable",
        "Object",
        "remove_instance_variable",
        1,
    ),
    ("rb_proc_lambda_p", "Proc", "lambda?", 0),
    ("rb_set_clear", "Set", "clear", 0),
    ("rb_str_concat", "String", "concat", 1),
    ("rb_str_dump", "String", "dump", 0),
    ("rb_str_equal", "String", "==", 1),
    ("rb_str_inspect", "String", "inspect", 0),
    ("rb_str_intern", "String", "intern", 0),
    ("rb_str_length", "String", "length", 0),
    ("rb_str_plus", "String", "+", 1),
    ("rb_str_replace", "String", "replace", 1),
    ("rb_str_scrub", "String", "scrub", 1),
    ("rb_str_succ", "String", "succ", 0),
    ("rb_str_times", "String", "*", 1),
    ("rb_str_to_str", "String", "to_str", 0),
    ("rb_struct_aref", "Struct", "[]", 1),
    ("rb_struct_aset", "Struct", "[]=", 2),
    ("rb_struct_members", "Struct", "members", 0),
    ("rb_struct_size", "Struct", "size", 0),
    ("rb_sym_to_s", "Symbol", "to_s", 0),
    ("rb_thread_kill", "Thread", "kill", 0),
    ("rb_thread_run", "Thread", "run", 0),
    ("rb_thread_wakeup", "Thread", "wakeup", 0),
    ("rb_time_utc_offset", "Time", "utc_offset", 0),
];

fn forward(recv: Value, meth: &str, args: &[Value]) -> Result<Value, Signal> {
    // SAFETY: every argument is an extension's own live `VALUE`.
    let recv = unsafe { value_of(recv) };
    let args: Vec<RubyValue> = args.iter().map(|a| unsafe { value_of(*a) }).collect();
    let out = zeo_rt::dispatch::send_value(&recv, Symbol::intern(meth), &args, None)?;
    to_value(&out)
}

crate::cext_fn! {
/// `Array#assoc`
fn rb_ary_assoc(recv: Value, a0: Value) -> Value {
    forward(recv, "assoc", &[a0])
}

/// `Array#<=>`
fn rb_ary_cmp(recv: Value, a0: Value) -> Value {
    forward(recv, "<=>", &[a0])
}

/// `Array#concat`
fn rb_ary_concat(recv: Value, a0: Value) -> Value {
    forward(recv, "concat", &[a0])
}

/// `Array#delete`
fn rb_ary_delete(recv: Value, a0: Value) -> Value {
    forward(recv, "delete", &[a0])
}

/// `Array#dup`
fn rb_ary_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Array#freeze`
fn rb_ary_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `Array#include?`
fn rb_ary_includes(recv: Value, a0: Value) -> Value {
    forward(recv, "include?", &[a0])
}

/// `Array#join`
fn rb_ary_join(recv: Value, a0: Value) -> Value {
    forward(recv, "join", &[a0])
}

/// `Array#+`
fn rb_ary_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Array#rassoc`
fn rb_ary_rassoc(recv: Value, a0: Value) -> Value {
    forward(recv, "rassoc", &[a0])
}

/// `Array#replace`
fn rb_ary_replace(recv: Value, a0: Value) -> Value {
    forward(recv, "replace", &[a0])
}

/// `Array#reverse`
fn rb_ary_reverse(recv: Value) -> Value {
    forward(recv, "reverse", &[])
}

/// `Array#sort`
fn rb_ary_sort(recv: Value) -> Value {
    forward(recv, "sort", &[])
}

/// `Array#sort!`
fn rb_ary_sort_bang(recv: Value) -> Value {
    forward(recv, "sort!", &[])
}

/// `Array#to_ary`
fn rb_ary_to_ary(recv: Value) -> Value {
    forward(recv, "to_ary", &[])
}

/// `Array#to_s`
fn rb_ary_to_s(recv: Value) -> Value {
    forward(recv, "to_s", &[])
}

/// `Array#unshift`
fn rb_ary_unshift(recv: Value, a0: Value) -> Value {
    forward(recv, "unshift", &[a0])
}

/// `Integer#&`
fn rb_big_and(recv: Value, a0: Value) -> Value {
    forward(recv, "&", &[a0])
}

/// `Integer#clone`
fn rb_big_clone(recv: Value) -> Value {
    forward(recv, "clone", &[])
}

/// `Integer#<=>`
fn rb_big_cmp(recv: Value, a0: Value) -> Value {
    forward(recv, "<=>", &[a0])
}

/// `Integer#/`
fn rb_big_div(recv: Value, a0: Value) -> Value {
    forward(recv, "/", &[a0])
}

/// `Integer#divmod`
fn rb_big_divmod(recv: Value, a0: Value) -> Value {
    forward(recv, "divmod", &[a0])
}

/// `Integer#==`
fn rb_big_eq(recv: Value, a0: Value) -> Value {
    forward(recv, "==", &[a0])
}

/// `Integer#eql?`
fn rb_big_eql(recv: Value, a0: Value) -> Value {
    forward(recv, "eql?", &[a0])
}

/// `Integer#div`
fn rb_big_idiv(recv: Value, a0: Value) -> Value {
    forward(recv, "div", &[a0])
}

/// `Integer#<<`
fn rb_big_lshift(recv: Value, a0: Value) -> Value {
    forward(recv, "<<", &[a0])
}

/// `Integer#-`
fn rb_big_minus(recv: Value, a0: Value) -> Value {
    forward(recv, "-", &[a0])
}

/// `Integer#%`
fn rb_big_modulo(recv: Value, a0: Value) -> Value {
    forward(recv, "%", &[a0])
}

/// `Integer#*`
fn rb_big_mul(recv: Value, a0: Value) -> Value {
    forward(recv, "*", &[a0])
}

/// `Integer#|`
fn rb_big_or(recv: Value, a0: Value) -> Value {
    forward(recv, "|", &[a0])
}

/// `Integer#+`
fn rb_big_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Integer#**`
fn rb_big_pow(recv: Value, a0: Value) -> Value {
    forward(recv, "**", &[a0])
}

/// `Integer#>>`
fn rb_big_rshift(recv: Value, a0: Value) -> Value {
    forward(recv, ">>", &[a0])
}

/// `Integer#^`
fn rb_big_xor(recv: Value, a0: Value) -> Value {
    forward(recv, "^", &[a0])
}

/// `Class#attached_object`
fn rb_class_attached_object(recv: Value) -> Value {
    forward(recv, "attached_object", &[])
}

/// `Class#subclasses`
fn rb_class_subclasses(recv: Value) -> Value {
    forward(recv, "subclasses", &[])
}

/// `Class#superclass`
fn rb_class_superclass(recv: Value) -> Value {
    forward(recv, "superclass", &[])
}

/// `Complex#abs`
fn rb_complex_abs(recv: Value) -> Value {
    forward(recv, "abs", &[])
}

/// `Complex#arg`
fn rb_complex_arg(recv: Value) -> Value {
    forward(recv, "arg", &[])
}

/// `Complex#conjugate`
fn rb_complex_conjugate(recv: Value) -> Value {
    forward(recv, "conjugate", &[])
}

/// `Complex#/`
fn rb_complex_div(recv: Value, a0: Value) -> Value {
    forward(recv, "/", &[a0])
}

/// `Complex#imag`
fn rb_complex_imag(recv: Value) -> Value {
    forward(recv, "imag", &[])
}

/// `Complex#-`
fn rb_complex_minus(recv: Value, a0: Value) -> Value {
    forward(recv, "-", &[a0])
}

/// `Complex#+`
fn rb_complex_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `Complex#**`
fn rb_complex_pow(recv: Value, a0: Value) -> Value {
    forward(recv, "**", &[a0])
}

/// `Complex#real`
fn rb_complex_real(recv: Value) -> Value {
    forward(recv, "real", &[])
}

/// `Fiber#alive?`
fn rb_fiber_alive_p(recv: Value) -> Value {
    forward(recv, "alive?", &[])
}

/// `Hash#delete`
fn rb_hash_delete(recv: Value, a0: Value) -> Value {
    forward(recv, "delete", &[a0])
}

/// `Hash#dup`
fn rb_hash_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Hash#fetch`
fn rb_hash_fetch(recv: Value, a0: Value) -> Value {
    forward(recv, "fetch", &[a0])
}

/// `Hash#freeze`
fn rb_hash_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `IO#binmode`
fn rb_io_binmode(recv: Value) -> Value {
    forward(recv, "binmode", &[])
}

/// `IO#close`
fn rb_io_close(recv: Value) -> Value {
    forward(recv, "close", &[])
}

/// `IO#closed?`
fn rb_io_closed_p(recv: Value) -> Value {
    forward(recv, "closed?", &[])
}

/// `IO#eof`
fn rb_io_eof(recv: Value) -> Value {
    forward(recv, "eof", &[])
}

/// `IO#flush`
fn rb_io_flush(recv: Value) -> Value {
    forward(recv, "flush", &[])
}

/// `IO#getbyte`
fn rb_io_getbyte(recv: Value) -> Value {
    forward(recv, "getbyte", &[])
}

/// `IO#gets`
fn rb_io_gets(recv: Value) -> Value {
    forward(recv, "gets", &[])
}

/// `IO#path`
fn rb_io_path(recv: Value) -> Value {
    forward(recv, "path", &[])
}

/// `IO#timeout`
fn rb_io_timeout(recv: Value) -> Value {
    forward(recv, "timeout", &[])
}

/// `IO#ungetbyte`
fn rb_io_ungetbyte(recv: Value, a0: Value) -> Value {
    forward(recv, "ungetbyte", &[a0])
}

/// `IO#ungetc`
fn rb_io_ungetc(recv: Value, a0: Value) -> Value {
    forward(recv, "ungetc", &[a0])
}

/// `IO#wait`
fn rb_io_wait(recv: Value, a0: Value, a1: Value) -> Value {
    forward(recv, "wait", &[a0, a1])
}

/// `IO#write`
fn rb_io_write(recv: Value, a0: Value) -> Value {
    forward(recv, "write", &[a0])
}

/// `Module#ancestors`
fn rb_mod_ancestors(recv: Value) -> Value {
    forward(recv, "ancestors", &[])
}

/// `Module#include?`
fn rb_mod_include_p(recv: Value, a0: Value) -> Value {
    forward(recv, "include?", &[a0])
}

/// `Module#included_modules`
fn rb_mod_included_modules(recv: Value) -> Value {
    forward(recv, "included_modules", &[])
}

/// `Module#name`
fn rb_mod_name(recv: Value) -> Value {
    forward(recv, "name", &[])
}

/// `Module#remove_const`
fn rb_mod_remove_const(recv: Value, a0: Value) -> Value {
    forward(recv, "remove_const", &[a0])
}

/// `Thread::Mutex#lock`
fn rb_mutex_lock(recv: Value) -> Value {
    forward(recv, "lock", &[])
}

/// `Thread::Mutex#locked?`
fn rb_mutex_locked_p(recv: Value) -> Value {
    forward(recv, "locked?", &[])
}

/// `Thread::Mutex#sleep`
fn rb_mutex_sleep(recv: Value, a0: Value) -> Value {
    forward(recv, "sleep", &[a0])
}

/// `Thread::Mutex#unlock`
fn rb_mutex_unlock(recv: Value) -> Value {
    forward(recv, "unlock", &[])
}

/// `Object#clone`
fn rb_obj_clone(recv: Value) -> Value {
    forward(recv, "clone", &[])
}

/// `Object#dup`
fn rb_obj_dup(recv: Value) -> Value {
    forward(recv, "dup", &[])
}

/// `Object#freeze`
fn rb_obj_freeze(recv: Value) -> Value {
    forward(recv, "freeze", &[])
}

/// `Object#frozen?`
fn rb_obj_frozen_p(recv: Value) -> Value {
    forward(recv, "frozen?", &[])
}

/// `Object#instance_variables`
fn rb_obj_instance_variables(recv: Value) -> Value {
    forward(recv, "instance_variables", &[])
}

/// `Object#method`
fn rb_obj_method(recv: Value, a0: Value) -> Value {
    forward(recv, "method", &[a0])
}

/// `Object#remove_instance_variable`
fn rb_obj_remove_instance_variable(recv: Value, a0: Value) -> Value {
    forward(recv, "remove_instance_variable", &[a0])
}

/// `Proc#lambda?`
fn rb_proc_lambda_p(recv: Value) -> Value {
    forward(recv, "lambda?", &[])
}

/// `Set#clear`
fn rb_set_clear(recv: Value) -> Value {
    forward(recv, "clear", &[])
}

/// `String#concat`
fn rb_str_concat(recv: Value, a0: Value) -> Value {
    forward(recv, "concat", &[a0])
}

/// `String#dump`
fn rb_str_dump(recv: Value) -> Value {
    forward(recv, "dump", &[])
}

/// `String#==`
fn rb_str_equal(recv: Value, a0: Value) -> Value {
    forward(recv, "==", &[a0])
}

/// `String#inspect`
fn rb_str_inspect(recv: Value) -> Value {
    forward(recv, "inspect", &[])
}

/// `String#intern`
fn rb_str_intern(recv: Value) -> Value {
    forward(recv, "intern", &[])
}

/// `String#length`
fn rb_str_length(recv: Value) -> Value {
    forward(recv, "length", &[])
}

/// `String#+`
fn rb_str_plus(recv: Value, a0: Value) -> Value {
    forward(recv, "+", &[a0])
}

/// `String#replace`
fn rb_str_replace(recv: Value, a0: Value) -> Value {
    forward(recv, "replace", &[a0])
}

/// `String#scrub`
fn rb_str_scrub(recv: Value, a0: Value) -> Value {
    forward(recv, "scrub", &[a0])
}

/// `String#succ`
fn rb_str_succ(recv: Value) -> Value {
    forward(recv, "succ", &[])
}

/// `String#*`
fn rb_str_times(recv: Value, a0: Value) -> Value {
    forward(recv, "*", &[a0])
}

/// `String#to_str`
fn rb_str_to_str(recv: Value) -> Value {
    forward(recv, "to_str", &[])
}

/// `Struct#[]`
fn rb_struct_aref(recv: Value, a0: Value) -> Value {
    forward(recv, "[]", &[a0])
}

/// `Struct#[]=`
fn rb_struct_aset(recv: Value, a0: Value, a1: Value) -> Value {
    forward(recv, "[]=", &[a0, a1])
}

/// `Struct#members`
fn rb_struct_members(recv: Value) -> Value {
    forward(recv, "members", &[])
}

/// `Struct#size`
fn rb_struct_size(recv: Value) -> Value {
    forward(recv, "size", &[])
}

/// `Symbol#to_s`
fn rb_sym_to_s(recv: Value) -> Value {
    forward(recv, "to_s", &[])
}

/// `Thread#kill`
fn rb_thread_kill(recv: Value) -> Value {
    forward(recv, "kill", &[])
}

/// `Thread#run`
fn rb_thread_run(recv: Value) -> Value {
    forward(recv, "run", &[])
}

/// `Thread#wakeup`
fn rb_thread_wakeup(recv: Value) -> Value {
    forward(recv, "wakeup", &[])
}

/// `Time#utc_offset`
fn rb_time_utc_offset(recv: Value) -> Value {
    forward(recv, "utc_offset", &[])
}
}
