# frozen_string_literal: true

# Generates the encoding registry and the single-byte mapping tables from the
# ruby 4.0.6 oracle:
#
#   crates/zeo-rt/src/enc/registry.rs     -- every `Encoding.list` row
#   crates/zeo-rt/src/enc/single_byte.rs  -- one 128-entry map per single-byte
#                                            encoding
#
# Run as `mise exec ruby@4.0.6 -- ruby tools/encoding_tables.rb`. Both files
# are checked in; regenerate them rather than editing by hand.
#
# The oracle decides the row ORDER (so `Encoding.list` matches), the names,
# the aliases, `dummy?` and `ascii_compatible?`. It also decides which rows
# are single-byte -- an encoding is, exactly when every one of the 256 bytes
# stands alone as one valid character.

ROOT = File.expand_path("..", __dir__)

# The encodings whose byte<->character structure this runtime implements.
# Everything else is registered by NAME only: it answers every reflection
# question correctly and refuses to transcode (see `EncKind::Registered`).
KINDS = {
  "UTF-8" => "EncKind::Utf8",
  "US-ASCII" => "EncKind::Ascii",
  "ASCII-8BIT" => "EncKind::Binary",
  "ISO-8859-1" => "EncKind::Latin1",
  "UTF-16BE" => "EncKind::Utf16 { be: true }",
  "UTF-16LE" => "EncKind::Utf16 { be: false }",
  "UTF-32BE" => "EncKind::Utf32 { be: true }",
  "UTF-32LE" => "EncKind::Utf32 { be: false }",
  "Shift_JIS" => "EncKind::MultiByte(MbFamily::Sjis)",
  "Windows-31J" => "EncKind::MultiByte(MbFamily::Sjis)",
  "EUC-JP" => "EncKind::MultiByte(MbFamily::EucJp)",
  "GBK" => "EncKind::MultiByte(MbFamily::Gbk)",
  "Big5" => "EncKind::MultiByte(MbFamily::Big5)",
}.freeze

# The dummy rows this runtime still converts, by special case in `transcode`
# (a BOM-carrying wide row, the stateful JIS escape codec). Every other dummy
# row is registered-only like any other unimplemented encoding.
CONVERTIBLE_DUMMIES = ["UTF-16", "UTF-32", "ISO-2022-JP"].freeze

# Aliases that name a RUNTIME SELECTOR rather than an encoding. CRuby moves
# them to whichever row `Encoding.default_external` / `.default_internal`
# currently names, so they cannot be static table data.
SELECTORS = ["locale", "external", "filesystem", "internal"].freeze

def const_name(name)
  name.upcase.gsub(/[-.]/, "_")
end

# Whether every byte stands alone as one valid character -- CRuby's own
# single-byte test, asked of the oracle rather than assumed from the name.
def single_byte?(enc)
  (0..255).all? do |b|
    s = b.chr.force_encoding(enc)
    s.valid_encoding? && s.length == 1
  rescue StandardError
    false
  end
end

# The Unicode scalar each byte 0x80..0xFF stands for, or nil where CRuby
# refuses the conversion (a valid character with no Unicode mapping).
def high_map(enc)
  (0x80..0xFF).map do |b|
    b.chr.force_encoding(enc).encode("UTF-8").ord
  rescue StandardError
    nil
  end
end

# Whether CRuby case-maps this encoding's non-ASCII letters through Unicode
# (the windows-125x and ISO-8859 families) or leaves them alone (KOI8-R).
def unicode_case?(enc)
  (0x80..0xFF).any? do |b|
    s = b.chr.force_encoding(enc)
    s.upcase != s || s.downcase != s
  rescue StandardError
    false
  end
end

rows = Encoding.list.map do |enc|
  aliases = enc.names.drop(1).reject { |a| SELECTORS.include?(a) }
  single = single_byte?(enc)
  {
    enc: enc,
    name: enc.name,
    aliases: aliases,
    dummy: enc.dummy?,
    ascii_compatible: enc.ascii_compatible?,
    single: single,
  }
end

# Rows that could carry a generated 128-entry map: single-byte, not dummy,
# and not already covered by a structural kind (ASCII-8BIT is raw bytes,
# ISO-8859-1 maps byte to codepoint).
candidates = rows.select { |r| r[:single] && !r[:dummy] && !KINDS.key?(r[:name]) }

candidates.each do |r|
  low = (0..127).all? { |b| b.chr.force_encoding(r[:enc]).encode("UTF-8") == b.chr }
  raise "#{r[:name]}: low half is not ASCII" unless low

  map = high_map(r[:enc])
  over = map.compact.find { |cp| cp > 0xFFFF }
  raise "#{r[:name]}: U+#{over.to_s(16)} needs more than 16 bits" if over

  # CRuby registers a few single-byte encodings with no transcoder at all
  # (Windows-1258, GB1988, macCentEuro, macThai): every high byte is a valid
  # character with no Unicode mapping to be had. A table of nothing would say
  # "undefined conversion" where CRuby says "converter not found", so those
  # rows stay registered-only instead.
  next if map.compact.empty?

  r[:hi] = map
  r[:unicode_case] = unicode_case?(r[:enc])
end

tables = candidates.select { |r| r[:hi] }

# ---------------------------------------------------------------- registry.rs

reg = +<<~HEADER
  //! The encoding registry: every row of ruby 4.0.6's `Encoding.list`, in its
  //! order, so `Encoding.list`, `.name_list`, `.aliases`, `.find` and the
  //! `Encoding::*` constants all answer exactly what CRuby answers.
  //!
  //! GENERATED by `tools/encoding_tables.rb` -- regenerate, do not edit.
  //!
  //! A row's `kind` says how much of the encoding this runtime IMPLEMENTS.
  //! [`EncKind::Registered`] rows carry a name, aliases and every reflection
  //! answer, but no byte<->character mapping: they read as one byte per
  //! character and refuse to transcode anything but ASCII.

  use crate::enc::mb::MbFamily;
  use crate::enc::single_byte;
  use crate::enc::table::{EncKind, EncodingId, EncodingSpec};

HEADER

rows.each_with_index do |r, i|
  reg << "pub const #{const_name(r[:name])}: EncodingId = EncodingId(#{i});\n"
end

reg << "\npub static ENCODINGS: &[EncodingSpec] = &[\n"
rows.each do |r|
  kind =
    if KINDS.key?(r[:name])
      KINDS[r[:name]]
    elsif r[:dummy]
      CONVERTIBLE_DUMMIES.include?(r[:name]) ? "EncKind::Binary" : "EncKind::Registered"
    elsif r[:hi]
      "EncKind::SingleByte"
    else
      "EncKind::Registered"
    end
  table = r[:hi] ? "Some(&single_byte::#{const_name(r[:name])})" : "None"
  aliases = r[:aliases].map { |a| a.inspect }.join(", ")
  reg << <<~ROW
    EncodingSpec {
        name: #{r[:name].inspect},
        aliases: &[#{aliases}],
        ascii_compatible: #{r[:ascii_compatible]},
        kind: #{kind},
        table: #{table},
        dummy: #{r[:dummy]},
    },
  ROW
end
reg << "];\n"

File.write(File.join(ROOT, "crates/zeo-rt/src/enc/registry.rs"), reg)

# ------------------------------------------------------------- single_byte.rs

sb = +<<~HEADER
  //! Single-byte encodings beyond Latin-1: per-byte Unicode mapping tables.
  //!
  //! GENERATED by `tools/encoding_tables.rb` from the ruby 4.0.6 oracle -- for
  //! every byte 0x80..=0xFF, the Unicode scalar CRuby's own converter
  //! produces, or `0` where CRuby raises `Encoding::UndefinedConversionError`.
  //! Deliberately NOT the WHATWG (encoding_rs) tables -- those fill several
  //! undefined vendor-page slots with C1 controls (windows-1252 `0x81` ->
  //! U+0081) where CRuby refuses the conversion, and this table IS the
  //! compatibility contract. Every byte is still a valid CHARACTER in its
  //! encoding (`valid_encoding?` is true and `length` counts it) -- an unmapped
  //! slot only refuses transcoding OUT.
  //!
  //! The low half (0x00..=0x7F) is ASCII in every one of these encodings and
  //! is not tabulated.

  /// One single-byte encoding's mapping surface.
  pub struct SingleByteTable {
      /// Whether CRuby case-maps this encoding through full Unicode case
      /// mapping (the windows-125x and ISO-8859 families) or folds ASCII
      /// letters only (KOI8-R, whose Cyrillic letters CRuby leaves uncased).
      pub unicode_case: bool,
      /// Unicode scalar for byte `0x80 + i`, or `0` for a valid byte with no
      /// Unicode mapping. U+0000 never appears as a high-half mapping, so it
      /// is free to carry that meaning.
      hi: [u16; 128],
  }

  impl SingleByteTable {
      /// The Unicode scalar for `byte`, `None` for a valid-but-unmapped one.
      pub fn decode(&self, byte: u8) -> Option<char> {
          if byte < 0x80 {
              return Some(byte as char);
          }
          char::from_u32(self.hi[(byte - 0x80) as usize] as u32).filter(|c| *c != '\\0')
      }

      /// The byte encoding `c`, or `None` when this encoding can't represent
      /// it. A linear scan of 128 entries -- fine for the transcode path,
      /// which is never hot.
      pub fn encode(&self, c: char) -> Option<u8> {
          let cp = c as u32;
          if cp < 0x80 {
              return Some(cp as u8);
          }
          let want = u16::try_from(cp).ok()?;
          if want == 0 {
              return None;
          }
          self.hi
              .iter()
              .position(|e| *e == want)
              .map(|i| (i + 0x80) as u8)
      }
  }
HEADER

tables.each do |r|
  sb << "\npub static #{const_name(r[:name])}: SingleByteTable = SingleByteTable {\n"
  sb << "    unicode_case: #{r[:unicode_case]},\n"
  sb << "    hi: [\n"
  r[:hi].each_slice(8) do |chunk|
    sb << "        " << chunk.map { |cp| format("0x%04X,", cp || 0) }.join(" ") << "\n"
  end
  sb << "    ],\n};\n"
end

File.write(File.join(ROOT, "crates/zeo-rt/src/enc/single_byte.rs"), sb)

warn "#{rows.size} encodings, #{tables.size} single-byte tables"
